Fix camera image update time check for asynchronous controller
cyberbotics/webots pull request #2138
Opened 2020-08-20 09:03 UTC by stefaniapedrazzi

**Description**
Fix #1926: fix image update time in case of asynchronous controller.

2020-08-24 12:52 UTC, omichel commented on src/Controller/api/robot_private.h
> +bool wb_robot_get_synchronization();
I believe we should not add public API functions into private include files like this `robot_private.h` file, as it is redundant with the public include files. Instead, we should `#include <webots/robot.h>` from the C file. The same probably applies to `wb_robot_get_time()` and maybe other functions.

2020-08-28 12:16 UTC, DavidMansolino commented
:eyes:

2020-08-28 12:33 UTC, DavidMansolino requested changes
Just one minor typo.

2020-08-28 12:33 UTC, DavidMansolino commented on projects/samples/devices/controllers/camera/camera.c
> +    else if (!image) {  // image may be NULL is Robot.synchronization is FALSE
```suggestion
    else if (!image) {  // image may be NULL if Robot.synchronization is FALSE
```

2020-08-28 12:37 UTC, DavidMansolino approved these changes
Thank you both!

2020-08-28 14:12 UTC, merged