Add ros dependencies to snap package too.
cyberbotics/webots pull request #2190
Opened 2020-09-01 13:38 UTC by DavidMansolino

**Description**
The snap package was missing the ros controller dependencies.

2020-09-01 18:30 UTC, DavidMansolino commented
I just tested the snap package created from this branch (https://github.com/cyberbotics/webots/releases/tag/untagged-164af96012d1f741e76f) and the ros controller is now working fine :tada:

2020-09-01 20:40 UTC, omichel approved these changes

2020-09-02 06:14 UTC, omichel requested changes
One minor detail...

2020-09-02 06:14 UTC, omichel commented on scripts/packaging/webots_distro.c
> +      add_ros_dependencies("debian/usr/local/webots/");
```suggestion
      add_ros_dependencies("debian/usr/local/webots");
```

2020-09-02 11:19 UTC, omichel approved these changes
Thank you.

2020-09-02 11:20 UTC, merged