Add Webots Privacy Policy
cyberbotics/webots pull request #2223
Opened 2020-09-10 14:39 UTC by stefaniapedrazzi

Address #1652:
add privacy policy for transparency and to be compliant with GDPR.

2020-09-11 07:46 UTC, omichel commented
I realize that this about box looks pretty bad. In particular, it misses the version information which anybody expect to see in a about box. So, above the copyright notice, it would be nice to see with a slightly bigger font "Webots R2020b revision 1". What do you think? Also I would remove "Our" in "Our Website".

2020-09-14 07:51 UTC, stefaniapedrazzi commented
Here is a new proposal for the About box.
I took inspiration from the one of Blender.

![about2](https://user-images.githubusercontent.com/5910449/93058223-5d93ee00-f66f-11ea-8caa-171bcc118553.png)

2020-09-14 08:12 UTC, omichel commented
It looks very good to me. Does the date correspond to the compilation date?

2020-09-14 08:15 UTC, stefaniapedrazzi commented
> It looks very good to me. Does the date correspond to the compilation date?

Yes, it should correspond to the compilation date.
It is computed based on the `WbApplicationInfo::releaseDate` (that uses the ``__DATE__`` macro).

2020-09-14 09:30 UTC, omichel requested changes
Thank you.
I have a few suggestions...

2020-09-14 09:30 UTC, omichel commented on docs/guide/privacy-policy.md
> +This Privacy Policy applies to the personal data of "Webots" software that may be collected through [https://cyberbotics.com](https://cyberbotics.com).
```suggestion
This Privacy Policy applies to the personal data of the "Webots" software that may be collected through [https://cyberbotics.com](https://cyberbotics.com).
```

2020-09-14 09:30 UTC, omichel commented on docs/guide/privacy-policy.md
> +After being anonymized, the collected personal information are published for on the telemetry page on [https://cyberbotics.com](https://cyberbotics.com).
```suggestion
After being anonymized, the collected personal information are published on the telemetry page at [https://cyberbotics.com/telemetry](https://cyberbotics.com/telemetry).
The purpose of this publication is openness and transparency.
It allows anyone to consider this data to better contribute to the Webots software.
```

2020-09-14 09:30 UTC, omichel commented on docs/guide/privacy-policy.md
> +To exercise your rights under these provisions, please contact us at the “Communications” details below.
```suggestion
To exercise your rights under these provisions, please contact us (see “Communications” section below).
```

2020-09-14 09:30 UTC, omichel commented on docs/guide/privacy-policy.md
> +Latest update: September 10, 2020.
```suggestion
Latest update: September 14th, 2020.
```

2020-09-14 09:30 UTC, omichel commented on src/webots/gui/WbAboutBox.cpp
> +  versionInfo->setText(QString("<p style='font-size: large;'><b>%1</b></p>"
It looks better to me if Webots is printed before the version number...
```suggestion
  versionInfo->setText(QString("<p style='font-size: large;'><b>Webots %1</b></p>"
```

2020-09-14 09:55 UTC, omichel approved these changes
Thank you.

2020-09-14 10:53 UTC, merged

2020-09-17 06:53 UTC, omichel commented
It seems that for some users, the display of the date seems wrong (probably related with the locale):
![webots R2020b rev2](https://user-images.githubusercontent.com/1264964/93430590-33d30500-f8c3-11ea-9dc5-2d03228e39c5.png)

2020-09-17 06:57 UTC, DavidMansolino commented
> probably related with the locale

Most probably due to the use of `Qt::SystemLocaleShortDate`.

2020-09-17 07:34 UTC, stefaniapedrazzi commented
i will change so that it will be independent from the locale settings.