Supervisor documentation: add missing field type values
cyberbotics/webots pull request #2272
Opened 2020-09-28 13:50 UTC by stefaniapedrazzi

**Description**
Fix missing field types in Supervisor documentation for the C++, Python, Java and MATLAB documentation.
Currently they are only documented in the C API.

**Documentation**
https://www.cyberbotics.com/doc/reference/supervisor#wb_supervisor_field_get_type?version=documentation-fix-missing-field-types

2020-09-28 14:34 UTC, omichel commented
Very good, thank you.
But we should maybe explain what is the `WB_MF` (or `MF`) case in the description and how should it be used.

2020-09-28 15:04 UTC, stefaniapedrazzi commented
I added an explanation.
Not sure if an example is also needed and if we should provide the example for all the programming languages.

2020-09-28 15:10 UTC, omichel requested changes
Thank you.
I believe this explanation is clear and sufficient and we don't need an example.

2020-09-28 15:10 UTC, omichel commented on docs/reference/supervisor.md
> +> **Note** [C++, Java, Python]: In the oriented-object APIs, the SF_* and MF_* constants are available as static integers of the `Field` class (for example, Field::SF\_BOOL).
```suggestion
> **Note** [C++, Java, Python]: In the oriented-object APIs, the SF\_* and MF\_* constants are available as static integers of the `Field` class (for example, Field::SF\_BOOL).
```

2020-09-30 09:53 UTC, omichel approved these changes

2020-09-30 09:56 UTC, merged