Fix Supervisor API field operations
cyberbotics/webots pull request #2375
Opened 2020-10-22 06:44 UTC by stefaniapedrazzi

Address #2292.

The `wb_supervisor_field_get_*` functions return inconsistent values during the same controller step if a previous `wb_supervisor_field_set_*` instructions is called:
* it returns the correct updated value before the set instruction(s) are sent to Webots
* it returns the old value after the set instruction(s) are sent to Webots and are no longer stored on the controller side

It is well [documented](https://www.cyberbotics.com/doc/reference/supervisor#wb_supervisor_field_set_sf_bool) that values could be wrong, but it very unclear for users why sometimes they are correct and sometimes not.

In this PR I tried to fix this behavior by keeping as long as possible the set operation list on the controller side and send it to Webots only if another field operation is requested ensuring that the set operations are applied before the other field operation.

Improved documentation:
https://www.cyberbotics.com/doc/reference/supervisor?version=fix-supervisor-field-operations#wb_supervisor_field_set_sf_bool

2020-10-22 09:09 UTC, stefaniapedrazzi commented
I still have to add an entry in the ChangeLog.

2020-10-22 15:59 UTC, omichel requested changes

2020-10-26 08:25 UTC, stefaniapedrazzi commented
There are issues retrieving packages in the appveyor test, but it doesn't seem related to this PR.
https://ci.appveyor.com/project/omichel/webots/builds/35952083

2020-10-26 08:46 UTC, omichel approved these changes
Thank you.
(yes, it seems some appveyor servers are currently down)

2020-10-26 08:48 UTC, merged