Add xvfb to requirements.
cyberbotics/webots pull request #2466
Opened 2020-11-18 16:14 UTC by brettle

**Description**
The build of the snap fails on a stock bionic system because xvfb is not installed.

2020-11-18 16:33 UTC, stefaniapedrazzi commented
Thank you!

But in this case `xvfb` is only needed to create the snap and for running Webots on native systems, so we don't want to add it as a runtime dependency of Webots.
This should be added in the [webots-snap](https://github.com/cyberbotics/webots-snap) repo.

2020-11-18 16:42 UTC, brettle commented
Since `make install` fails on a stock headless bionic system, I'd argue this is a bug in this repo not `webots-snap`. I agree it's a build dependency, not a runtime dependency though.

2020-11-18 16:46 UTC, stefaniapedrazzi commented
Here are the instruction for example for installing Webots on Docker:
https://github.com/cyberbotics/webots/wiki/Docker#get-and-compile-webots
where it is specified that `xvfb` has to be installed.
But this is only required for running Webots on headless systems.
It is a very particular case and we don't want to install xvfb on other systems using the default installation scripts.

We can evaluate if it makes sense to add an additional script for headless system, but it will contain only `xvfb` for the moment, so I'm not sure it makes much sense.

2020-11-18 16:51 UTC, stefaniapedrazzi commented
I can add it in the Linux installation page:
https://github.com/cyberbotics/webots/wiki/Linux-installation

2020-11-18 17:01 UTC, brettle commented
If it's added in the compilation dependencies script, it won't be included in the deb package, right? It will just be installed for people trying to build from source. The addition would simplify the build documentation. I'm really not seeing the downside.

2020-11-18 17:02 UTC, stefaniapedrazzi commented
The downside is that it will be installed on the computer of all the users and developers that are compiling Webots and have a monitor and won't need the `xvfb` package on their system.

2020-11-18 17:17 UTC, brettle commented
It's only 2.2MB which is a drop in the bucket compared to all of the other deps that need to be installed to build from source. Weigh that against the time and frustration of developers who need it but don't have it installed. For example, it has taken you multiple attempts to get [the new automated snap build](https://github.com/cyberbotics/webots-snap/pull/23) to work because of this issue. That would not have occurred if this had been fixed.

2020-11-19 09:48 UTC, stefaniapedrazzi commented
Yes, in https://github.com/cyberbotics/webots-snap/pull/23 I'm experimenting but it is clear from the error message that `xvfb` is causing issues.

I got your point and I'm taking seriously into consideration your use case. But we should also consider all the other use cases. For example to run Webots in headless system it is not enough to install `xvfb` but it also needs to be setup before being able to start Webots.

So we think that the best option is, in the runtime dependencies script, to check if the system is headless, for example checking if the `DISPLAY` environment variable is empty, and if yes install `xvfb`.

A second step, as much importart as this one, would be to automatically setup and start `xvfb` and the other variables if the DISPLAY variable is empty (headless mode) so that Webots can be started out of the box.

2020-11-19 17:04 UTC, brettle commented
Sounds reasonable. I've made the suggested changes to the scripts and packaging Makefile. I'm assuming that getting webots to start out of the box on a headless server will be addressed separately.

2020-11-23 09:25 UTC, stefaniapedrazzi requested changes
There are some syntax errors making the tests crashing and a slightly different approach should be used in the packaging Makefile to not break the automatic generation of snap packages.

2020-11-23 09:25 UTC, stefaniapedrazzi commented on scripts/packaging/Makefile
> +endif
See previous comment
```suggestion
```

2020-11-25 10:51 UTC, stefaniapedrazzi approved these changes
Thank you!

I restarted the tests that were failing due to issues with in some dependency and now the Linux tests passed successfully.

2020-11-26 08:19 UTC, merged