First prototype of URL download & caching
cyberbotics/webots pull request #2591
Opened 2020-12-21 17:05 UTC by omichel

This PR implement support for URL download and caching.
It addresses partly #1638,

2021-01-19 10:25 UTC, lukicdarkoo approved these changes
Nice! I briefly checked and it works fine on Ubuntu

2021-01-19 10:25 UTC, lukicdarkoo commented on src/webots/nodes/WbImageTexture.cpp
> +  if (mUrl->item(0).startsWith("https://"))
`http://` should be included as well?

2021-01-19 15:47 UTC, omichel commented
I applied your suggestions and re-passed the tests.

2021-01-19 17:14 UTC, lukicdarkoo requested changes
`hall.wbt` is all black, but I am not sure whether it is related to this PR or something else.

2021-01-19 17:14 UTC, lukicdarkoo commented on projects/samples/howto/url/controllers/url/Makefile
> +# Copyright 1996-2021 Cyberbotics Ltd.
This file should be included to `projects/samples/howto/Makefile` and the description is missing in `samples-howto.md`.

2021-01-20 09:27 UTC, omichel commented
Yes, it seems the problem with `hall.wbt` is caused by this PR. I am investigating it.

2021-01-20 13:23 UTC, omichel commented
It turns out the `hall.wbt` world has no light at all, so it seems normal that it should appear black.
However, it doesn't appear black on the `develop` branch, and I don't understand why...

2021-01-20 13:33 UTC, DavidMansolino commented
> However, it doesn't appear black on the develop branch, and I don't understand why...

It is because the background is producing some light. This is a commun technic used to optimize performance to use only the background to illuminate the scene (and additionally it it looks more realistic in indoors environment where the source of the light is extremely diffuse).

The fact that it doesn't work in this branch probably indicates that the `*IrradianceUrl` images of the background are not loaded.

2021-01-20 13:35 UTC, omichel commented
> It is because the background is producing some light. This is a commun technic used to optimize performance to use only the background to illuminate the scene (and additionally it it looks more realistic in indoors environment where the source of the light is extremely diffuse).
>
> The fact that it doesn't work in this branch probably indicates that the *IrradianceUrl images of the background are not loaded.

That makes sense. Thank you!

2021-01-20 15:49 UTC, omichel commented
Now the `hall.wbt` is rendered properly (thanks to @DavidMansolino!)

2021-01-22 16:06 UTC, lukicdarkoo submitted a review, later dismissed
Looks good to me. However, it would be good that @stefaniapedrazzi check it again.

2021-01-25 12:36 UTC, stefaniapedrazzi requested changes
Globally everything is fine, but I found a couple of issues:
* as described more in detail in one of the comments, deleting the `ImageTexture` url item (`PBRAppearance` node) doesn't trigger the object appearance change in the 3D view
* `Background`:
    * also in this case deleting one `*Url` value doesn't trigger the scene update (I have to save and revert the world to see the black background)
    * the console message warning about the incomplete cubemap when one of the `*Url` field is empty is no longer printed in the console. I would keep it as it helps users understanding why the background is still black after defining some of the fields

2021-01-25 12:36 UTC, stefaniapedrazzi commented on src/webots/nodes/WbBackground.cpp
> +      warn(tr("Cannot not retrieve '%1': %2").arg(url).arg(mDownloader[i]->error()));
```suggestion
      warn(tr("Cannot retrieve '%1': %2").arg(url).arg(mDownloader[i]->error()));
```

2021-01-25 12:36 UTC, stefaniapedrazzi commented on src/webots/nodes/WbBackground.cpp
> +      return false;
Is it not needed to delete `device` before returning?
Same for the other return cases later in this function.

2021-01-25 12:36 UTC, stefaniapedrazzi commented on src/webots/nodes/WbBackground.cpp
> +      return false;
Is it not needed to delete `device` before returning?

2021-01-25 13:50 UTC, omichel commented on src/webots/app/WbApplication.cpp
> -  if (!mWorldLoadingProgressDialogCreated && mWorldLoadTimer && (mWorldLoadTimer->elapsed() / 1000) > 2) {
I just explained in the PR description.

2021-01-27 13:42 UTC, omichel commented
Thank you @stefaniapedrazzi for the in depth review. I believe I fixed all the problems you reported.

2021-01-27 16:01 UTC, stefaniapedrazzi requested changes
Thank you! Yes, all my previous comments were fixed.

There is still an issue with the irradiance cubemap.
If the cubemap is complete but the irradiance cubemap is not complete,  Webots crashes with the following log:
```
webots-bin: TextureCubeMap.cpp:73: virtual void wren::TextureCubeMap::prepareGl(): Assertion `mDatas[i]' failed.
```

I can reproduce it by converting to base nodes the `TexturedBackround` PROTO, deleting one of the `*IrradianceUrl` item, saving and reverting the world.
Maybe there are also some update issues, because otherwise it should crash immediately when the irradiance url is delete. Also, previously the following message was printed in the console, but now nothing is printed when deleting the irradiance url
```
WARNING: Background: Incomplete irradiance cubemap
```

2021-01-27 16:18 UTC, omichel commented
I cannot reproduce this crash. I tried both on Windows and Linux. Which world did you open to make it crash?

2021-01-27 16:24 UTC, stefaniapedrazzi commented
I tested different worlds and I can reproduce it with all of them.
For example the `battery.wbt` world.

It is an assertion failure so I think it is not reproducible if Webots is compiled in release mode.

2021-01-27 16:25 UTC, omichel commented
Oh, I see, Wren should be compiled in debug mode...

2021-01-27 16:34 UTC, omichel commented
OK, I fixed the crash.

2021-01-27 16:51 UTC, stefaniapedrazzi commented
I confirm the crash is gone and now the message is correctly printed in the console.

Could you just check one last behavior?
If I load a modified `battery.wbt` world where the `frontIrradianceUrl` is empty, and I copy the `bottomIrradianceUrl` to the `frontIrradianceUrl`, the rectangle arena walls become darker. But if I remove again the `frontIrradianceUrl` value they doesn't return hell. It seems like the update is not applied.

2021-01-28 07:46 UTC, omichel commented
> If I load a modified battery.wbt world where the frontIrradianceUrl is empty, and I copy the bottomIrradianceUrl to the frontIrradianceUrl, the rectangle arena walls become darker. But if I remove again the frontIrradianceUrl value they doesn't return hell. It seems like the update is not applied.

Well spotted! I believe I fixed this one as well.

2021-01-28 08:07 UTC, stefaniapedrazzi commented
Thank you!
Now the update is applied correctly and I can clearly see the difference when re-adding an irradiance url (and I get the same after save and revert). Just one last note, the behavior in this PR is now different from before and if the irradiance cubemap is not complete, also the background "baseColor" cubemap is not displayed.

2021-01-28 08:18 UTC, omichel commented
> Just one last note, the behavior in this PR is now different from before and if the irradiance cubemap is not complete, also the background "baseColor" cubemap is not displayed.

Yes, that is true, but I believe it's better that way, as we don't want to encourage incomplete maps. Users should fix all the warnings if they want the background to be displayed.

2021-01-28 09:02 UTC, stefaniapedrazzi approved these changes
If the behavior is wanted then everything is fine for me.

2021-01-28 09:27 UTC, merged

2021-02-01 13:41 UTC, DavidMansolino commented
> > Just one last note, the behavior in this PR is now different from before and if the irradiance cubemap is not complete, also the background "baseColor" cubemap is not displayed.
> 
> Yes, that is true, but I believe it's better that way, as we don't want to encourage incomplete maps. Users should fix all the warnings if they want the background to be displayed.

Note that adding the constraint to always having a complete irradiance map to display the background is probably fine, but adding the opposite constraint (complete background (color) map for the irradiance to work) is IMO a regression as it is often useful to have the reflection of the background without actually seeing it (e.g. when you are inside a building, by the way, several of the world files use this technic currently).

In any case, the ``TexturedBackground`` PROTO currently doesn't respect the new constraint introduced in this PR (https://github.com/cyberbotics/webots/blob/develop/projects/objects/backgrounds/protos/TexturedBackground.proto#L36-L37)

2021-02-02 14:41 UTC, omichel commented
> Note that adding the constraint to always having a complete irradiance map to display the background is probably fine, but adding the opposite constraint (complete background (color) map for the irradiance to work) is IMO a regression as it is often useful to have the reflection of the background without actually seeing it (e.g. when you are inside a building, by the way, several of the world files use this technic currently).
>
> In any case, the TexturedBackground PROTO currently doesn't respect the new constraint introduced in this PR (https://github.com/cyberbotics/webots/blob/develop/projects/objects/backgrounds/protos/TexturedBackground.proto#L36-L37)

You are right, it seems the [hall.wbt](https://github.com/cyberbotics/webots/blob/develop/projects/samples/environments/factory/worlds/hall.wbt) world is broken again for this reason. I could fix it previously as it was reported broken by @lukicdarkoo, but it seems I broke my own fix afterward 😒... I will further investigate and fix this.

2021-02-02 14:55 UTC, omichel commented
That should be fixed in #2695: the color map should be either complete or empty (e.g., 6 or 0 textures loaded) so that the irradiance map is loaded.