Update italian translation
cyberbotics/webots pull request #2592
Opened 2020-12-22 00:46 UTC by ad-daniel

**Description**
Continuation of the italian translation of Webots.

2020-12-23 09:29 UTC, stefaniapedrazzi requested changes
Thank you very much for your contribution!
It is never easy to translate.
I reported some minor comments and some word changes to try to use italian words instead of slang or "italianized" versions of english words.

The major issue to me seems to be the use of the `&amp;` sign (resulting in the underlined letter in the Webots menu /menu items). This is used as shortcut to open the menu from the keyboard by pressing ``<ALT+<letter>``. So even in the translation we should pay attention that the same letter is not used twice otherwise the the second one is useless and it is even better to not set it.
Could you please review all the menus in the italian version and check that these shortcuts are correctly set?

2020-12-23 09:29 UTC, stefaniapedrazzi commented on resources/translations/wb_it.ts
> +        <translation>Impossibile creare link simbolico della libreria dinamica: &apos;%1&apos;.</translation>
```suggestion
        <translation>Impossibile creare un link simbolico della libreria dinamica: &apos;%1&apos;.</translation>
```

2020-12-23 09:29 UTC, stefaniapedrazzi commented on resources/translations/wb_it.ts
> +        <translation>animazione HTML5 esportata con successo in &apos;%1&apos;
```suggestion
        <translation>Animazione HTML5 esportata con successo in &apos;%1&apos;
```

2020-12-23 09:29 UTC, stefaniapedrazzi commented on resources/translations/wb_it.ts
> +        <translation>esportazione HTML5 fallita</translation>
```suggestion
        <translation>Esportazione HTML5 fallita</translation>
```

2020-12-23 09:29 UTC, stefaniapedrazzi commented on resources/translations/wb_it.ts
> +        <translation>Errore nel interrompere la registrazione dell&apos;animazione HTML5: &apos;%1&apos;</translation>
```suggestion
        <translation>Errore nell&apos;interrompere la registrazione dell&apos;animazione HTML5: &apos;%1&apos;</translation>
```

2020-12-23 09:29 UTC, stefaniapedrazzi commented on resources/translations/wb_it.ts
> +        <translation>nodi PROTO (Progetti Aggiuntivi)</translation>
```suggestion
        <translation>Nodi PROTO (Progetti Aggiuntivi)</translation>
```

2020-12-23 09:29 UTC, stefaniapedrazzi commented on resources/translations/wb_it.ts
> +        <translation>nodi PROTO (Progetto Corrente)</translation>
```suggestion
        <translation>Nodi PROTO (Progetto Corrente)</translation>
```

2020-12-23 09:29 UTC, stefaniapedrazzi commented on resources/translations/wb_it.ts
> +        <translation>Questa cartella elenca tutti i nodi PROTO idonei della directory locale &apos;protos&apos;: &apos;%1&apos;.</translation>
```suggestion
        <translation>Questa sezione elenca tutti i nodi PROTO idonei della cartella locale &apos;protos&apos;: &apos;%1&apos;.</translation>
```

2020-12-23 09:29 UTC, stefaniapedrazzi commented on resources/translations/wb_it.ts
> +        <translation>Questa cartella elenca tutti i nodi PROTO idonei forniti da Webots.</translation>
```suggestion
        <translation>Questa sezione elenca tutti i nodi PROTO idonei forniti da Webots.</translation>
```

2020-12-23 09:29 UTC, stefaniapedrazzi commented on resources/translations/wb_it.ts
> -        <source>Insert the identity matrix
The source text should not be modified

2020-12-23 09:29 UTC, stefaniapedrazzi commented on resources/translations/wb_it.ts
> +        <translation>Restora &amp;Punto di Vista</translation>
```suggestion
        <translation>Ripristina &amp;Punto di Vista</translation>
```

2020-12-23 09:29 UTC, stefaniapedrazzi commented on resources/translations/wb_it.ts
> +Restora lo stato iniziale della simulazione. (%1+Shift+F)</translation>
```suggestion
Ripristina lo stato iniziale della simulazione. (%1+Shift+F)</translation>
```

2020-12-23 09:29 UTC, stefaniapedrazzi commented on resources/translations/wb_it.ts
> +        <translation>Resetta Simulazione</translation>
I would rather use "azzera" than "resetta" (that is more a slang)
```suggestion
        <translation>Azzera Simulazione</translation>
```

2020-12-23 09:29 UTC, stefaniapedrazzi commented on resources/translations/wb_it.ts
> +        <translation>Nascondi il Rendering per ottenere migliori performance. (%1+4)</translation>
```suggestion
        <translation>Nascondi il Rendering per ottenere migliori prestazioni. (%1+4)</translation>
```

2020-12-23 09:29 UTC, stefaniapedrazzi commented on resources/translations/wb_it.ts
> +        <translation>Pausa la simulazione. (%1+0)</translation>
```suggestion
        <translation>Metti in pausa la simulazione. (%1+0)</translation>
```

2020-12-23 09:29 UTC, stefaniapedrazzi commented on resources/translations/wb_it.ts
> +        <translation>Pulisce la Console.</translation>
```suggestion
        <translation>Pulisci la Console.</translation>
```

2020-12-23 09:29 UTC, stefaniapedrazzi commented on resources/translations/wb_it.ts
> +        <translation>Valore invalido di &apos;fieldOfView&apos; cambiato a 0.7854. Il campo visivo è limitato a pi se il campo &apos;spherical&apos;è FALSO.</translation>
```suggestion
        <translation>Valore invalido di &apos;fieldOfView&apos; cambiato a 0.7854. Il campo visivo è limitato a pi se il campo &apos;spherical&apos; è FALSO.</translation>
```

2020-12-23 09:29 UTC, stefaniapedrazzi commented on resources/translations/wb_it.ts
> +        <translation>&apos;%1&apos; previsto essere un file ma è una directory.</translation>
```suggestion
        <translation>&apos;%1&apos; previsto essere un file ma è una cartella.</translation>
```

2020-12-23 09:29 UTC, stefaniapedrazzi commented on resources/translations/wb_it.ts
> +        <translation>Previsto un tipo VRML97 ma trovato &apos;%2&apos;</translation>
```suggestion
        <translation>Previsto formato VRML97 ma trovato &apos;%2&apos;</translation>
```

2020-12-23 09:29 UTC, stefaniapedrazzi commented on resources/translations/wb_it.ts
> +        <translation>Il primo elemento del campo &apos;%1&apos; è supposto essere un file ma è invece una directory.</translation>
```suggestion
        <translation>Il primo elemento del campo &apos;%1&apos; deve essere un file ma è invece una cartella.</translation>
```

2020-12-23 09:29 UTC, stefaniapedrazzi commented on resources/translations/wb_it.ts
> +        <translation>Impossibile creare una directory nella directory temporanea di Webots &quot;%1&quot;</translation>
```suggestion
        <translation>Impossibile creare una cartella nella cartella temporanea di Webots &quot;%1&quot;</translation>
```

2020-12-23 09:29 UTC, stefaniapedrazzi commented on resources/translations/wb_it.ts
> +        <translation>Impossibile creare la directory temporanea Webots &quot;%1&quot;</translation>
```suggestion
        <translation>Impossibile creare la cartella temporanea Webots &quot;%1&quot;</translation>
```

2020-12-23 09:29 UTC, stefaniapedrazzi commented on resources/translations/wb_it.ts
> +        <translation>il nodo %1 non può essere inserito al livello superiore della gerarchia dei nodi.</translation>
```suggestion
        <translation>Il nodo %1 non può essere inserito al livello superiore della gerarchia dei nodi.</translation>
```

2020-12-23 09:29 UTC, stefaniapedrazzi commented on resources/translations/wb_it.ts
> +        <translation>Token &quot;%1&quot; invalido</translation>
```suggestion
        <translation>Simbolo &quot;%1&quot; invalido</translation>
```

2020-12-23 09:29 UTC, stefaniapedrazzi commented on resources/translations/wb_it.ts
> +        <translation>Il file &apos;%1&apos; è stato creato da Webots %2 e stai usando Webots %3. Compatibilità con versioni successive potrebbe non funzionare.</translation>
```suggestion
        <translation>Il file &apos;%1&apos; è stato creato da Webots %2 e stai usando Webots %3. La compatibilità con versioni successive potrebbe non funzionare.</translation>
```

2020-12-23 09:29 UTC, stefaniapedrazzi commented on resources/translations/wb_it.ts
> +        <translation>errore &apos;%1&apos;: Intestazione mancante.</translation>
```suggestion
        <translation>&apos;%1&apos;: errore : Intestazione mancante.</translation>
```

2020-12-23 09:29 UTC, stefaniapedrazzi commented on resources/translations/wb_it.ts
> +        <translation>la parola chiave &apos;IS&apos; è permessa solo in files .proto</translation>
```suggestion
        <translation>la parola chiave &apos;IS&apos; è permessa solo in file .proto</translation>
```

2020-12-23 09:29 UTC, stefaniapedrazzi commented on resources/translations/wb_it.ts
> +        <translation>Fine del file raggiunta sebbene un token sia previsto</translation>
```suggestion
        <translation>Fine del file raggiunta sebbene un simbolo sia previsto</translation>
```

2020-12-23 09:29 UTC, stefaniapedrazzi commented on resources/translations/wb_it.ts
> +        <translation>resetta</translation>
```suggestion
        <translation>ripristina</translation>
```

2020-12-23 09:29 UTC, stefaniapedrazzi commented on resources/translations/wb_it.ts
> +        <translation>Resetta Simulazione.
```suggestion
        <translation>Azzera Simulazione.
```

2020-12-23 09:29 UTC, stefaniapedrazzi commented on resources/translations/wb_it.ts
> +        <translation>Resetta</translation>
```suggestion
        <translation>Azzera</translation>
```

2020-12-27 01:39 UTC, ad-daniel commented
Thank you for the feedback, I've incorporated the suggested changes.
With regards to the accelerators, that makes a lot more sense, I misunderstood their function entirely. I've fixed it so there's no doubles.

PS: the source language might require some work in that direction as well, for instance in the File menu there's 4 "O".

2021-01-04 07:53 UTC, stefaniapedrazzi requested changes
Thank you!
There are still a couple of duplicated accelerators in "File" and "Modifica" menus, but it is fine like this.

I just have one last changes and then it's all fine for me.

2021-01-04 07:53 UTC, stefaniapedrazzi commented on resources/translations/wb_it.ts
> +        <translation>edita</translation>
```suggestion
        <translation>modifica</translation>
```

2021-01-04 10:57 UTC, ad-daniel commented
Thank you, for some reason I didn't consider the grayed out ones, should be all unique now (at least the italian ones). I also made the suggested change and marked it here as resolved but somehow it still requires it.
As for the failed test, it's the same issue that was in the master branch yesterday related to copyright dates

2021-01-04 11:09 UTC, stefaniapedrazzi approved these changes
Thank you!

Is your branch up-to-date with the `webots:master` branch?

2021-01-04 16:19 UTC, merged