use closest contact for ray collision
cyberbotics/webots pull request #2610
Opened 2020-12-29 17:26 UTC by ad-daniel

**Related Issues**
This pull-request addresses issue #2605

**Description**
The root of the problem appears to be that IndexedFaceSets are different to classic Solids with regards to ray collision. With solids like boxes and spheres there appears to be always only one point of contact (n = 1 [here](https://github.com/cyberbotics/webots/blob/3766a52ca250cc6ba41a777182a4aeb61d2d3642/src/webots/engine/WbSimulationCluster.cpp#L582-L585)) which might explain why the collision callback:

> ds->rayCollisionCallback(odeGeomData2->geometry(), o1, &contact[0].geom);

is always called with `contact[0]`. With IndexedFaceSets however there can be more, I'm not sure if more than 2 but at least 2 for a box-like shape built using IndexedFaceSets, as shown in this video. 

https://user-images.githubusercontent.com/44834743/103298156-089b9e00-49fa-11eb-8510-e8fd0fe9934a.mp4

As can be seen the problem then arises from the fact that it isn't guaranteed that contact[0] is the closest, in fact it appears to never be. Since `dCollide()` returned the contact point on the opposite face as first element, the angle computed [here](https://github.com/cyberbotics/webots/blob/3766a52ca250cc6ba41a777182a4aeb61d2d3642/src/webots/nodes/WbDistanceSensor.cpp#L545-L548) when the contact is handled evaluates in this case to 180° ( `angle = direction.angle(-normal)` ) and the ray is therefore ignored because outside the 45° cone which explains why it always returns max value as mentioned in issue #2605.

The suggested fix then is to use the closest contact among the `n` returned by `dCollide()`;

Here's the same video after the fix:

https://user-images.githubusercontent.com/44834743/103298149-05081700-49fa-11eb-8bbf-4225e258a602.mp4

**Test world used**
[distance_sensor_bug.zip](https://github.com/cyberbotics/webots/files/5751497/distance_sensor_bug.zip)

**Related (possible) pitfalls**
It doesn't appear to be at the origin of the problem here, but the `TexturedBox.proto` (technically `TexturedParallelepiped.proto`) primitive uses a IndexedFaceSet to define the parallelepiped, and the faces are defined as squares (4 vertices) whereas according to the IndexedFaceSet documentation 

> When used for collision detection (boundingObject), each face of the IndexedFaceSet must contain exactly three vertices, hence defining a triangle mesh (or trimesh).

Considering more often than not TexturedBoxes will use their own shape as boundingObject, it might be better to re-define them as such. It doesn't appear to create any issue as is, despite being defined as 4-vertices faces there appears to be a mechanism somewhere that splits them into triangles the correct way (or just out of luck) so the issue mentioned here might return if the automatic splitting is altered at some point and the normals of some of the triangles aren't in the correct direction (rays being ignored again because the angle is outside the 45° cone). Unless of course the splitting isn't random at all, in which case it will be fine.

2020-12-29 21:11 UTC, omichel requested changes
Thank you for this great bug fix!
May I ask you to also add a line in the change log mentioning this fix?

2020-12-29 21:20 UTC, omichel commented
Regarding the triangulation of the bounding objects, I am not sure that the documentation is correct. I believe at some point, we may have introduced the tesselation of all meshes, including the `IndexedFaceSet` of bounding objects. We should double-check the code about it and either fix the documentation or the `TexturedParallelepiped` proto. This should be addressed in a different PR.

2020-12-29 22:49 UTC, ad-daniel commented
I've added the line to the changelog.
Regarding the triangulation, I've opened a different issue: #2611

2020-12-30 06:22 UTC, omichel approved these changes
Thank you!

2020-12-30 11:54 UTC, merged