Expose new API for accessing RangeFinder's raw float buffer in Python
cyberbotics/webots pull request #2664
Opened 2021-01-19 06:58 UTC by WasabiFan

**Description**

This PR introduces a new `data_type` keyword parameter on the `getRangeImage` method. The default value, `list`, preserves its existing behavior. The new alternative, `buffer`, returns a `bytes` object with a copy of the machine-dependent `float` buffer.

The behavior of `getRangeImageArray` is unchanged. I opted to add the new functionality to `getRangeImage` rather than `getRangeImageArray` because a byte buffer more closely resembles a 1D list than 2D. 🤷 

**Related Issues**

Fixes issue #2661. There's a full description in that issue.

API is modelled after #2321.

**Tasks**

I don't know what tasks I'm supposed to put here, but... I added the option and updated the documentation.

I have _not_ introduced a changelog entry.

**Documentation**

This MR is sourced from my fork for politeness; I believe I could push the branch to the upstream repo and change the source if that's what is preferred.

**Additional context**

<details>
<summary>Not-very-scientific test controller</summary>

```python
from controller import Robot

import time
import numpy as np
import cv2

robot = Robot()

timestep = int(robot.getBasicTimeStep())

rf = robot.getDevice("range-finder")
rf.enable(int(robot.getBasicTimeStep()))

i = 0
while robot.step(timestep) != -1:
    if i % 2 == 0:
        start = time.time()
        image = rf.getRangeImage(data_type="list")
        image_np = np.array(image).reshape(rf.getHeight(), rf.getWidth())
        end = time.time()
        #cv2.imwrite("list.png", np.array(image_np * 100, dtype=np.uint8))
        print(f"List time: {(end-start)*1000:.2f} ms")
    else:
        start = time.time()
        image = rf.getRangeImage(data_type="buffer")
        image_np = np.frombuffer(image, dtype=np.float32).reshape(rf.getHeight(), rf.getWidth())
        end = time.time()
        #cv2.imwrite("buffer.png", np.array(image_np * 100, dtype=np.uint8))
        print(f"Buffer time: {(end-start)*1000:.2f} ms")
    i += 1

```
</details>

On my machine, with a 640x480 image (formatted as `median` / `mean`):

-|list|buffer
---|---|---
function call only | 8ms / 8.7ms | 5ms / 5.5ms
function call plus numpy array | 22ms / 24.5ms | 7ms / 7.6ms

I'm not 100% satisfied with this performance (7ms is still rather high for what should, ideally, do effectively zero work) but I figure it's worth opening the PR for discussion.

2021-01-19 08:24 UTC, lukicdarkoo commented
Thank you for the nice PR!

I have just briefly tested the performance of a C controller, and the C controller is indeed faster (around 1.5ms, so around 3.5ms difference). The only bottleneck I see is `PyBytes_FromStringAndSize`, but I assume it shouldn't be that slow. Do you have any idea?

If there is no obvious way to solve it we can merge it and investigate further in another PR.

2021-01-19 08:29 UTC, lukicdarkoo commented
Here is the reason:
> Return a new bytes object with a copy of the string v as value and length len on success, and NULL on failure. If v is NULL, the contents of the bytes object are uninitialized.

https://docs.python.org/3/c-api/bytes.html#c.PyBytes_FromStringAndSize

The only way to avoid it and I am aware of is Python Buffer Protocol. However, maybe there is something in SWIG to should simplify the implementation.

2021-01-19 16:33 UTC, WasabiFan commented
@lukicdarkoo take a look at my findings posted in #2661 — there's some performance info there regarding the function you mentioned.

2021-01-19 16:55 UTC, lukicdarkoo commented
@WasabiFan Sorry, I missed it :disappointed: 

> I implemented both the bytes and bytearray variants and, evidently

Do you have the `bytearray` implementation somewhere so I can check it?

If we make the `bytearray` version work faster than `bytes` then we can keep both of them. Even though Python doesn't own data in `bytearray` there could be use-cases in which `bytearray` is preferable.

2021-01-19 17:34 UTC, WasabiFan commented
I didn't keep a copy, but the version I tested was a direct copy of the `__getRangeImageBuffer` function which is in my change set here, but with `PyByteArray_FromStringAndSize` instead of `PyBytes_FromStringAndSize`. I'd certainly appreciate any thoughts on what I may have missed.

2021-01-19 18:58 UTC, lukicdarkoo commented
It seems that `PyByteArray_FromStringAndSize` doesn't share a buffer:
https://github.com/python/cpython/blob/e8e66eab941b983b6e85cd0d57cd45838880c568/Objects/bytearrayobject.c#L131-L139

I wanted to add a custom buffer type that exposes `setpointer` method:
https://gist.github.com/lukicdarkoo/40684dbffe234796376dc001d2fc4cfb
but I gave up in the end because it looked overengineered.

A possibly better solution would be to export `numpy` objects directly:
https://numpy.org/devdocs/reference/swig.interface-file.html

2021-01-19 22:32 UTC, WasabiFan commented
> It seems that PyByteArray_FromStringAndSize doesn't share a buffer:

Interesting, and surprising!

> I wanted to add a custom buffer type that exposes setpointer method:

That seems like a very sensible solution... I agree with your assessment though. Integrating something like that into the controller library would just add more surface area for strange maintenance edge-cases. I would be a bit surprised if there aren't existing libraries which expose a wrapper like this, but I'm not seeing anything from a cursory search.

> A possibly better solution would be to export numpy objects directly:

Agreed in principle. Is this something that the project as a whole is open to? In particular:
- NumPy would now be a build-time dependency
- Either only this one function would be able to return a NumPy array, or it would ideally be retrofit into e.g. `Lidar` and `Camera`

2021-01-20 08:47 UTC, lukicdarkoo commented
> Integrating something like that into the controller library would just add more surface area for strange maintenance edge-cases. I would be a bit surprised if there aren't existing libraries which expose a wrapper like this, but I'm not seeing anything from a cursory search.

Exactly!

> Agreed in principle. Is this something that the project as a whole is open to? In particular:
> 
> * NumPy would now be a build-time dependency
> * Either only this one function would be able to return a NumPy array, or it would ideally be retrofit into e.g. `Lidar` and `Camera`

If I am not mistaken, it would be just a matter of including `numpy.i`. `numpy.i` is built on top of Python Buffer Protocol, so it should not be a big issue.

The idea behind `getRangeImage(data_type='list')` is that we can easily add an arbitrary number of data types without breaking backward compatibility. Therefore, for getting numpy buffer we could use `getRangeImage(data_type='numpy')`.

@omichel We can merge this one, and open another PR for potential numpy integration?

2021-01-20 08:58 UTC, omichel commented
> @omichel We can merge this one, and open another PR for potential numpy integration?

Sure. Thank you for the investigation and great contribution in the works!

2021-01-20 09:00 UTC, omichel requested changes

2021-01-20 09:00 UTC, omichel commented on src/controller/python/controller.i
> +    int len = width * height;
```suggestion
    const int width = $self->getWidth();
    const int height = $self->getHeight();
    const int len = width * height;
```

2021-01-20 09:16 UTC, WasabiFan commented
Thanks for the review and comments; I'll take a look tomorrow!

> If I am not mistaken, it would be just a matter of including numpy.i. numpy.i is built on top of Python Buffer Protocol, so it should not be a big issue.

I am just on my phone at the moment so can't grab the full details, but earlier I looked at the definition of that SWIG file and as far as I could tell it expanded to use functions from [here](https://numpy.org/devdocs/reference/c-api/array.html). I'm not familiar with SWIG but as I understand it it's purely a preprocessor step, so if it uses those functions I think we'll need to be able to link against numpy.

2021-01-21 08:03 UTC, omichel approved these changes
Thank you.

2021-01-22 07:33 UTC, lukicdarkoo commented
@WasabiFan Feel free to click the merge the `Squash and merge` button :)

2021-01-22 21:31 UTC, merged