Proto2mesh multithreaded
cyberbotics/webots pull request #2698
Opened 2021-02-02 18:03 UTC by Simon-Steinmann

Adding more parsable arguments and multithreading

2021-02-02 20:50 UTC, omichel commented
The CI tests are failing (line too long, see log).

2021-02-05 12:57 UTC, omichel commented
Is the PR ready for review now or do you want to commit your fast mesh optimization code in there?

2021-02-06 18:10 UTC, Simon-Steinmann commented
The PR should be pretty much ready now. So far my tests are all successful, However, I only inspected the generated .obj files, not the whole protos loaded into Webots. We should probably think of a way to verify and benchmark a conversion. Compare load times and see if the robot looks and functions the same.

2021-02-08 14:45 UTC, omichel requested changes
Thank you for this very good PR!
I only have a few minor suggestions.
Also, I believe we should probably remove the `--input=` option and replace it with a mandatory argument that comes without this `--input=` prefix, like:
```bash
python proto2mesh.py ../../projects/robots --verbose
```

2021-02-08 14:45 UTC, omichel commented on scripts/proto_splitter/proto2mesh.py
> +                #          str(p0) + str(p1) + str(p2) + '\n' + str(n))
Clean-up:
```suggestion
```

2021-02-08 14:45 UTC, omichel commented on scripts/proto_splitter/proto2mesh.py
> +                raise Exception("ERROR: LUA skript for mesh data is not supported.")
German word 😆:
```suggestion
                raise Exception("ERROR: LUA script for mesh data is not supported.")
```

2021-02-08 14:45 UTC, omichel commented on scripts/proto_splitter/proto2mesh.py
> +        # print(defName, len(data))
cleanup:
```suggestion
```

2021-02-08 14:45 UTC, omichel commented on scripts/proto_splitter/proto2mesh.py
> +        help='If set, detailed output of mesh conversion is shown in console',
consistency with other help lines:
```suggestion
        help='If set, detailed output of mesh conversion is shown in console.',
```

2021-02-08 14:45 UTC, omichel commented on scripts/proto_splitter/proto2mesh.py
> +    cpv = options.cpv
We should try to avoid this kind of abbreviation in variable and function names, prefer `checkProtoValidity` instead.

2021-02-08 14:45 UTC, omichel commented on scripts/proto_splitter/proto2mesh.py
> +    if cpv:  # if we check protos files for validity
... This will save us from this kind of comment.

2021-02-08 14:45 UTC, omichel commented on scripts/proto_splitter/proto2mesh.py
> +    mt = options.mt
I would rename `mt` to `multithreading` (see explanation below).

2021-02-09 08:13 UTC, omichel approved these changes
Thank you.
It looks all very good to me now.

2021-02-09 15:14 UTC, omichel approved these changes
Thank you.

2021-02-09 15:31 UTC, merged