Delete differential drive
cyberbotics/webots pull request #2749
Opened 2021-02-12 15:20 UTC by lukicdarkoo

Delete deprecated differential drive module. I am changing some variables related to the module in #2740, so I guess it is better to delete it now than later.

2021-02-15 08:01 UTC, stefaniapedrazzi commented on lib/controller/matlab/WB_NODE_DIFFERENTIAL_WHEELS.m
> -value = 32;
Note that after deleting the `WB_NODE_DIFFERENTIAL_WHEELS` node, all the subsequent node values changes and the whole Matlab API should be updated and not just this file.
So you should regenerate the Matlab API files and commit all the changed ones.

2021-02-15 10:36 UTC, stefaniapedrazzi requested changes
Everything seems fine.
Here are just a couple of files that still needs to be updated:
* `robot.md` documentation of `wb_robot_get_type`:
    https://github.com/cyberbotics/webots/blob/72fc39fe3b97ebc91799df83c1138c785e1d98b3/docs/reference/robot.md#wb_robot_get_type
* `supervisor.md` function `wb_supervisor_node_get_type`: in the note for C++, Java and Python we should use a different node than `Node::DIFFERENTIAL_WHEELS` for the example
    https://github.com/cyberbotics/webots/pull/2749/files#diff-bc04135433036246a5befef3ec0c4113f48bb6f62f0042ae6912e3d43751d63bR566
- in `projects/samples/curriculum/controllers/intermediate_lfm/intermediate_lfm.c` and `projects/samples/curriculum/controllers/novice_ir_sensors/novice_ir_sensors.c` some comments still refer to the `wb_differential_wheels_*` functions
- in the generic window CSS: `generic.css` there are some rules for class "differential-wheels-button" that are no longer used
- in `WbSolid::updateJointChildren` there is a comment referring specifically to differential wheels. It would be good to know if this also applied to other cases or not:
    https://github.com/cyberbotics/webots/blob/cleanup-differential-drive/src/webots/nodes/WbSolid.cpp#L1218-L1222
- `resources/webots_ros/src/robot_information_parser.cpp`:
   https://github.com/cyberbotics/webots_ros/blob/master/src/robot_information_parser.cpp#L96

2021-02-15 13:37 UTC, lukicdarkoo commented
> in projects/samples/curriculum/controllers/intermediate_lfm/intermediate_lfm.c and projects/samples/curriculum/controllers/novice_ir_sensors/novice_ir_sensors.c some comments still refer to the wb_differential_wheels_* functions

It looks those comments have been outdated for a while :)

2021-02-15 16:21 UTC, lukicdarkoo commented
I reverted kinematics mode (I wasn't aware it exists)

2021-02-16 11:02 UTC, omichel requested changes
I tested the two examples with kinematic differential drives (e-puck and khepera) and they both work nicely.

2021-02-16 13:46 UTC, omichel submitted a review, later dismissed
Thank you. It's all good for me.
Please wait for the review of @stefaniapedrazzi before merging.

2021-02-17 07:13 UTC, stefaniapedrazzi submitted a review, later dismissed
Thank you.

I will approve this PR again just after the conflicts with the `webots_ros` submodule are fixed.

2021-02-17 08:17 UTC, lukicdarkoo commented
@stefaniapedrazzi No conflicts, the tests should pass

2021-02-17 08:21 UTC, omichel approved these changes

2021-02-17 08:23 UTC, stefaniapedrazzi approved these changes

2021-02-17 08:29 UTC, merged

2021-04-05 11:53 UTC, eze1376 commented
Hi,
When I want to build webots, feature-robocup-controllers branch from source.
I get this error
`make[1]: *** No rule to make target 'nodes/WbDifferentialWheels.hpp', needed by 'WbSolid.o'.  Stop.`
and I think it's because of this PR.
If there is a solution, please let me know!
Thanks,

2021-04-05 14:45 UTC, eze1376 commented
It will be solve by:
`make clean`