Generic gear PROTO
cyberbotics/webots pull request #2805
Opened 2021-03-02 22:24 UTC by ad-daniel

**Description**
Introduces a generic gear generator PROTO. The tooth profile is inspired on glxgears implementation.

I believe it was necessary to add the contactRadius field for the spherical boundingObjects attached to the tip of each tooth as depending on the number of teeth and the size of the gear itself there's no good way of ensuring this sphere is always of a reasonable size (or rather, we don't know what is a reasonable size to begin with)

PS: when I load the docs locally, the new gears sub-category doesn't show up in the left side-menu but it does in the main page index [here](https://cyberbotics.com/doc/guide/objects). It adds it automatically or do I need to add the reference elsewhere?

**Images**
![model](https://user-images.githubusercontent.com/44834743/109722371-e6b2c900-7bac-11eb-9bd5-7a1053d9cca4.png)

2021-03-03 09:35 UTC, stefaniapedrazzi reviewed
Note that the objects documentation is automatically generated by running the `docs/guide/generate_objects_doc.py` script.
We should try to avoid to commit a version that differs from the automatically generated one otherwise we have to manually check the differences every time we regenerate the documentation.

By the way, I noticed some other issues (not related to this PR) in the `generate_objects_doc.py` that produces differences w.r.t the committed files (URLs and derived node) and I will just open an issue about this.
*edit: it has already been fixed on the master branch but not ported to the develop branch. I'm taking care of it.*

2021-03-03 09:43 UTC, omichel commented
I would also add a simple example in `projects/samples/howto/gears/` showing at least one motor running one gear that will drive another passive gear (I guess you almost have it already).

2021-03-03 11:42 UTC, ad-daniel commented
@stefaniapedrazzi I see, I'll keep it in mind. Do I need to do anything about it this time?

2021-03-03 11:45 UTC, stefaniapedrazzi commented
> @stefaniapedrazzi I see, I'll keep it in mind. Do I need to do anything about it this time?

Yes, you need to generate the documentation with the script and commit the auto-generated documentation file instead of your manually written one.
Note that you should first synch with the latest version of the develop branch.

2021-03-03 13:48 UTC, ad-daniel commented
Should be good for review now, thanks.

2021-03-03 14:31 UTC, stefaniapedrazzi requested changes

2021-03-03 14:31 UTC, stefaniapedrazzi commented on docs/guide/samples-howto.md
> +[WorldInfo](../reference/worldinfo.md) node.
In the documentation we write each sentence on one line and avoid to manually break sentences.
Could you please fix it?

2021-03-03 14:31 UTC, stefaniapedrazzi commented on projects/samples/howto/gears/worlds/gears.wbt
> +  coordinateSystem "NUE"
Could you please also add the title and info?

2021-03-03 14:31 UTC, stefaniapedrazzi commented on docs/guide/samples-howto.md
> +collide the second wheel begins to turn. Using this sort of approach as general purpose transmission is not generally advised but
```suggestion
collides the second wheel begins to turn. Using this sort of approach as general purpose transmission is not generally advised but
```

2021-03-03 14:31 UTC, stefaniapedrazzi commented on docs/guide/samples-howto.md
> +does work with some tuning of the `dampingConstant` of the [HingeJoint](../reference/hingejoint.md), the ERP and CFM values in the
```suggestion
does work with some tuning of the `dampingConstant` of the [HingeJoint](../reference/hingejoint.md), and the `ERP` and `CFM` values in the
```

2021-03-03 14:31 UTC, stefaniapedrazzi commented on projects/objects/gear/protos/Gear.proto
> +    local Z = fields.teeth.value
Wouldn't be better to rename this variable to something more descriptive?

2021-03-03 14:31 UTC, stefaniapedrazzi commented on projects/objects/gear/protos/Gear.proto
> +      io.stderr:write("'width' value must bigger than zero. Using default value.\n")
```suggestion
      io.stderr:write("'width' value must be greater than 0. Using default value.\n")
```

2021-03-03 14:31 UTC, stefaniapedrazzi commented on projects/objects/gear/protos/Gear.proto
> +      io.stderr:write("'density' value must bigger or equal to zero. Using default value.\n")
```suggestion
      io.stderr:write("'density' value must be greater or equal to 0. Using default value.\n")
```

2021-03-03 14:31 UTC, stefaniapedrazzi commented on projects/objects/gear/protos/Gear.proto
> +      io.stderr:write("'teeth' value must bigger than 8. Using default value.\n")
```suggestion
      io.stderr:write("'teeth' value must be greater than 8. Using default value.\n")
```

2021-03-03 14:31 UTC, stefaniapedrazzi commented on projects/samples/howto/gears/controllers/gears/Makefile
> +###-----------------------------------------------------------------------------
For sample controllers we use a shorter Makefile header, you can copy the one from any other howto controller.

2021-03-03 14:32 UTC, stefaniapedrazzi commented
The Gear PROTO works fine!
There are just some minor issues to fix.

2021-03-04 08:07 UTC, omichel requested changes
This [projects/samples/howto/gears/controllers/gears/gears](binary file) should not be committed, but ignored in a local `.gitignore` file.

2021-03-04 08:54 UTC, ad-daniel commented
Done

2021-03-04 08:58 UTC, omichel approved these changes
Thank you.

2021-03-04 09:57 UTC, stefaniapedrazzi approved these changes
Thank you

2021-03-04 09:58 UTC, merged

2021-03-04 09:59 UTC, stefaniapedrazzi commented
Sorry, I just realized that we should also add an entry in the ChangeLog about this new PROTO.
But this can be done in a separate PR.