Integrate the `ros_control` package to the `ros` controller
cyberbotics/webots pull request #2822
Opened 2021-03-05 16:47 UTC by lukicdarkoo

This PR integrates the `ros_control` package to the `ros` controller.

**Tasks**
- [x] Proof of concept
- [ ] Test with differential drive
- [ ] Test with MoveIt
- [ ] Document
- [ ] Changelog

2021-03-08 23:46 UTC, Simon-Steinmann commented
Does the robot description contain the visual data? This was an issue with ROS2 as well like 2 month ago. The new way of storing protos, with the meshes as .obj files, should make this fairly simple.

2021-03-09 07:37 UTC, lukicdarkoo commented
> Does the robot description contain the visual data? This was an issue with ROS2 as well like 2 month ago. The new way of storing protos, with the meshes as .obj files, should make this fairly simple.

No :/ It is output from the `wb_robot_get_urdf` function. We need to improve the `wb_robot_get_urdf` function to get the visual data as well. Do you have a use case for this? We deliberately omitted this feature.

2021-03-09 09:03 UTC, omichel requested changes
It looks very good.
I just have a few suggestions.

2021-03-09 09:03 UTC, omichel commented on projects/default/controllers/ros/highlevel/WebotsHw.cpp
> +  WebotsHw::WebotsHw(webots::Robot *robot) : mRobot(robot) {
I would rename this class `WebotsHW` (with a uppercase W) to match ROS control's `hardware_interface::RobotHW`

2021-03-09 09:29 UTC, omichel commented on projects/default/controllers/ros/highlevel/WebotsHw.cpp
> +  WebotsHw::WebotsHw(webots::Robot *robot) : mRobot(robot) {
Webots convention would have led to `WebotsHardware` instead (see https://github.com/cyberbotics/webots/wiki/Coding-Style#cs44-no-abbreviations), but in that case, I believe we should adopt the convention used in the upper class, e..g., `RobotHW`.

2021-03-09 09:56 UTC, omichel approved these changes
Thank you.

2021-03-09 10:14 UTC, merged