Use WebGL to draw plots in the generic robot window
cyberbotics/webots pull request #2854
Opened 2021-03-15 09:35 UTC by stefaniapedrazzi

Use WebGL to draw the plot instead of drawing directly in the canvas.

Steps:
* [x] add instructions to draw the graph using WebGL  
* [x] create one GL context per canvas
* [ ] reduce the number of GL context

2021-03-17 16:04 UTC, stefaniapedrazzi commented
I tested on Linux and I'm now updating my development environment to also test on Windows but it will take some time.

2021-03-17 16:16 UTC, omichel reviewed
I could test it on Windows and it seems to work.
However, the rescaling of the position sensor graphs is still confusing: previous values disappear suddenly, it looks buggy... I will make a movie to show you this.

2021-03-17 16:16 UTC, omichel commented on resources/projects/plugins/robot_windows/generic/canvas.js
> +    for (var i = 0; i < webglNames.length; ++i) {
Shouldn't we use `let` instead of `var` everywhere?

2021-03-17 16:30 UTC, omichel commented
If you look at the second graph, instead of being rescaled, the graph appears like if it was erased. This happens twice and is confusing. I believe that with WebGL, we could have a much smoother rescaling.

https://user-images.githubusercontent.com/1264964/111502491-2a2d3b80-8746-11eb-9581-8f2da24caebe.mp4

2021-03-17 16:48 UTC, stefaniapedrazzi commented
Thank you for the tests.

This is the JUMP rule defined in the generic robot window. The PositionSensor and motors are the only device using this range update method and I think it is the correct way to update the range given that they can continuously growing and it would not make sense to stretch the range.
I will try to improve the used formula so that a bigger portion of the graph is visible and increase the range size.
But we should not stretch the range and extend it because it will produce unusable graphs (same as the encoders for the vehicle robot window).

By the way it seems that there are some issues drawing the white background of the graph on Windows.
Here is what I get on Linux
![webgl_plot](https://user-images.githubusercontent.com/5910449/111505497-f9023a80-8748-11eb-9154-13309a2e2bd9.png)

2021-03-17 16:58 UTC, omichel commented
> This is the JUMP rule defined in the generic robot window. The PositionSensor and motors are the only device using this range update method and I think it is the correct way to update the range given that they can continuously growing and it would not make sense to stretch the range.
I will try to improve the used formula so that a bigger portion of the graph is visible and increase the range size.
But we should not stretch the range and extend it because it will produce unusable graphs (same as the encoders for the vehicle robot window).

I believe that all the Y values in the displayed range should be visible on the graph when we rescale it, which is not the case currently.

2021-03-17 17:17 UTC, stefaniapedrazzi commented
> I believe that all the Y values in the displayed range should be visible on the graph when we rescale it, which is not the case currently.

Yes, this can be improved so that _most_ of the Y values are visible.
But the range size should be always kept the same it cannot be stretched so that all the Y values are visible and made bigger.
I updated a version that work much better but stretching the range size for position sensors, motors, and ecoders is very bad and should be avoided.

2021-03-22 08:19 UTC, stefaniapedrazzi commented
I added a third range update method that makes sure that all the Y values are visible.
It is currently set as default for motors and position sensors.
The drawback is that it is not as efficient as the others given that every time it needs to loop through the Y values to adjust the range (stretch it when Y is out of range and shrink it when old Y values are discarded).
I expected a much bigger impact on the performance but for simple graphs I could not see any difference in the speedometer.

2021-03-22 10:43 UTC, omichel requested changes
Yes, the ADAPT method looks much better than the previous JUMP method.
Thank you.

2021-03-22 10:43 UTC, omichel commented on resources/projects/plugins/robot_windows/generic/timeplot_widget.js
> +  } else if (y > this.yRange['max'])
```suggestion
  if (Math.abs(max - min) < delta)
    halfOffset = (delta - max + min) * 0.5; // Minimum size of range is defined by the initial values.
  else if (y > this.yRange['max'])
```

2021-03-22 11:52 UTC, omichel approved these changes

2021-03-22 12:03 UTC, merged