Darwin-op expose backlash
cyberbotics/webots pull request #2881
Opened 2021-03-17 23:58 UTC by ad-daniel

**Description**
This PR exposes a `enableBacklash` field and activates backlash on all joints (amount: 0.04) for the `HingeJoint` based Darwin-OP (the default one).

It should be noted that:

-  The `HingeJointWithBacklash` PROTO already has a mechanism that reverts to a simple `HingeJoint` in case backlash is 0. So in theory there should be no performance difference between the original Darwin and the modified version if backlash is enforced to 0 (condition for it to revert). In practice however there appears to be some overhead in the latter case which makes it more computationally complex, which is why in this PR the switch is done directly in the Darwin PROTO despite this mechanism existing in the `HingeJointWithBacklash`.
-  I'm undecided if I should lower the default timestep of the world down to 8, in the offchance users enable backlash to test it

**Performance metrics**
TODO

2021-03-18 07:19 UTC, omichel commented on projects/robots/robotis/darwin-op/protos/Darwin-op.proto
> +  field SFBool     enableBacklash  FALSE                      # Enables backlash on all joints.
I would rename this field to simply "backlash".

2021-03-18 07:22 UTC, omichel commented on projects/robots/robotis/darwin-op/protos/Darwin-op.proto
> +    local backlash_head = 0.04
I believe we should put here the value taken from in the datasheet of the Darwin-OP servo. Is that correct?
Also, for convenience, we could have single backlash value, like:
```lua
local backlash = 0.04
local backlash_head = backlash
local backlash_neck = backlash
...
```
That would make it easier to adjust.

2021-03-18 14:58 UTC, omichel requested changes
Thank you.
We should also update the user guide (ROBOTIS OP2 page).

2021-03-18 23:05 UTC, ad-daniel commented
I've added the documentation regarding the new field and since in the other PR it was mentioned that the default rotation should be `0 0 1 0` I changed this one as well.

2021-03-19 08:42 UTC, omichel requested changes

2021-03-19 08:42 UTC, omichel commented on docs/guide/robotis-op2.md
> +*Backlash*
```suggestion
#### Backlash
```

2021-03-19 08:42 UTC, omichel commented on docs/guide/robotis-op2.md
> +*Self Collision*
```suggestion
#### Self Collision
```

2021-03-19 08:42 UTC, omichel commented on docs/guide/robotis-op2.md
> +Additionally, for the correct enforcing of this effect, the value of the `basicTimestep` in [WorldInfo](../reference/worldinfo.md) should be set to 8 or lower.
```suggestion
Additionally, for the correct enforcing of this effect, the value of the `basicTimestep` in [WorldInfo](../reference/worldinfo.md) should probably be set to a smaller value when enabling the backlash.
```

2021-03-19 08:42 UTC, omichel commented on docs/guide/robotis-op2.md
> +For these reasons, activating this option is very computationally expensive and will significantly slow down the simulation speed.
```suggestion
For these reasons, activating this option is computationally expensive and will significantly slow down the simulation speed.
```

2021-03-19 08:42 UTC, omichel commented on docs/guide/robotis-op2.md
> +Due to the small amount of backlash present in the motors, for correct modeling of this effect it is required to lower the `basicTimestep` in [WorldInfo](../reference/worldinfo.md) to 8 or less.
```suggestion
Due to the small amount of backlash present in the motors, for correct modeling of this effect it is required to lower the `basicTimestep` in [WorldInfo](../reference/worldinfo.md). It was observed that setting the `basicTimeStep` to 8 ms gives good results.
```

2021-03-19 09:49 UTC, omichel approved these changes
Thank you.

2021-03-19 09:49 UTC, merged