add command to set WEBOTS_SAFE_MODE in windows
cyberbotics/webots pull request #2968
Opened 2021-04-13 12:15 UTC by Behrouz-m

**Documentation**
If this pull-request changes the doc, add the link to the related page, including the `?version=BRANCH_NAME`, such as:
https://cyberbotics.com/doc/guide/starting-webots?version=released

2021-04-14 07:20 UTC, omichel requested changes
Thank you for this contribution. I only have a couple of styling requests.

2021-04-14 07:20 UTC, omichel commented on docs/guide/starting-webots.md
> +Using  GUI:
```suggestion
From the Windows graphical user interface:
```

2021-04-14 07:20 UTC, omichel commented on docs/guide/starting-webots.md
> +Using cmd:
```suggestion
From the `cmd` command prompt:
```

2021-04-15 15:05 UTC, Behrouz-m commented
@omichel please check it. thanks for the suggestion.

2021-04-15 15:24 UTC, omichel approved these changes
Thank you!

2021-04-15 15:26 UTC, omichel commented
@Behrouz-m: I just sent you an invite to become a member of the Committers group. Once accepted, you should be able to merge this PR.

2021-04-16 10:05 UTC, Behrouz-m commented
> 
> 
> @Behrouz-m: I just sent you an invite to become a member of the Committers group. Once accepted, you should be able to merge this PR.

Thank you. It was unexpected :)
I am happy to be a member of your team.

2021-04-16 10:06 UTC, merged

2021-04-16 10:21 UTC, omichel commented
> Thank you. It was unexpected :)
I am happy to be a member of your team.

You are welcome!