Add Summit-XL Steel robot
cyberbotics/webots pull request #2969
Opened 2021-04-14 10:55 UTC by mael25

Adds the Robotnik Summit-XL Steel robot, alongside the Sick S300 lidar that it uses.

**Tasks**
  - [ ] Create Icon

![summitxls](https://user-images.githubusercontent.com/38250944/114699452-a0f72d80-9d20-11eb-858a-4fe17aaaeaa1.png)

2021-04-20 16:28 UTC, omichel reviewed
From the picture of the sick sensor, it looks like the mesh has no crease angle as we can see the faces (normal per face) on the cylinder-like part.

2021-04-20 16:28 UTC, omichel commented on docs/guide/summit-xl-steel.md
> +  SFRotation  rotation        1 0 0 -1.5708
The default rotation should be along the Z axis, not X. Also the angle value should be 0.

2021-04-20 16:28 UTC, omichel commented on docs/guide/summit-xl-steel.md
> +  SFVec3f     translation     0 0.118 0
The orientation of the robot should be FLU, hence its default translation should be 0 0 0.118.

2021-04-20 16:28 UTC, omichel commented on projects/devices/sick/protos/SickS300.proto
> +field SFRotation rotation       0 1 0 0
```suggestion
field SFRotation rotation       0 0 1 0
```

2021-04-21 12:31 UTC, mael25 commented
> From the picture of the sick sensor, it looks like the mesh has no crease angle as we can see the faces (normal per face) on the cylinder-like part.

Yes, I checked this and it was due to the structure of the mesh: there were thin faces at each "corner" in addition to the bigger faces. I have corrected this and it works well now.
<img src="https://user-images.githubusercontent.com/38250944/115553462-b97dbf80-a2ad-11eb-988f-c815a4defb59.png" alt="sicks300" width="550"/>

2021-04-22 11:57 UTC, mael25 commented
I have added the web component, the PR should be ready now. I have kept the `rotation 0 1 0 0` field for the SickS300 as the Lidars are not yet in FLU.

2021-04-23 07:16 UTC, mael25 commented
I just thought it might be better to put the keyboard controller of the ConveyorPlatform directly in its controllers folder rather than in the one of the Summit-XL Steel

2021-05-14 15:29 UTC, BenjaminDeleze requested changes
Is it possible to move the viewpoint back a bit in the .x3d file. Because if I open it in the documentation viewer I can only see the wheels and I have to zoom out.

2021-06-02 07:33 UTC, closed without merging

2021-06-02 07:34 UTC, mael25 commented
This PR has been split in two other that target now the `develop` branch: #3121 for the `Summit-XL Steel` robot and #3122 for the `Sick S300` Lidar