Fix typo verticalfieldofview
cyberbotics/webots pull request #2972
Opened 2021-04-14 13:06 UTC by mael25

The verticalFieldOfView of the HokuyoUtm30lx was computed using a value for the fieldOfView that was corresponding to other Hokuyo lidars.

2021-04-14 14:29 UTC, omichel requested changes
Thank you!
We should probably add a line in the change log about this fix as it may break existing user simulations.

2021-04-16 06:30 UTC, omichel submitted a review, later dismissed
Thank you.

2021-04-16 07:23 UTC, mael25 commented
I had to merge master into this branch as a new bug entry was added in the meantime...

2021-04-16 07:24 UTC, omichel approved these changes

2021-04-16 07:24 UTC, merged