Fix loading of hidden position3 for Ball
cyberbotics/webots pull request #3001
Opened 2021-04-23 06:24 UTC by ad-daniel

**Description**
PR #2964 only addressed the saving of the hidden position to file, in practice however while loading it also purposefully ignores the possibility of a `position3` (which ended up overwriting `position`).
Since it slipped through, I've also a unit test that verifies the loading of hidden position for all joints.

2021-04-23 07:20 UTC, omichel requested changes
Very good. I only have a few minor suggestions.

2021-04-23 07:20 UTC, omichel commented on src/webots/nodes/WbBallJoint.cpp
>    if (index == 3) {
To improve the code readability, I would rather do something like:
```C++
  if (index != 3)
    return;
```
(the same applies for the other types of joints)

2021-04-23 07:20 UTC, omichel commented on tests/parser/controllers/generic_sensor/generic_sensor.c
> +  int nb_devices = atoi(argv[1]);
```suggestion
  const int nb_devices = atoi(argv[1]);
```

2021-04-23 07:20 UTC, omichel commented on tests/parser/controllers/generic_sensor/generic_sensor.c
> +  }
```suggestion
  while (wb_robot_step(TIME_STEP) != -1.0)
    wb_emitter_send(emitter, outbuffer, 50 * sizeof(char));
```

2021-04-23 07:20 UTC, omichel commented on tests/parser/controllers/generic_sensor/generic_sensor.c
> +  sprintf(outbuffer, "%.4f %.4f %.4f %s\n", positions[0], positions[1], positions[2], wb_robot_get_name());
We should probably use `snprintf` in general instead of `sprintf` (together with `sizeof(outbuffer)`).

2021-04-23 07:20 UTC, omichel commented on tests/parser/controllers/generic_sensor/generic_sensor.c
> +    wb_emitter_send(emitter, outbuffer, 50 * sizeof(char));
```suggestion
    wb_emitter_send(emitter, outbuffer, strlen(outbuffer) + 1);
```

2021-04-23 07:20 UTC, omichel commented on tests/parser/controllers/hidden_parameter_single/hidden_parameter_single.c
> +      }
```suggestion
      } else
        ts_assert_boolean_equal(0, "Message unknown.");
```

2021-04-23 07:20 UTC, omichel commented on tests/parser/controllers/hidden_parameter_single/hidden_parameter_single.c
> +  ts_assert_boolean_equal(received_message, "Should've received at least one message, but didn't.");
```suggestion
  ts_assert_boolean_equal(received_message, "Should have received at least one message, but didn't.");
```

2021-04-26 08:01 UTC, stefaniapedrazzi requested changes
Parser tests are different than the other tests because they mainly focus on detecting crashes at load or checking the messages printed in the console without running the simulation.

This kind of tests on hidden parameters should probably be moved to the `tests/physics` folder where the other tests about hidden fields are already located.

2021-04-26 08:08 UTC, ad-daniel commented
> This kind of tests on hidden parameters should probably be moved to the `tests/physics` folder where the other tests about hidden fields are already located.

I've modified an existing test which already verified the loading of hidden parameters and was in parser folder. Should the entire test unit be moved then?

2021-04-26 08:14 UTC, stefaniapedrazzi commented
> I've modified an existing test which already verified the loading of hidden parameters and was in parser folder. Should the entire test unit be moved then?

Yes. The whole `hidden_parameter_single` test should be moved to the `physics` folder because it is now also testing the physics behavior after loading the model.

2021-04-26 08:59 UTC, ad-daniel commented
Moved and removed the redundant returns. Thank you.

2021-04-26 11:48 UTC, stefaniapedrazzi approved these changes
Thank you

2021-04-26 12:11 UTC, omichel approved these changes

2021-04-26 12:13 UTC, merged