Added mStep increment in ros.cpp
cyberbotics/webots pull request #3040
Opened 2021-05-05 14:39 UTC by kyax32

**Description**
Fixing a bug which affects sampling period of sensors enabled from a ROS service. Sensors enabled from ROS are publishing values based on the basic time step of the world and not on the given value when enabling the sensor. mStep was not increased in ROS::run method. Additionaly I changed mStepSize by mRobot->getBasicTimeStep() in ROS::run, when passing the elapsed time to the publishValues method. mStepSize seems to be always equal to 1, even if the basic time step is bigger than 1ms.

**Related Issues**
None (Discord discussion)

**Tasks**
Add the list of tasks of this PR.
  - [ ] Task 1
  - [ ] Task 2

**Documentation**
None

**Screenshots**
None

**Additional context**
Bug was discovered while creating a VIO module using ROS environment.

2021-05-05 15:56 UTC, lukicdarkoo requested changes
Thank you for this!

I have a minor comment about the `mStepSize`.

2021-05-05 15:56 UTC, lukicdarkoo commented on projects/default/controllers/ros/Ros.cpp
> +      mSensorList[i]->publishValues(mStep * mRobot->getBasicTimeStep());
The `mStepSize` is configured in the `timeStepCallback` function. To preserve the functionality of the `timeStepCallback`, I would rather set default value of the `mStepSize` to `mRobot->getBasicTimeStep()` as soon as we have access to the `Robot` object.

2021-05-06 07:11 UTC, lukicdarkoo approved these changes
Thank you!

2021-05-06 08:40 UTC, omichel commented
@kyax32: I just sent you an invite to become a member of the Webots Committers, so that you should be able to merge this PR.

2021-05-06 13:25 UTC, merged

2021-05-06 13:26 UTC, kyax32 commented
Thanks @omichel ! The PR is now merged.