Enhancement in Makefile : add GDB option
cyberbotics/webots pull request #3056
Opened 2021-05-11 19:53 UTC by ShuffleWire

Adding -ggdb option in makefile help (a lot) GDB to debug, which it needed because of the usage of QT, probably.

2021-05-12 10:45 UTC, omichel commented
It would be probably useful to add it also to the `ode` and `wren` Makefiles.

2021-05-12 11:48 UTC, ShuffleWire commented
I will do so as soon as I've some time.
PS : Sorry for closing/reopening the PR, i've missclicked...

2021-05-15 08:47 UTC, ShuffleWire commented
As a side note, I'm not sure if we need this option for `ode` and `wren`, because it's initially caused by the use of Qt, and they don't depend on it, exact ? I've not tried to build and debug them, to be fair.
If needed, I'm not sure were to add it, because in both `ode` and `wren` there is no place to add debbuging options. Found one in Makefile.include, however. So I've made both modification, but only one of each should be enough.

2021-05-17 10:43 UTC, omichel requested changes
I believe it is sufficient to apply it in the Makefile.include as this one is included by the ODE and WREN makefiles.

2021-05-17 10:43 UTC, omichel commented on src/wren/Makefile
> +
```suggestion
```

2021-05-17 10:43 UTC, omichel commented on src/ode/Makefile
> +endif
```suggestion
```

2021-05-17 10:54 UTC, omichel commented
Also, I believe that we should remove the `-g` option and leave only the `-ggdb` one, which is seems indeed better, see: https://stackoverflow.com/questions/668962/what-is-the-difference-between-gcc-ggdb-and-gcc-g

2021-05-18 14:49 UTC, ShuffleWire commented
As far as I understand, the -g option is more "standard". Whould removing it could cause issue when debugging with any thing others than gdb ? If not, or if it's not a issue, I would remove it.

2021-05-18 15:38 UTC, ShuffleWire commented
That it, finally just replacing -g with -ggdb in two location

2021-05-18 15:43 UTC, omichel approved these changes
Thank you.

2021-05-19 08:32 UTC, merged