Add JavaScript support for procedural PROTO
cyberbotics/webots pull request #3087
Opened 2021-05-25 08:49 UTC by ad-daniel

**Description**
TODO

2021-06-10 15:15 UTC, ad-daniel commented
The failing test is unrelated to this PR, the test suite passes successfully.

2021-06-11 13:23 UTC, omichel commented on docs/reference/javascript-procedural-proto.md
> +Webots cannot load procedural PROTO nodes directly, therefore the procedural PROTO is first translated to pure JavaScript and the resulting script is evaluated by a JavaScript Engine, in Webot's case
```suggestion
Webots cannot load procedural PROTO nodes directly, therefore the procedural PROTO is first translated to pure JavaScript and the resulting script is evaluated by a JavaScript engine, in Webot's case using QJSEngine, and the result of this process yields a VRML97 compatible PROTO file which is then loaded by Webots as any other non-procedural would.
```

2021-06-11 13:29 UTC, omichel commented on docs/reference/javascript-procedural-proto.md
> +The available modules are the following.
```suggestion
The available modules are the following:
```

2021-06-11 13:39 UTC, omichel commented on docs/reference/procedural-proto-nodes.md
> +> **Note**: Lua support will be dropped in future releases, wherever possible [JavaScript](javascript-procedural-proto.md) should be preferred instead.
That seems a bit redundant with line 9...

2021-06-11 13:52 UTC, omichel commented on tests/protos/worlds/template_proto_follow_solid_LUA.wbt
> +#VRML_SIM R2021b utf8
The name of this file doesn't seem to be consistent with others (LUA in capital letters).

2021-06-14 07:43 UTC, BenjaminDeleze requested changes
Seems good to me, there is just two small things that I am not sure about

2021-06-14 07:43 UTC, BenjaminDeleze commented on src/webots/core/WbTemplateEngine.cpp
> +    }
```suggestion
    static bool firstJavaScriptCall = true;
    if (firstJavaScriptCall) {
      initializeJavaScript();
      firstJavaScriptCall = false;
    }
```

2021-06-15 06:28 UTC, BenjaminDeleze approved these changes
Seems good to me

2021-06-15 06:49 UTC, omichel approved these changes
I tested it on Windows and it works nicely.

2021-06-15 08:26 UTC, merged