Add Summit-XL Steel
cyberbotics/webots pull request #3121
Opened 2021-06-02 07:00 UTC by mael25

**Description**
Adds the Robotnik Summit-XL Steel robot
**This PR replaces #2969 which targeted the `master` branch**

**Tasks**
  - [x] Create Icons
  - [x] Documentation Summit-XL Steel
  - [x] Better appearance & documentation SickS300 (lidar-sensors.md)
  - [x] Update robots Makefile
  - [x] Update Changelog
  - [x] Improve appearance base & Redo pictures/icons
  - [x] Add web component

<img src="https://user-images.githubusercontent.com/38250944/115353386-ba80f500-a1b8-11eb-91c6-67f812ff1925.png" width="50%">.

2021-06-10 14:00 UTC, BenjaminDeleze requested changes
The plastic crate that is on the robotino plateform is a bit _in_ the conveyor belt and so it cannot move.

2021-06-11 09:15 UTC, mael25 commented on docs/guide/summit-xl-steel.md
> +Designed by Robotnik, [Summit-XL Steel](summit-xl-steel.md) is a four-wheeled (mecanum) robot.
You're right, I have replaced it by the link to the webpage on the constructor website, as it is done for several other robots currently.

2021-06-11 14:25 UTC, mael25 commented
@BenjaminDeleze I have slightly offseted the `PlasticCrate` so that it moves on the conveyor belt. I have also added the missing sensors (`GPS` and RGBD camera, implemented as a `Camera` and a `RangeFinder`)

2021-06-11 14:58 UTC, BenjaminDeleze approved these changes
Thank you!

2021-06-11 15:00 UTC, merged