Fix world update for Summit-XL steel
cyberbotics/webots pull request #3172
Opened 2021-06-14 21:02 UTC by ad-daniel

**Description**
World update test fails because of the field order/formatting in the world file.

2021-06-15 06:30 UTC, mael25 commented
Thanks! I will do the same for the similar Fabtino world that has just been merged.

2021-06-15 12:42 UTC, ad-daniel commented
Looks to be working, check if you can approve it.

2021-06-15 15:20 UTC, mael25 commented
I think we could take the opportunity of this PR to add  the `renderingDevicePerspectives` in the `.wbproj` to avoid the full screen cameras.

2021-06-15 15:51 UTC, mael25 commented
I will do the same for the `Mir100`

2021-06-16 08:09 UTC, mael25 commented
So I took the opportunity of this PR to also:

- [ ] Enable the camera in the demo controllers
- [ ] Choose a proper camera window size for the .wbproj file
- [ ] In the controllers, get the basic timestep from the robot and not redefine it
- [ ] Remove an unnecessary pillar in the Mir100 world and correct the height of its camera

2021-06-16 08:24 UTC, omichel requested changes
A few const would be nice.

2021-06-16 08:24 UTC, omichel commented on projects/objects/factory/conveyors/controllers/keyboard_conveyor_platform/keyboard_conveyor_platform.c
> +  int time_step = wb_robot_get_basic_time_step();
```suggestion
  const int time_step = wb_robot_get_basic_time_step();
```

2021-06-16 08:24 UTC, omichel commented on projects/robots/mir/mir100/controllers/keyboard_control/keyboard_control.c
> +  int time_step = wb_robot_get_basic_time_step();
```suggestion
  const int time_step = wb_robot_get_basic_time_step();
```

2021-06-16 08:24 UTC, omichel commented on projects/robots/rec/fabtino/controllers/keyboard_control/keyboard_control.c
> +  int time_step = wb_robot_get_basic_time_step();
```suggestion
  const int time_step = wb_robot_get_basic_time_step();
```

2021-06-16 08:24 UTC, omichel commented on projects/robots/robotnik/summit_xl_steel/controllers/keyboard_control/keyboard_control.c
> +  int time_step = wb_robot_get_basic_time_step();
```suggestion
  const int time_step = wb_robot_get_basic_time_step();
```

2021-06-16 14:20 UTC, ad-daniel commented
Looks good to me, I can't approve it though

2021-06-16 14:25 UTC, merged