Add force/torque scale factor to Worldinfo
cyberbotics/webots pull request #3175
Opened 2021-06-15 10:22 UTC by mael25

**Description**
This PR adds two new fields to `WorldInfo`: `dragForceScale` and `dragTorqueScale`. They allow the user to set the order of magnitude of the force/torque applied to a `Solid` inside the Webots interface when doing (Alt+Click). Indeed, it is sometimes difficult to apply a force/torque in the desired range when dragging the mouse. The force is computed as follow: 

*F* [N] = `dragForceScale` * `Solid.mass` * *d*, where *d* corresponds to the vector created by dragging the mouse (in meters),

instead of F [N] = _constant_ * *d*^3 , as we do not need anymore the cubic of *d* to be able to apply a big force. Besides, taking into account the mass allows us to adapt the force to the object (this was already the case for the torque computation).

The torque is computed in the same idea:

*T* [Nm] = `dragTorqueScale` * `Solid.mass` * *d*,

instead of T [Nm] = _constant_  * `Solid.mass` * *d*   (nothing changes except we can set the value of the _constant_).

The default values of the added fields corresponds to the _constant_ values that are currently used.

2021-06-15 12:13 UTC, omichel requested changes

2021-06-15 16:45 UTC, ShuffleWire commented
For the torque part, should we not better use the rotational inertia (from the inertia matrix) instead of mass ?

2021-06-16 07:00 UTC, omichel requested changes
The behavior looks good to me.
However, I could clean-up a little bit the code.

2021-06-16 07:00 UTC, omichel commented on src/webots/gui/WbDragSolidEvent.cpp
>  }
Code clean-up: I would delete this apparently useless `mMagnituteString` field and make this method const.
The same applies to the `WbDragTorqueEvent` object.

2021-06-16 07:50 UTC, mael25 commented
> For the torque part, should we not better use the rotational inertia (from the inertia matrix) instead of mass ?

@ShuffleWire This would indeed give a more relevant range of torque and would enable to adapt it according to the direction of the torque to apply, but in most use cases the mass gives us already a good idea of the order of magnitude of the torque to apply.

However, if this is a feature that you would really like to see into Webots, feel free to implement it ! ;)

2021-06-16 08:44 UTC, ShuffleWire commented
> > For the torque part, should we not better use the rotational inertia (from the inertia matrix) instead of mass ?
> 
> @ShuffleWire This would indeed give a more relevant range of torque and would enable to adapt it according to the direction of the torque to apply, but in most use cases the mass gives us already a good idea of the order of magnitude of the torque to apply.
> 
> However, if this is a feature that you would really like to see into Webots, feel free to implement it ! ;)

Yes, I do agree, we are not doing accurate physic here, and it would be relevant only for part with mass very far from center of mass, which is not common. Mass will be nice, then :)

2021-06-16 09:04 UTC, merged