Add the name of a solid next to it in tree
cyberbotics/webots pull request #3198
Opened 2021-06-17 22:16 UTC by ShuffleWire

Fix https://github.com/cyberbotics/webots/issues/3157

However, the fix is not the right way to do it, but I don't which one is the good one : 
- add "Solid" in either WbNodeUtilities::isDeviceTypeName or WbNodeUtilities::isSolidDeviceTypeName
- or remove the condition that this PR modify. In fact I don't understand why should we limit the display of the name to certains types. As long as the node have a "name" field, we should be good to display it.

2021-06-18 07:00 UTC, omichel commented
Thank you for this contribution.
I believe the second option you propose is the best: as long as the node has a "name" field (and no DEF name), we should use it to display it in the scene tree.

2021-06-18 07:02 UTC, omichel commented
It would be nice to also add a line in the change log about this.

2021-06-18 07:40 UTC, ShuffleWire commented
I'm not convinced if we should add the name for node which are def or use, however.

2021-06-18 07:45 UTC, omichel commented
USE/DEF name are displayed if specifed, this already gives a good indication on what the node is (if the USE/DEF name is well chosen). So, I would not display the "name" field in case the DEF/USE name is specified, as it would provide too much information which may be confusing.

2021-06-22 11:56 UTC, ad-daniel commented
Just a heads up, when the PR already has a reviewer assigned, re-request the review directly to that person after making the necessary changes. This way it's less likely to go unnoticed. Here's an example
![rev](https://user-images.githubusercontent.com/44834743/122920053-3d613000-d361-11eb-9bef-232fcc7b8f5c.png)

2021-06-22 12:12 UTC, ShuffleWire commented
> Just a heads up, when the PR already has a reviewer assigned, re-request the review directly to that person after making the necessary changes. This way it's less likely to go unnoticed. Here's an example

Thank for the advice :) 
However, afaik, I do think I can't to much more from my side : 
![image](https://user-images.githubusercontent.com/83014015/122922084-8d40f680-d363-11eb-87ef-554113c14057.png)
omichel is already requested, isn't ? and I don't think their are any pending requested change

2021-06-22 12:17 UTC, omichel requested changes
That looks very good to me.
Maybe we can just take advantage of this PR to make it const correct?

2021-06-22 12:17 UTC, omichel commented on src/webots/scene_tree/WbTreeItem.cpp
> +        WbSFString *name = mNode->findSFString("name");
```suggestion
        const WbSFString *name = mNode->findSFString("name");
```

2021-06-22 12:20 UTC, ShuffleWire commented on src/webots/scene_tree/WbTreeItem.cpp
> +        WbSFString *name = mNode->findSFString("name");
of course !

2021-06-22 12:23 UTC, omichel approved these changes
Thank you.

2021-06-22 12:23 UTC, ad-daniel commented
> Thank for the advice :)
> However, afaik, I do think I can't to much more from my side :

![rev](https://user-images.githubusercontent.com/44834743/122923700-3dfbc580-d365-11eb-9e2f-dff07655b583.png)
We generally handle the assignment of the reviewer, what I mean is after doing the changes and going out of draft, you can use this button to re-request the specific person for a second review.

2021-06-22 12:37 UTC, ShuffleWire commented
@ad-daniel ok so going in/out of draft is the trick. Will be trying that next time !

2021-06-22 12:38 UTC, merged