Display the magnitude of linear and rotationnal speed
cyberbotics/webots pull request #3209
Opened 2021-06-21 14:01 UTC by ShuffleWire

**Description**
Allows to easily monitor the displacement speed of a robot with changing direction

2021-06-23 11:02 UTC, stefaniapedrazzi commented
Linear and angular velocities are 3D vectors.
Adding a forth value like it is done in this PR is wrong and would just confuse users.

2021-06-23 11:51 UTC, ShuffleWire commented
What about this way ?
![image](https://user-images.githubusercontent.com/83014015/123091836-1ae71980-d42a-11eb-958d-6bf43baba984.png)

2021-06-23 13:36 UTC, stefaniapedrazzi commented
This would be acceptable.

Please check your code style before asking for a new review (const variables, variables names, etc.) and make sure you also add an entry in the ChangeLog.

2021-06-28 06:25 UTC, stefaniapedrazzi requested changes
Thank you.
This contribution is fine.
Could you please just adjust the change log entry?

2021-06-28 06:25 UTC, stefaniapedrazzi commented on docs/reference/changelog-r2021.md
> +    - Display magnitude of velocity/rotational speed vectors, to help monitoring robot displacement ([#3209](https://github.com/cyberbotics/webots/pull/3209)).
This is an enhancement and not a new major feature. Could you please move it in the `Enhancements` section?
Moreover we should use the correct terminology as displayed in the UI:
```suggestion
    - Display magnitude of linear and rotational velocity vectors in the [Field Editor](../guide/the-scene-tree.md#field-editor), to help monitoring robot displacement ([#3209](https://github.com/cyberbotics/webots/pull/3209)).
```

2021-06-28 16:01 UTC, stefaniapedrazzi approved these changes
Thank you

2021-06-28 17:01 UTC, merged