Use the OpenCV coordinate system for the Camera node
cyberbotics/webots pull request #3472
Opened 2021-07-20 07:03 UTC by lukicdarkoo

![](http://wiki.ros.org/image_pipeline/CameraInfo?action=AttachFile&do=get&target=CameraCoords.png)

2021-07-27 07:33 UTC, omichel requested changes

2021-07-27 07:33 UTC, omichel commented on projects/samples/devices/worlds/camera.wbt
> +      rotation 1 4.7949e-09 1.32679e-06 3.14159
That looks odd, can't we simplify?
```suggestion
      translation 0 0.0915 -0.04
      rotation 1 0 0 3.14159
```

2021-07-27 07:33 UTC, omichel commented on projects/samples/devices/worlds/camera.wbt
> +          translation 0 -2.38898e-05 -0.015
```suggestion
          translation 0 0 -0.015
```

2021-07-27 07:33 UTC, omichel commented on src/webots/nodes/WbCamera.cpp
> +  }
```suggestion
  if (hasBeenSetup())
    mWrenCamera->rotatePitch(M_PI);  // OpenCV camera axis orientation
```

2021-07-27 07:33 UTC, omichel commented on tests/api/worlds/camera_revert.wbt
> +          translation 0 -2.38898e-05 -0.015
```suggestion
          translation 0 0 -0.015
```

2021-07-27 07:33 UTC, omichel commented on tests/api/worlds/robot_multiple_step.wbt
> +      rotation 0.70710528118436 -3.3905113482557537e-09 0.707108281185553 3.14159
```suggestion
      rotation 0.70710528118436 0 0.707108281185553 3.14159
```

2021-07-27 07:33 UTC, omichel commented on projects/samples/devices/worlds/camera_auto_focus.wbt
> +        focalDistance 0.4623355950533638
Why do we have to change this?

2021-07-27 10:17 UTC, lukicdarkoo commented on projects/samples/devices/worlds/camera_auto_focus.wbt
> +        focalDistance 0.4623355950533638
Slipped :/

2021-07-27 10:20 UTC, lukicdarkoo commented
I want to compare with Gazebo before merging. Because, as stated here:

> In the case of cameras, there is often a second frame defined with a "_optical" suffix. This uses a slightly different convention:
> - z forward
> - x right
> - y down

there are apparently two frames, one FLU and the other the OpenCV one.

2021-07-28 10:03 UTC, lukicdarkoo commented
A good example is [realsense_ros_gazebo](https://github.com/nilseuropa/realsense_ros_gazebo).

In the example, the camera device is associated with `${sensor_name}_link` which follows the FLU convention. The transform tree continues as follows:
```
${sensor_name}_link (FLU)
    |-- ${sensor_name}_depth_frame (FLU)
        |-- ${sensor_name}_depth_optical_frame (OpenCV)
```

Here is a RViz snapshot:
![image](https://user-images.githubusercontent.com/2135826/127302477-0e22ecf0-8fb4-4bb9-b35e-294ead778ec5.png)

Therefore, they have a dummy link `${sensor_name}_depth_optical_frame` to get the optical frame. I am not sure how does it reflect in our models. To me, the Camera node should be FLU and a user can add a child node to get the optical frame.

2021-07-29 13:14 UTC, lukicdarkoo commented
Considering that all camera devices should follow the FLU convention, do you think it is a good idea to convert the WREN camera? 
I have already started in the `feature-flu-camera` branch, but many things are broken. I am not sure what else we will discover.

2021-07-29 13:59 UTC, stefaniapedrazzi commented
> Considering that all camera devices should follow the FLU convention, do you think it is a good idea to convert the WREN camera?
> I have already started in the `feature-flu-camera` branch, but many things are broken. I am not sure what else we will discover.

Yes, it seem good to convert the WREN camera.
Note that WREN camera is used for all the rendering devices (main viewpoint, camera, range finder, lidar) and not just for camera devices so if they do not use the same convention it might be needed to adjust the orientation in some cases.
But the main viewpoint and camera devices are probably the most used functionalities.

2021-07-30 12:47 UTC, omichel commented
I assume this PR is on hold until #3525 is merged.

2021-07-30 14:40 UTC, lukicdarkoo commented
> I assume this PR is on hold until #3525 is merged.

It should be replaced by #3525 (along with conversion of all other camera based devices)

2021-08-03 10:31 UTC, omichel commented
It looks all good to me, but I would try to improve a little bit the documentation image to make it easier to understand, maybe with a narrower angle camera and without selecting the robot, but only the camera.

2021-08-03 11:57 UTC, lukicdarkoo commented
> It looks all good to me, but I would try to improve a little bit the documentation image to make it easier to understand, maybe with a narrower angle camera and without selecting the robot, but only the camera.

Good point, I have just replaced the image. If you have any other on how to improve the image let me know. I believe those images are very important.

2021-08-03 12:03 UTC, omichel approved these changes
It is way better. Thank you.

2021-08-03 12:46 UTC, merged