Clean code related to Ubuntu 16.04
cyberbotics/webots pull request #3480
Opened 2021-07-21 12:45 UTC by mael25

**Description**
Fixes #3424
Remove the code related to Ubuntu 16.04 that is no more needed

2021-07-21 13:40 UTC, mael25 commented
Regarding the search of an existing X11 library in  [Makefile.robotis-op2](https://github.com/cyberbotics/webots/blob/master/projects/robots/robotis/darwin-op/controllers/Makefile.robotis-op2#L38), we can remove the part concerning Ubuntu <=10 and could modify the part for Ubuntu >=12 to this:
```
ifneq ($(wildcard /usr/lib/($OSARCH)-linux-gnu/libX11.so.6),)
LIBX11_SOURCE = /usr/lib/($OSARCH)-linux-gnu/libX11.so.6
endif
```

2021-07-21 14:46 UTC, stefaniapedrazzi commented on scripts/packaging/webots_distro.c
> +#if defined(WEBOTS_UBUNTU_18_04)
This could be simplified to 
```suggestion
#ifdef WEBOTS_UBUNTU_18_04
```

2021-07-21 14:46 UTC, stefaniapedrazzi commented on scripts/packaging/webots_distro.c
> +#if defined(WEBOTS_UBUNTU_18_04)
This could be simplified
```suggestion
#ifdef WEBOTS_UBUNTU_18_04
```

2021-07-21 14:46 UTC, stefaniapedrazzi commented on docs/local_exporter.py
> -                # On Ubuntu 16.04 there are issues with the certificates.
I would keep this comment because it explains why on Linux the behavior is different.

2021-07-21 14:46 UTC, stefaniapedrazzi commented
> Regarding the search of an existing X11 library in [Makefile.robotis-op2](https://github.com/cyberbotics/webots/blob/master/projects/robots/robotis/darwin-op/controllers/Makefile.robotis-op2#L38), we can remove the part concerning Ubuntu <=10 and could modify the part for Ubuntu >=12 to this:
> 
> ```
> ifneq ($(wildcard /usr/lib/($OSARCH)-linux-gnu/libX11.so.6),)
> LIBX11_SOURCE = /usr/lib/($OSARCH)-linux-gnu/libX11.so.6
> endif
> ```

> Regarding the search of an existing X11 library in [Makefile.robotis-op2](https://github.com/cyberbotics/webots/blob/master/projects/robots/robotis/darwin-op/controllers/Makefile.robotis-op2#L38), we can remove the part concerning Ubuntu <=10 and could modify the part for Ubuntu >=12 to this:
> 
> ```
> ifneq ($(wildcard /usr/lib/($OSARCH)-linux-gnu/libX11.so.6),)
> LIBX11_SOURCE = /usr/lib/($OSARCH)-linux-gnu/libX11.so.6
> endif
> ```

I don't think we ever had issues with the architecture.
So maybe it is not even necessary to compute it and we could keep the  hard coded `i386-linux-gnu`.
But if it is easy to get it is ok to improve it.

2021-07-21 14:48 UTC, stefaniapedrazzi commented
Personally I would include this change in R2022a (that will be released in December) and not R2021c.
It we decide so, then it is fine to clean up the code now but we should wait until R2021c is released before merging.

2021-07-21 14:53 UTC, stefaniapedrazzi commented
Actually `Makefile.robotis-op2` refers to the OS installed on the robot.
So I would keep it as is unless we know exactly which OS is currently installed on the Robotis robots.

2021-07-22 07:24 UTC, mael25 commented
I have also removed the double underscore fix for Ubuntu 16.04 on Unity (https://github.com/cyberbotics/webots-dev/pull/7470) as it is no longer needed. Indeed, it was applied only on Linux if the environment variable XDG_CURRENT_DESKTOP=="Unity". Since Ubuntu 16.10, this variable has an other format, i.e. "Unity:Unity7" (see https://bugs.launchpad.net/ubuntu/+source/unity-control-center/+bug/1629668), so the fix is not applied anyway. I have tested on 18.04 with Unity, and in my case the variable was "Unity:Unity7:ubuntu", so the fix was not applied and the underscores were looking fine (not doubled) in the Robot context menu.

2021-07-22 07:25 UTC, mael25 commented
So the last step will be to add an entry in the Changelog about this PR before merging (in R2021c or R2022a).

2021-07-26 15:17 UTC, stefaniapedrazzi commented
Note that this PR should target the develop branch.

2021-07-26 15:20 UTC, stefaniapedrazzi commented
Second though: it seems fine to apply this to R2021c.

2021-07-28 10:35 UTC, mael25 commented
I added an entry to the Changelog and changed the targeted branch, so this should be ready to merge.

2021-07-28 10:53 UTC, stefaniapedrazzi requested changes
Thank you

2021-07-28 10:53 UTC, stefaniapedrazzi commented on docs/reference/changelog-r2021.md
> +Released on September, 30th, 2021.
I would not set a date for the moment
```suggestion
Released on XX, XXth, 2021.
```

2021-07-28 11:23 UTC, stefaniapedrazzi approved these changes
Thank you!

2021-07-28 11:34 UTC, merged