Create Debian package from Ubuntu 20.04
cyberbotics/webots pull request #3507
Opened 2021-07-26 15:30 UTC by stefaniapedrazzi

Drop support of Debian package on Ubuntu 18.04.
It is already stated in the documentation that the Debian package works only on the latest Ubuntu LTS:
https://www.cyberbotics.com/doc/guide/installation-procedure#installation-on-linux

This should fix #3503 and probably also #3486.

2021-07-26 15:32 UTC, lukicdarkoo commented
Regarding #3486, if we upgrade to Ubuntu 20.04 it will work with ROS Noetic, but not with ROS Melodic.

2021-07-26 15:38 UTC, stefaniapedrazzi commented
> Regarding #3486, if we upgrade to Ubuntu 20.04 it will work with ROS Noetic, but not with ROS Melodic.

Yes.
I will add a note about this in the documentation.

2021-07-28 08:02 UTC, lukicdarkoo requested changes
Thank you, just a tiny improvement maybe

2021-07-28 08:05 UTC, stefaniapedrazzi commented on docs/guide/tutorial-8-using-ros.md
>  These examples were tested with ROS `noetic` and `melodic` on Linux.
The reason for this has to be checked in the history of the file.
But can be change.

2021-07-28 08:17 UTC, lukicdarkoo approved these changes
Thanks

2021-07-28 08:56 UTC, merged