TouchSensor to FLU
cyberbotics/webots pull request #3517
Opened 2021-07-28 12:08 UTC by mael25

**Description**
Switch the `TouchSensor` (type=force) measurement axis form z to x, in order to meet FLU convention.

**Tasks**
- [x] Add illustration

**Documentation**
https://cyberbotics.com/doc/reference/touchsensor?version=feature-enu-touchsensor

2021-07-29 08:25 UTC, lukicdarkoo commented
@cyberbotics/maintainers I would add an image of each sensor (not just specific to this PR) in the documentation that clearly depicts the axes. I started it here:
https://cyberbotics.com/doc/reference/lidar?version=feature-lidar-flu#description

That way we will establish clear conventions and it will be easier for the users to get familiar with the sensors. A few guidelines:
- The sensor image should contain a context, like a typical physical sensor, robot, and environment. Additional sketches (without context) can be included if necessary.
- The context (robot and environment) should be simple, it should not distract a user.
- The axes should be clearly visible.
- The important parts of the sensors should be tagged.
- If the optional rendering (`View > Optional Rendering`) is available for the sensor it should be visible in the picture (and tagged).

2021-07-30 06:39 UTC, mael25 commented
@lukicdarkoo I have added a picture (https://cyberbotics.com/doc/reference/touchsensor?version=feature-enu-touchsensor#coordinate-system) with the coordinate system of the `TouchSensor`, let me know if you think it is sufficient to understand the device.

2021-07-30 07:39 UTC, lukicdarkoo requested changes
I believe we can merge this one without affecting the other PRs

2021-07-30 07:39 UTC, lukicdarkoo commented on docs/reference/touchsensor.md
> +For example, if the [TouchSensor](#touchsensor) is used as foot sensor, then the x-axis should be oriented downwards.
```suggestion
For example, if the [TouchSensor](#touchsensor) is used as a foot sensor then the x-axis should be oriented downwards.
```

2021-07-30 07:45 UTC, lukicdarkoo approved these changes
Thank you

2021-07-30 09:09 UTC, merged