Implement more fluid object rotation
cyberbotics/webots pull request #3540
Opened 2021-08-04 14:44 UTC by lukicdarkoo

Sometimes, when the viewpoint is aligned with the object's axis of rotation, it is hard to rotate the object. This object rotation mechanism follows the one in Blender.

Let me know whether you like it (and I will proceed with the implementation)?

2021-08-04 15:05 UTC, ShuffleWire commented
That is so nice !

2021-08-09 06:41 UTC, stefaniapedrazzi commented
Shouldn't the new black line start from the center of the object (like in Blender) instead of the point when the user clicks?
Given that the rotation center is in any case the center of the object I think it would make more sense.

2021-08-09 06:43 UTC, stefaniapedrazzi commented on docs/reference/changelog-r2021.md
> +    - Improved UX when using the object rotation around axis feature ([#3540](https://github.com/cyberbotics/webots/pull/3540)).
I'm not sure that users that will read the change log will understand what is UX.

2021-08-09 06:45 UTC, stefaniapedrazzi requested changes
Apart from the comment on the starting point of the new black arrow, the behavior seems fine.

2021-08-09 06:45 UTC, stefaniapedrazzi commented on src/webots/wren/WbTranslateRotateManipulator.cpp
> +  // Check if the vector is parallel to the xy-plan of the camera (dot product close to zero)
```suggestion
  // Check if the vector is parallel to the xy-plane of the camera (dot product close to zero)
```

2021-08-09 06:58 UTC, lukicdarkoo commented
> Shouldn't the new black line start from the center of the object (like in Blender) instead of the point when the user clicks?
> Given that the rotation center is in any case the center of the object I think it would make more sense.

That's a big question :) In Blender, there are no curved arrow widgets, so it is a bit different. I am afraid it would be unintuitive to click on the arrow widget and the center of rotation jumps to the object.

I will implement as you suggested and we can compare

2021-08-09 08:42 UTC, lukicdarkoo commented
@stefaniapedrazzi I definitely like more your suggestion. Let me know if it is better now

2021-08-09 09:24 UTC, stefaniapedrazzi commented
Thank you! I think it is better like this.
If you think that it is still not very intuitive we could also show the other two axis (short lines same as when showing the coordinate system) to better mark the center of the object.
Then if we have this new black arrow that is rotating we may evaluate if it still makes sense to also rotate the round arrow.

There is just one issue with this PR that is if the viewpoint is located on the negative side of the rotation axis, the resulting rotation is inverted with respect to the mouse drag and to the expected rotation.

2021-08-11 06:29 UTC, lukicdarkoo commented
> If you think that it is still not very intuitive we could also show the other two axis (short lines same as when showing the coordinate system) to better mark the center of the object.

Implemented

> Then if we have this new black arrow that is rotating we may evaluate if it still makes sense to also rotate the round arrow.

I believe that the arrows are still indicators, they clearly indicate the axis of rotation.

> There is just one issue with this PR that is if the viewpoint is located on the negative side of the rotation axis, the resulting rotation is inverted with respect to the mouse drag.

As soon as GitHub is fully functional I will push the update

2021-08-18 13:18 UTC, stefaniapedrazzi commented
Is this PR waiting for a new review?

2021-08-18 13:46 UTC, lukicdarkoo commented
> Is this PR waiting for a new review?
> I didn't receive any review request.

It is ready for review

2021-08-18 14:43 UTC, stefaniapedrazzi approved these changes
Thank you

2021-08-19 06:13 UTC, merged