Fix supervisor node set visibility
cyberbotics/webots pull request #3543
Opened 2021-08-05 07:10 UTC by stefaniapedrazzi

Fix #3529:
if given node doesn't have a dedicated Wren node, then apply visibility to closest descendants with dedicated Wren node.

Only `WbBillboard`, `WbGeometry`, `WbTransform` and `WbMuscle` have a dedicated Wren node.
For all the other nodes we have to retrieve the descendant nodes:

Nodes overriding the function to retrieve closes descendant nodes with dedicated Wren node:
|Node | Function Overridden | Comments |
| ------ | --------- | -------- |
| BasicJoint | x  | |
| Billboard | x | |
| Geometry | x | |
| Group | x | |
| Motor | x | |
| Muscle  | x | Users can override the visibility properties in the main view switching the `Muscle.isVisible` flag |
| Propeller | x | Webots code overrides the visibility properties when enabling/disabling the slow/fast helix |
| Shape | x | |
| Slot | x | |
| SolidReference | x | |
| Transform | x | |
| Background | ? | This function cannot be used to hide background from cameras | 
| Light | | This function cannot be used to hide lights from cameras  |
| Fog | | This function cannot be used to hide fog from cameras |

Nodes that doesn't have any associated Wren nodes:
Appearance, Background, Brake, Color, ContactProperties, Coordinate, Damping, Focus, Fog, ImageTexture, ImmersionProperties, JointParameters, Lens, LensFlare, Material, Normal, PBRAppearance, Physics, Recognition, TextureCoordinate, TextureTransform, Viewpoint, WorldInfo, Zoom

Remaining nodes are derived from other nodes already listed.

2021-08-05 07:46 UTC, stefaniapedrazzi commented
I fixed the set visibility function so that it is never applied to parent and sibling nodes.
However the `wb_supervisor_node_set_visibility` function has (same as previous version) some limitations that could only be overcome by adding additional mechanisms. These are listed in the table in PR description.
But I'm not sure it is worth adding these additional mechanisms now or wait until we have use cases that requires the resolution.

2021-08-05 07:51 UTC, omichel commented
I believe we should simply document these limitations in the reference manual for now as I believe they are not a problem for most use cases.

2021-08-09 05:59 UTC, stefaniapedrazzi commented
I has to fix conflicts in the ChangeLog.

2021-08-09 14:58 UTC, ad-daniel requested changes
Looks good, only very minor details

2021-08-09 14:58 UTC, ad-daniel commented on tests/api/controllers/supervisor_node_set_visibility/supervisor_node_set_visibility.c
>                       "Camera 0 should not see the red box after it is been hide from this camera.\n");
```suggestion
                     "Camera 0 should not see the red box after it was hidden from this camera.\n");
```

2021-08-09 14:58 UTC, ad-daniel commented on tests/api/worlds/supervisor_node_set_visibility.wbt
> +      translation 0 0.84 5.50586e-07
```suggestion
      translation 0 0.84 0
```

2021-08-09 14:58 UTC, ad-daniel commented on tests/api/worlds/supervisor_node_set_visibility.wbt
> +      translation 0 0.84 5.50586e-07
```suggestion
      translation 0 0.84 0
```

2021-08-09 15:11 UTC, ad-daniel submitted a review, later dismissed

2021-08-09 15:11 UTC, ad-daniel commented
Thank you.

2021-08-09 15:40 UTC, lukicdarkoo approved these changes

2021-08-09 18:34 UTC, merged