FLU: Implement backward compability mechanism
cyberbotics/webots pull request #3619
Opened 2021-08-27 10:23 UTC by lukicdarkoo

To avoid breaking worlds and PROTOs we add a mechanism to handle the backward compatibility by adding Transform nodes and rotation Transform descendants.

**Tasks**
  - [x] Proof of concept
  - Cases
    - [x] 21b PROTO inside 21b PROTO
    - [x] 21c PROTO inside 21b PROTO
    - [x] 21b PROTO inside 21c PROTO
    - [x] Primitive inside 21b PROTO
    - [x] Primitive inside 21b world
  - Cover all nodes
    - [x] Cylinder
    - [x] Capsule
    - [x] Cone
    - [x] Plane
    - [x] Elevation grid
    - [x] Camera
    - [x] Range Finder
    - [x] Lidar
    - [x] Radar
    - [x] Track
    - [x] Viewpoint
    - [x] TouchSensor
    - [x] Connector
    - [x] Emitter & Receiver
    - [x] Pen
  - [x] Fix reset 
  - [x] Handle USE/DEF
  - [x] Add tests

World example
```
#VRML_SIM R2021c utf8
WorldInfo {
}
Viewpoint {
  orientation 0.1763811647303118 -0.3150091039421665 -0.9325550649489456 5.201713829247902
  position -0.3639376985270853 -1.5105649727458803 1.0602391552040498
}
TexturedBackground {
}
TexturedBackgroundLight {
}
Floor {
  size 100 100
}
Robot {
  translation -2.69 0 0
  children [
    Camera {
      children [
        DEF BOX_SHAPE Shape {
          geometry Box {
            size 0.1 0.1 0.1
          }
        }
      ]
      boundingObject USE BOX_SHAPE
    }
  ]
}
TrashContainer {
}
JetBot {
}
UR3e {
  translation 0 0.33 1.54865e-06
  rotation 1 0 0 4.692820414042842e-06
}
DEF TEST Spot {
  translation 1.02 0.624 0.6
  rotation 1 0 0 1.5708
}
```

<table>
<tr><td colspan="2">Imagine a user has a custom built of the Khepera IV robot</td></tr>
<tr>
<td>

![Screenshot-20210914165331-531x592](https://user-images.githubusercontent.com/2135826/133281094-d78690b8-b699-4c2f-8d12-3180e3e6c2bd.png)
</td>
<td>

![Screenshot-20210914165456-402x384](https://user-images.githubusercontent.com/2135826/133281322-b58aff22-b921-40be-8647-a975f26e3579.png)
</td>
</tr>

<tr>
<td>

![Screenshot-20210916145443-909x673](https://user-images.githubusercontent.com/2135826/133615865-18f7bf2c-adef-4447-b673-6510a60a55f9.png)
Before the backwards compatibility fix
</td>
<td>

![Screenshot-20210916145502-986x624](https://user-images.githubusercontent.com/2135826/133615895-39f78cfa-6ed1-46fb-b9f5-b29040119445.png)
After the backwards compatibility fix
</td>
</tr>

</table>

2021-09-10 07:14 UTC, lukicdarkoo commented
There are a lot of edge cases. From my point of view, it is not critical to cover all of them as far as we properly notify a user of them (and we cover like 95% of cases, otherwise it doesn't make sense).

With this PR, we can achieve "a high conversion coverage" for devices and geometries. However, we have changed the orientation of pretty much any PROTO. I am afraid a lot of users use our PROTOs (a typical example being the `Floor` PROTO), so the old worlds will be broken in any case. Maybe we can add a special tag for converted PROTOs? The tag would need to have information about a rotation we made.

2021-09-17 07:00 UTC, lukicdarkoo commented
The tests are passing locally, the Windows error seems not to be related to the PR.

Keep in mind in mind there are probably a lot of edge cases that are not covered. However, I will believe it will significantly improve the user experience (see the examples in the original comment).

2021-09-17 14:48 UTC, omichel requested changes
Although, I didn't yet fully tested, it looks good to me.
There is a series of apparently unrelated files committed here however.

2021-09-17 15:00 UTC, lukicdarkoo commented on src/webots/gui/WbDragTransformEvent.cpp
> +                                   mViewpoint->orientation()->value(), mViewDistanceUnscaling);
It fixes the new object rotation, I can make a separate PR (it was just convenient to discover and implement small UX improvements).

2021-09-17 15:01 UTC, lukicdarkoo commented on src/webots/wren/WbTranslateRotateManipulator.cpp
> +              maxDimension = height > width ? height : width, arrowScaleFactor = (arrowScale * 2.0f / maxDimension) * 10.0f;
Also related to the object rotation

2021-09-17 15:03 UTC, omichel commented on src/webots/gui/WbDragTransformEvent.cpp
> +                                   mViewpoint->orientation()->value(), mViewDistanceUnscaling);
OK, no need to make a separate PR, that's fine.

2021-09-22 06:46 UTC, merged