convert last objects to FLU
cyberbotics/webots pull request #3647
Opened 2021-09-07 09:14 UTC by joachimhgg

- [ ] (132) objects/robotstadium/protos/RobotstadiumSoccerField.proto
- [ ] (133) objects/robotstadium/protos/RobotstadiumGoal.proto
- [ ] (134) objects/lego/protos/LegoLargeMotor.proto
- [ ] (135) objects/lego/protos/LegoWheel.proto
- [ ] (136) objects/create_wall/protos/CreateWall.proto
- [ ] (190) objects/backgrounds/protos/TexturedBackgroundLight.proto
- [ ] (191) objects/backgrounds/protos/TexturedBackground.proto
- [ ] (195) objects/freight/protos/IntermodalOfficeContainer.proto
- [ ] (196) objects/freight/protos/IntermodalContainer.proto
- [ ] (261) objects/lights/protos/DoubleFluorescentLamp.proto
- [ ] (262) objects/lights/protos/ConstructionLamp.proto
- [ ] (263) objects/lights/protos/CeilingSpotLight.proto
- [ ] (264) objects/lights/protos/CeilingLight.proto
- [ ] (265) objects/lights/protos/FloorLight.proto
- [ ] (266) objects/floors/protos/CircleArena.proto
- [ ] (270) objects/telephone/protos/OfficeTelephone.proto
- [ ] (271) objects/telephone/protos/Telephone.proto
- [ ] (282) objects/gear/protos/Gear.proto

2021-09-08 12:56 UTC, BenjaminDeleze commented on projects/objects/lego/protos/LegoWheel.proto
>          geometry IndexedFaceSet {
The translation at line 7 need to be converted

2021-09-08 12:56 UTC, BenjaminDeleze commented on projects/objects/freight/protos/IntermodalOfficeContainer.proto
> +#VRML_SIM R2021b utf8
```suggestion
#VRML_SIM R2021c utf8
```

2021-09-08 12:56 UTC, BenjaminDeleze commented on projects/objects/freight/protos/IntermodalOfficeContainer.proto
> +  field SFRotation rotation       0 1 0 0      # Is `Transform.rotation`.
```suggestion
  field SFRotation rotation       0 0 1 0      # Is `Transform.rotation`.
```

2021-09-08 12:56 UTC, BenjaminDeleze commented on projects/objects/freight/protos/IntermodalOfficeContainer.proto
> +          size 12.192 2.438 2.6
```suggestion
          size 12.192 2.438 2.6
```

2021-09-08 12:56 UTC, BenjaminDeleze commented on projects/objects/lights/protos/ConstructionLamp.proto
>        }
The SpotLight need to be converted (View ->Optional Rendering -> Show light position can help)

2021-09-08 12:56 UTC, BenjaminDeleze commented on projects/objects/lights/protos/CeilingLight.proto
>  # A ceiling light (0.19 x 0.8 x 0.19 m).
```suggestion
# A ceiling light (0.19 x 0.19 x 0.8 m).
```

2021-09-08 12:56 UTC, BenjaminDeleze commented on projects/objects/lights/protos/FloorLight.proto
>    rotation IS rotation
The description, line 4, need to be updated

2021-09-08 12:56 UTC, BenjaminDeleze commented on projects/objects/floors/protos/CircleArena.proto
>            coord Coordinate {
The translation at line 78 need to be changed

2021-09-08 12:56 UTC, BenjaminDeleze commented on projects/objects/telephone/protos/OfficeTelephone.proto
> +#VRML_SIM R2021b utf8
```suggestion
#VRML_SIM R2021c utf8
```

2021-09-08 12:56 UTC, BenjaminDeleze commented on projects/objects/telephone/protos/OfficeTelephone.proto
> +  field SFRotation rotation       0 1 0 0
```suggestion
  field SFRotation rotation       0 0 1 0
```

2021-09-08 12:56 UTC, BenjaminDeleze commented on projects/objects/gear/protos/Gear.proto
>                    # base face
Something seems wrong, the gear is flat

2021-09-09 06:57 UTC, BenjaminDeleze requested changes
Thank you, all comments have been addressed.

However, the gear seems still wrong (the texture is 'inside')

2021-09-09 06:57 UTC, BenjaminDeleze commented on projects/objects/lego/protos/LegoWheel.proto
> +  field SFVec3f    translation 0 0 -0.9780026
```suggestion
  field SFVec3f    translation 0 0 0.0219974
```

2021-09-10 14:45 UTC, BenjaminDeleze requested changes
Thank you, the gear looks nicer now.
However the bounding object with the option `teethBoundingObject` is wrong 
and the axis of the gear should be align with x (it is currently align with z)

2021-09-13 14:30 UTC, BenjaminDeleze requested changes
It is better, but I managed to break the `teethBoundingObject` by putting the `toothDepth` to 0.03 or the `pitchRadius` to 0.05.

2021-09-15 09:24 UTC, ad-daniel commented
- I believe the `IntermodalOfficeContainer` was backwards (i.e the door wasn't on the front as is the case for all buildings), so I fixed that and since I was on it I've collapsed all transforms (`IntermodalContainer` included).
- Fixed  the gear.
- The Cylinders/Capsules/Plane of `RobocupStadium` appear to be have been forgotten (probably because it's a PROTO that was already FLU), so I added it to this PR

2021-09-15 14:50 UTC, BenjaminDeleze approved these changes
Thank you!

2021-09-15 14:54 UTC, merged