Feature flu pedestrian
cyberbotics/webots pull request #3650
Opened 2021-09-08 08:07 UTC by joachimhgg

- [x] (322) humans/pedestrian/protos/PedestrianRightHand.proto
- [x] (323) humans/pedestrian/protos/PedestrianLeftFoot.proto
- [x] (324) humans/pedestrian/protos/PedestrianLeftUpperLeg.proto
- [x] (325) humans/pedestrian/protos/PedestrianNeck.proto
- [x] (326) humans/pedestrian/protos/PedestrianLeftHand.proto
- [x] (327) humans/pedestrian/protos/PedestrianLeftUpperArm.proto
- [x] (328) humans/pedestrian/protos/PedestrianTorso.proto
- [x] (329) humans/pedestrian/protos/Pedestrian.proto
- [x] (330) humans/pedestrian/protos/PedestrianRightLowerArm.proto
- [x] (331) humans/pedestrian/protos/PedestrianRightUpperLeg.proto
- [x] (332) humans/pedestrian/protos/PedestrianRightFoot.proto
- [x] (333) humans/pedestrian/protos/PedestrianLeftLowerArm.proto
- [x] (334) humans/pedestrian/protos/PedestrianRightLowerLeg.proto
- [x] (335) humans/pedestrian/protos/PedestrianHead.proto
- [x] (336) humans/pedestrian/protos/PedestrianRightUpperArm.proto
- [x] (337) humans/pedestrian/protos/PedestrianLeftLowerLeg.proto

2021-09-08 09:29 UTC, lukicdarkoo commented
We recently discussed and a rule for converting robots is slightly different. All worlds in which the pedestrian (or any other robot we are converting) is used have to be converted to ENU. I forgot to mention it in the main PR.

That way, we demonstrate that the conversion is successful.

2021-09-17 08:28 UTC, lukicdarkoo requested changes
Looks good, just a few minor comments

2021-09-17 08:28 UTC, lukicdarkoo commented on projects/humans/pedestrian/protos/Pedestrian.proto
> +  field       SFVec3f    translation           0 0 1.27
This should be also changed in `docs/guide/humans.md`

2021-09-17 08:28 UTC, lukicdarkoo commented on projects/humans/pedestrian/worlds/pedestrian.wbt
> +  rotation 0 0 1 1.5708003061004252
```suggestion
```
Do we need this?

2021-10-01 09:19 UTC, omichel approved these changes
Thank you.

2021-10-01 10:14 UTC, merged