Feature FLU: Aibo Bioloid Qrio
cyberbotics/webots pull request #3700
Opened 2021-09-17 11:28 UTC by BenjaminDeleze

**Description**

### Robots
- [x] Aibo
- [ ] Bioloid
- [ ] Qrio

### Worlds

2021-09-22 14:12 UTC, lukicdarkoo requested changes
Looks good except:
- `QRIO.proto`: x-axis is not forward.
- `aibo_ers7.wbt` and `qrio.wbt` worlds were not checked in #3073 (I have just checked them).

2021-09-22 14:14 UTC, lukicdarkoo commented on projects/robots/sony/qrio/protos/QRIO.proto
> +  field SFVec3f    translation     0 0 0.42   # Is `Transform.translation`.
Not aligned

2021-09-22 14:15 UTC, lukicdarkoo commented on projects/robots/sony/qrio/protos/QRIO.proto
> +  field SFVec3f    translation     0 0 0.42   # Is `Transform.translation`.
Also, it should be changed in `qrio.md` as well

2021-09-23 06:42 UTC, BenjaminDeleze commented
I think I addressed all coments

2021-09-23 07:25 UTC, lukicdarkoo commented on projects/robots/robotis/bioloid/protos/BioloidDog.proto
> +        translation 0 0 0
```suggestion
```
I missed a tiny detail :/

2021-09-23 08:05 UTC, lukicdarkoo approved these changes
Thank you!

2021-09-23 08:06 UTC, merged