FLU: Convert JetBot robot and JetsonNano device
cyberbotics/webots pull request #3702
Opened 2021-09-20 14:23 UTC by stefaniapedrazzi

Convert:

robots:
* [x] (699) robots/nvidia/jetbot/protos/JetBotRaspberryPiCamera.proto
* [x] (700) robots/nvidia/jetbot/protos/JetBot.proto

worlds:
* [x] (255) projects/robots/nvidia/jetbot/worlds/jetbot.wbt

and devices:
* [x] projects/devices/nvidia/protos/JetsonNano.proto

2021-09-20 15:13 UTC, stefaniapedrazzi commented
Windows test is failing because of Java and is not related to the changes in this PR.

2021-09-22 08:14 UTC, stefaniapedrazzi commented
> Looks good! I have only one remark: the default rotation of the RaspberryPiCamera in the cameraSlot of the JetBot.proto seems wrong.

Not sure to understand what do you mean.
Do you refer to this line?
https://github.com/cyberbotics/webots/blob/d074158a2d161a879f3de837db607e746d032f98/projects/robots/nvidia/jetbot/worlds/jetbot.wbt#L261

To me it seems correct, both the object appearance and Camera image are oriented correctly.

The only thing is that effectively this object is not FLU (I will fix it) but this has nothing to do with the orientation in the `cameraSlot`.

2021-09-22 08:56 UTC, BenjaminDeleze commented
> Do you refer to this line?

No to this one https://github.com/cyberbotics/webots/blob/d074158a2d161a879f3de837db607e746d032f98/projects/robots/nvidia/jetbot/protos/JetBot.proto#L22

2021-09-22 09:30 UTC, stefaniapedrazzi commented
I also found errors in the `SolidRoundedBox` PROTO that is used in the JetBot robot.
This PROTO is also used in the a couple of `samples/devices` worlds that are not been yet converted and in these two worlds that are markes as converted but it seems they are still being processed:
* `projects/samples/environments/factory/worlds/hall.wbt` (I could not find the corresponding PR)
* `projects/samples/environments/factory/worlds/extended_solids.wbt` (see https://github.com/cyberbotics/webots/pull/3664, not merged)

2021-09-22 10:34 UTC, BenjaminDeleze requested changes
Thank you!
just one small thing:

2021-09-22 10:34 UTC, BenjaminDeleze commented on projects/objects/solids/protos/SolidRoundedBox.proto
> +    console.error('\'innerSize\'' + innerSize.x + ' '  + innerSize.y + ' '  + innerSize.z);
```suggestion
```
I think this is a debug log

2021-09-22 10:41 UTC, stefaniapedrazzi commented on projects/objects/solids/protos/SolidRoundedBox.proto
> +    console.error('\'innerSize\'' + innerSize.x + ' '  + innerSize.y + ' '  + innerSize.z);
Thank you!

2021-09-22 10:42 UTC, BenjaminDeleze approved these changes
Thank you!

2021-09-22 12:10 UTC, merged