Attempt to fix VM detection on Windows
cyberbotics/webots pull request #3744
Opened 2021-10-04 13:12 UTC by omichel

Might fix #3738.

2021-10-04 13:20 UTC, llessieux commented
I'll check that as soon as I can.

2021-10-04 13:43 UTC, llessieux commented
By the way, I have a fix for the Windows 11 detection too if you want. Same file.
It is just an extra build number check to switch between Windows 10 and 11.

2021-10-04 13:57 UTC, llessieux requested changes

2021-10-04 13:57 UTC, llessieux commented on src/webots/core/WbSysInfo.cpp
>      virtualMachine = 1;
I think that the virtualMachine should be set to 0 in this case.

2021-10-04 14:08 UTC, llessieux commented
That's the change I have tested for the Windows 11 detection.

    case QSysInfo::WV_WINDOWS10:  // Or Windows 11
    {
      QString version("Windows 10");
      QString kernel_version = QSysInfo::kernelVersion();
      QRegExp rx("[.]");
      QStringList list = kernel_version.split(rx, Qt::SkipEmptyParts);
      if (list.size() == 3) {
        int build_number = list[2].toInt();
        if (build_number >= 2200) {
          version = "Windows 11";
        }
      }
      sysInfo.append(version);
      break;

2021-10-04 14:17 UTC, omichel commented
That looks good. May I ask you to commit it in there?

2021-10-04 14:24 UTC, llessieux commented
> 
> 
> That looks good. May I ask you to commit it in there?

Sure. But that will have to wait until tomorrow ;) Getting late here :)

Ok I can confirm that your fix seems to be working here.

2021-10-05 14:16 UTC, llessieux commented
Ok Windows 11 detection added.

2021-10-05 14:56 UTC, omichel commented
It doesn't work quite well as on my Windows 10 machine, it says "Windows 11". The list returned in `kernelVersion` is `("10", "0", "19043")` on my machine, which obviously leads to "Windows 11".

2021-10-06 11:02 UTC, llessieux commented
I think that there is a zero missing :) It should be 22000.

2021-10-06 11:05 UTC, llessieux commented
You can check it also by looking at the version number of NtosKernel.exe in C:\Windows\System32.

2021-10-06 12:14 UTC, llessieux approved these changes

2021-10-06 13:55 UTC, merged