Add rolling friction to contact properties
cyberbotics/webots pull request #3771
Opened 2021-10-12 15:44 UTC by ad-daniel

**Description**

Fixes: https://github.com/cyberbotics/webots/issues/2086

This PR introduces rolling friction (ODE's rho, rho2, rhoN).

https://user-images.githubusercontent.com/44834743/144199204-9837b7a0-c353-4c7c-866c-5ff9f044dfce.mp4

2021-12-03 16:43 UTC, ad-daniel commented
The PR was already ready for review, it was waiting for `feature-enu-plan` to be merged into develop. The PR only required changing the viewpoint and fixing the geometry of the cylinder. I tested it locally on Linux and it seems ENU/FLU had no effect on rolling friction, it continues working as intended.

2021-12-06 13:35 UTC, omichel requested changes
Thank you. It looks good to me, only a couple of minor things.

2021-12-06 13:35 UTC, omichel commented on docs/reference/contactproperties.md
> +The field can have up to three coefficients, using ODE's nomenclature they are [rho, rho2, rhoN].
These coefficients are mandatory even they are set to 0 or -1.
```suggestion
The field holds three coefficients, using ODE's nomenclature they are [rho, rho2, rhoN].
```

2021-12-06 13:35 UTC, omichel commented on docs/reference/contactproperties.md
> +The field accepts only positive values or -1.0, where -1.0 corresponds to infinity.
```suggestion
Each coefficient accepts only positive values or -1.0, where -1.0 corresponds to infinity.
```

2021-12-06 13:35 UTC, omichel commented on docs/reference/contactproperties.md
> +WEBOTS\_HOME/projects/sample/howto/rolling\_friction/worlds/rolling\_friction.wbt illustrates the effect of the different coefficients.
A hyperlink to the GitHub file would be welcome here (see other places in the documentation where this is done).

2021-12-06 13:35 UTC, omichel commented on tests/physics/controllers/rolling_friction_supervisor/rolling_friction_supervisor.c
> +  WbNodeRef ball_nodes[9];
Instead of hard-coding 9 everywhere, we could define it as a constant along the TIME_STEP value:

```C
#define BALL_COUNT 9
```

2021-12-06 15:16 UTC, ad-daniel commented
I've fixed as suggested, since there were other cited samples in the same page I've also turned those into hyperlinks.

2021-12-06 15:33 UTC, omichel requested changes
I believe that in English we should rather say "the test.wbt world" rather "the world test.wbt"

2021-12-06 15:33 UTC, omichel commented on docs/reference/contactproperties.md
> +The world [asymmetric\_friction1.wbt](../guide/samples-howto.md#asymmetric_friction1-wbt) contains an example of fully asymmetric friction.
We rather use this style although both styles are probably correct:
```suggestion
The [asymmetric\_friction1.wbt](../guide/samples-howto.md#asymmetric_friction1-wbt) world contains an example of fully asymmetric friction.
```
(see other occurrences below)

*Note*: "the readme.txt file" has 1.2M hits in google search while "the file readme.txt" has only 88k.

2021-12-06 16:40 UTC, omichel approved these changes

2021-12-06 19:25 UTC, omichel approved these changes

2021-12-06 20:05 UTC, merged