Feature flu various robots
cyberbotics/webots pull request #3807
Opened 2021-10-21 12:36 UTC by joachimhgg

**Protos**

- [x] (749) robots/neuronics/ipr/protos/IprHd6ms90.proto
- [x] (750) robots/neuronics/ipr/protos/IprHd6m90.proto
- [x] (751) robots/neuronics/ipr/protos/IprHd6m180.proto
- [x] (752) robots/neuronics/ipr/protos/IprHd6ms180.proto

**Worlds**

- [x] (224) projects/robots/fp_robotics/p-rob3/worlds/p-rob3.wbt
- [x] (245) projects/robots/robotcub/icub/worlds/icub_stand.wbt
- [x] (002) scripts/icon_studio/worlds/icon_studio.wbt and objects.json
- [x] (268) projects/robots/micromagic/scout/worlds/scout.wbt
- [x]  (299) projects/robots/neuronics/ipr/worlds/ipr_factory.wbt
- [x] (300) projects/robots/neuronics/ipr/worlds/ipr_cube.wbt
- [x] (301) projects/robots/neuronics/ipr/worlds/ipr_collaboration.wbt
- [x] (302) projects/robots/neuronics/ipr/worlds/ipr_models.wbt

2021-11-02 16:35 UTC, ad-daniel requested changes
Mostly minor stuff, thank you

2021-11-02 16:35 UTC, ad-daniel commented on scripts/icon_studio/controllers/icon_creator/objects.json
> +    "background": [
Forest has a bug, likely an issue with the PROTO itself.
![a](https://user-images.githubusercontent.com/44834743/139904647-05d6709d-fe6e-4a48-91b3-8ee1be1a24db.png)

2021-11-02 16:35 UTC, ad-daniel commented on scripts/icon_studio/controllers/icon_creator/objects.json
> +    "fields": "  translation 0 0 -0.211 rotation 0.6785976608971787 -0.2810890310957679 -0.6785972083810249 -2.59356",
this object should have a proper (monotone color) background like everything else

2021-11-02 16:35 UTC, ad-daniel commented on scripts/icon_studio/controllers/icon_creator/objects.json
> +    "fields": "  rotation 0.11178796221525046 -0.1471636664273077 0.9827747996298206 1.6477654786391709",
Tiago robot is backwards

2021-11-02 16:35 UTC, ad-daniel commented on scripts/icon_studio/controllers/icon_creator/objects.json
> +    "fields": "  rotation -0.04339021564602396 -0.1791348245106523 0.9828672361177421 1.6039571495576197",
Tiago base is half-clipped into the ground

2021-11-02 16:35 UTC, ad-daniel commented on scripts/icon_studio/controllers/icon_creator/objects.json
> +    "fields": "  rotation -0.7745939356506115 -0.4472169628474524 -0.4472149628476185 -1.8234853071795865",
this one too

2021-11-03 10:10 UTC, joachimhgg commented on scripts/icon_studio/controllers/icon_creator/objects.json
> +    "fields": "  translation 0.0370218 0.573555 -1.028 rotation -1.3505393835251057e-16 1.2211986311439658e-16 -1.0 1.96308 controller \"void\"",
It is not failing when testing with a small dataset. I put in in the end of the json file.

2021-11-03 10:16 UTC, joachimhgg commented
You can test the fixes by adding this code in your `objects.json`: 
```
{
  "default": {
    "colorThreshold": 0.01,
    "background": [1.0, 1.0, 1.0],
    "fields": "rotation 0 1 0 0.3",
    "nodeString": ""
  },  
  "projects/robots/pal_robotics/tiago_base/protos/TiagoBase.proto": {
    "nodeString": "  TiagoBase{ rotation 0 0 -1 1.57 }"
  },
  "projects/vehicles/protos/mercedes_benz/MercedesBenzSprinter.proto": {
    "nodeString": "  MercedesBenzSprinter{ rotation 0 0 1 3.14159 }"
  },
  "projects/vehicles/protos/mercedes_benz/MercedesBenzSprinterSimple.proto": {
    "nodeString": "  MercedesBenzSprinterSimple{ rotation 0 0 1 3.14159 }"
  },
  "projects/robots/boston_dynamics/spot/protos/Spot.proto": {
    "fields": "  translation 1.028 -0.0370218 0.573555 rotation 0 0 -1 1.96308 controller \"void\"",
    "nodeString": "  Spot{ translation 1.028 -0.0370218 0.573555 rotation 0 0 -1 1.96308 controller \"void\" }"
  },
  "projects/objects/balls/protos/Ball": {
    "fields": "   translation 0 0 0.0325 rotation 0.0 0.0 1.0 0.3",
    "nodeString": "     Ball{ translation 0 0 0.0325 rotation 0.0 0.0 1.0 0.3 }"
  },
  "projects/objects/balls/protos/SoccerBall": {
    "fields": "   translation 0 0 0.113 rotation 0.0 0.0 1.0 0.3",
    "nodeString": "     SoccerBall{ translation 0 0 0.113 rotation 0.0 0.0 1.0 0.3 }"
  },
  "projects/objects/geometries/protos/TexturedParallelepiped": {
    "fields": "   rotation 0.0 0.364549 0.931184 -0.561795",
    "nodeString": "   Transform { translation 0 0 0.06 rotation 0.0 0.364549 0.931184 -0.561795  children [ Shape { appearance Appearance { material Material { } texture ImageTexture { url [ \"textures/tagged_wall.jpg\" ] } } geometry TexturedParallelepiped { } } ] }"
  },
  "projects/objects/road/protos/LaneSeparation": {
    "fields": "   translation 0 0 0.01 rotation 0.0 0.0 1.0 1.5708 length 19",
    "nodeString": "   LaneSeparation{ translation 0 0 0.01 rotation 0.0 0.0 1.0 1.5708 length 19 }"
  },
  "projects/objects/road/protos/RoadLine": {
    "fields": "  translation 0 0.5 0.03 rotation 0.0 0.0 1.0 1.57",
    "nodeString": "    Road { translation 0 0.5 0.03 rotation 0.0 0.0 1.0 1.57 width 16 numberOfLanes 4 wayPoints [ 0 0 0 -20.0 -10.0 0 -50.0 10.0 0 ] lines [ RoadLine { type \"dashed\" } RoadLine { type \"continuous\" } RoadLine { type \"double\" color 1 1 0 } ] splineSubdivision 6 } "
  },
  "projects/robots/festo/robotino3/protos/Robotino3WebcamMountingSupport.proto": {
    "fields": "   translation 0 0 0.211 rotation 0.6785976608971788 -0.28108903109576794 -0.678597208381025 -2.59356",
    "nodeString": "   Robotino3WebcamMountingSupport{ translation 0 0 0.211 rotation 0.6785976608971788 -0.28108903109576794 -0.678597208381025 -2.59356 }"
  },
  "projects/robots/kinematics/tinkerbots/protos/TinkerbotsPivot": {
    "background": [
      1.0,
      1.0,
      1.0
    ],
    "colorThreshold": 0.001,
    "fields": " rotation 0 0 -1 0.261803",
    "nodeString": " Robot { rotation 0 0 -1 0.261803 children [ Slot { endPoint TinkerbotsPivot { } } ] }"
  },
  "projects/robots/pal_robotics/tiago++/protos/Tiago++.proto": {
    "fields": "  rotation -0.230732 -0.109357 0.966852 -1.27752",
    "nodeString": "  Tiago++{ rotation -0.230732 -0.109357 0.966852 -1.27752 }"
  }
}
```

2021-11-03 13:32 UTC, ad-daniel commented
Very good, only 2 details remaining:

- forest on icon studio still showing up wrong

Issue coming from the other (previous) PR:
- when I load `visual_tracking.wbt` I get these errors:
```
WARNING: DEF YELLOW_CAR Transform > Transform > Group > DEF SIDE_RIGHT_INDICATOR Shape > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/feature-flu-sample-default-robots/projects/vehicles/protos/textures/indicator.jpg: Error opening https://raw.githubusercontent.com/cyberbotics/webots/feature-flu-sample-default-robots/projects/vehicles/protos/textures/indicator.jpg
WARNING: DEF YELLOW_CAR Transform > Transform > DEF FOGLIGHT Transform > DEF FRONT_FOGLIGHT Shape > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/feature-flu-sample-default-robots/projects/vehicles/protos/textures/antifog.jpg: Error opening https://raw.githubusercontent.com/cyberbotics/webots/feature-flu-sample-default-robots/projects/vehicles/protos/textures/antifog.jpg
WARNING: DEF YELLOW_CAR Transform > Transform > Group > DEF COACHWORK Shape > DEF VEHICLE_APP PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/feature-flu-sample-default-robots/projects/appearances/protos/textures/matte_car_paint/matte_car_paint_base_color.jpg: Error opening https://raw.githubusercontent.com/cyberbotics/webots/feature-flu-sample-default-robots/projects/appearances/protos/textures/matte_car_paint/matte_car_paint_base_color.jpg
WARNING: DEF YELLOW_CAR Transform > Transform > Group > DEF COACHWORK Shape > DEF VEHICLE_APP PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/feature-flu-sample-default-robots/projects/appearances/protos/textures/glossy_car_paint/glossy_car_paint_roughness.jpg: Error opening https://raw.githubusercontent.com/cyberbotics/webots/feature-flu-sample-default-robots/projects/appearances/protos/textures/glossy_car_paint/glossy_car_paint_roughness.jpg
WARNING: DEF YELLOW_CAR Transform > Transform > Group > DEF COACHWORK Shape > DEF VEHICLE_APP PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/feature-flu-sample-default-robots/projects/appearances/protos/textures/glossy_car_paint/glossy_car_paint_normal.jpg: Error opening https://raw.githubusercontent.com/cyberbotics/webots/feature-flu-sample-default-robots/projects/appearances/protos/textures/glossy_car_paint/glossy_car_paint_normal.jpg
WARNING: DEF YELLOW_CAR Transform > Transform > Group > DEF FRONT_PLATE Transform > Shape > DEF PLATE_APPEARANCE PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/feature-flu-sample-default-robots/projects/vehicles/protos/textures/plate.jpg: Error opening https://raw.githubusercontent.com/cyberbotics/webots/feature-flu-sample-default-robots/projects/vehicles/protos/textures/plate.jpg
WARNING: DEF YELLOW_CAR Transform > Transform > Group > DEF REAR_LOGO Transform > Shape > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/feature-flu-sample-default-robots/projects/vehicles/protos/citroen/textures/citroen_logo_base_color.png: Error opening https://raw.githubusercontent.com/cyberbotics/webots/feature-flu-sample-default-robots/projects/vehicles/protos/citroen/textures/citroen_logo_base_color.png
WARNING: DEF YELLOW_CAR Transform > Transform > Group > DEF REAR_LOGO Transform > Shape > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/feature-flu-sample-default-robots/projects/vehicles/protos/citroen/textures/citroen_logo_normal.jpg: Error opening https://raw.githubusercontent.com/cyberbotics/webots/feature-flu-sample-default-robots/projects/vehicles/protos/citroen/textures/citroen_logo_normal.jpg
WARNING: DEF YELLOW_CAR Transform > DEF FRONT_RIGHT_WHEEL Solid > Slot > Slot > Solid > Transform > DEF TIRE Shape > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/feature-flu-sample-default-robots/projects/vehicles/protos/abstract/textures/tire_texture_base_color.jpg: Error opening https://raw.githubusercontent.com/cyberbotics/webots/feature-flu-sample-default-robots/projects/vehicles/protos/abstract/textures/tire_texture_base_color.jpg
WARNING: DEF YELLOW_CAR Transform > DEF FRONT_RIGHT_WHEEL Solid > Slot > Slot > Solid > Transform > DEF TIRE Shape > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/feature-flu-sample-default-robots/projects/vehicles/protos/abstract/textures/tire_texture_roughness.jpg: Error opening https://raw.githubusercontent.com/cyberbotics/webots/feature-flu-sample-default-robots/projects/vehicles/protos/abstract/textures/tire_texture_roughness.jpg
WARNING: DEF YELLOW_CAR Transform > DEF FRONT_RIGHT_WHEEL Solid > Slot > Slot > Solid > Transform > DEF TIRE Shape > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/feature-flu-sample-default-robots/projects/vehicles/protos/abstract/textures/tire_texture_normal.jpg: Error opening https://raw.githubusercontent.com/cyberbotics/webots/feature-flu-sample-default-robots/projects/vehicles/protos/abstract/textures/tire_texture_normal.jpg
WARNING: DEF YELLOW_CAR Transform > DEF FRONT_RIGHT_WHEEL Solid > Slot > Slot > Solid > Transform > DEF TIRE Shape > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/feature-flu-sample-default-robots/projects/vehicles/protos/abstract/textures/tire_texture_occlusion.jpg: Error opening https://raw.githubusercontent.com/cyberbotics/webots/feature-flu-sample-default-robots/projects/vehicles/protos/abstract/textures/tire_texture_occlusion.jpg
WARNING: DEF BUS Transform > Transform > Group > DEF COACHWORK Shape > DEF APPEARANCE PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/feature-flu-sample-default-robots/projects/appearances/protos/textures/matte_car_paint/matte_car_paint_roughness.jpg: Error opening https://raw.githubusercontent.com/cyberbotics/webots/feature-flu-sample-default-robots/projects/appearances/protos/textures/matte_car_paint/matte_car_paint_roughness.jpg
```
the urls should be something like: `webots:// ...`. They were probably changed manually to test something.

2021-11-03 14:22 UTC, joachimhgg commented
> Very good, only 2 details remaining:
> 
>     * forest on icon studio still showing up wrong
> 
> 
> Issue coming from the other (previous) PR:
> 
>     * when I load `visual_tracking.wbt` I get these errors:
> 
> 
> ```
> WARNING: DEF YELLOW_CAR Transform > Transform > Group > DEF SIDE_RIGHT_INDICATOR Shape > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/feature-flu-sample-default-robots/projects/vehicles/protos/textures/indicator.jpg: Error opening https://raw.githubusercontent.com/cyberbotics/webots/feature-flu-sample-default-robots/projects/vehicles/protos/textures/indicator.jpg
> WARNING: DEF YELLOW_CAR Transform > Transform > DEF FOGLIGHT Transform > DEF FRONT_FOGLIGHT Shape > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/feature-flu-sample-default-robots/projects/vehicles/protos/textures/antifog.jpg: Error opening https://raw.githubusercontent.com/cyberbotics/webots/feature-flu-sample-default-robots/projects/vehicles/protos/textures/antifog.jpg
> WARNING: DEF YELLOW_CAR Transform > Transform > Group > DEF COACHWORK Shape > DEF VEHICLE_APP PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/feature-flu-sample-default-robots/projects/appearances/protos/textures/matte_car_paint/matte_car_paint_base_color.jpg: Error opening https://raw.githubusercontent.com/cyberbotics/webots/feature-flu-sample-default-robots/projects/appearances/protos/textures/matte_car_paint/matte_car_paint_base_color.jpg
> WARNING: DEF YELLOW_CAR Transform > Transform > Group > DEF COACHWORK Shape > DEF VEHICLE_APP PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/feature-flu-sample-default-robots/projects/appearances/protos/textures/glossy_car_paint/glossy_car_paint_roughness.jpg: Error opening https://raw.githubusercontent.com/cyberbotics/webots/feature-flu-sample-default-robots/projects/appearances/protos/textures/glossy_car_paint/glossy_car_paint_roughness.jpg
> WARNING: DEF YELLOW_CAR Transform > Transform > Group > DEF COACHWORK Shape > DEF VEHICLE_APP PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/feature-flu-sample-default-robots/projects/appearances/protos/textures/glossy_car_paint/glossy_car_paint_normal.jpg: Error opening https://raw.githubusercontent.com/cyberbotics/webots/feature-flu-sample-default-robots/projects/appearances/protos/textures/glossy_car_paint/glossy_car_paint_normal.jpg
> WARNING: DEF YELLOW_CAR Transform > Transform > Group > DEF FRONT_PLATE Transform > Shape > DEF PLATE_APPEARANCE PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/feature-flu-sample-default-robots/projects/vehicles/protos/textures/plate.jpg: Error opening https://raw.githubusercontent.com/cyberbotics/webots/feature-flu-sample-default-robots/projects/vehicles/protos/textures/plate.jpg
> WARNING: DEF YELLOW_CAR Transform > Transform > Group > DEF REAR_LOGO Transform > Shape > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/feature-flu-sample-default-robots/projects/vehicles/protos/citroen/textures/citroen_logo_base_color.png: Error opening https://raw.githubusercontent.com/cyberbotics/webots/feature-flu-sample-default-robots/projects/vehicles/protos/citroen/textures/citroen_logo_base_color.png
> WARNING: DEF YELLOW_CAR Transform > Transform > Group > DEF REAR_LOGO Transform > Shape > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/feature-flu-sample-default-robots/projects/vehicles/protos/citroen/textures/citroen_logo_normal.jpg: Error opening https://raw.githubusercontent.com/cyberbotics/webots/feature-flu-sample-default-robots/projects/vehicles/protos/citroen/textures/citroen_logo_normal.jpg
> WARNING: DEF YELLOW_CAR Transform > DEF FRONT_RIGHT_WHEEL Solid > Slot > Slot > Solid > Transform > DEF TIRE Shape > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/feature-flu-sample-default-robots/projects/vehicles/protos/abstract/textures/tire_texture_base_color.jpg: Error opening https://raw.githubusercontent.com/cyberbotics/webots/feature-flu-sample-default-robots/projects/vehicles/protos/abstract/textures/tire_texture_base_color.jpg
> WARNING: DEF YELLOW_CAR Transform > DEF FRONT_RIGHT_WHEEL Solid > Slot > Slot > Solid > Transform > DEF TIRE Shape > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/feature-flu-sample-default-robots/projects/vehicles/protos/abstract/textures/tire_texture_roughness.jpg: Error opening https://raw.githubusercontent.com/cyberbotics/webots/feature-flu-sample-default-robots/projects/vehicles/protos/abstract/textures/tire_texture_roughness.jpg
> WARNING: DEF YELLOW_CAR Transform > DEF FRONT_RIGHT_WHEEL Solid > Slot > Slot > Solid > Transform > DEF TIRE Shape > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/feature-flu-sample-default-robots/projects/vehicles/protos/abstract/textures/tire_texture_normal.jpg: Error opening https://raw.githubusercontent.com/cyberbotics/webots/feature-flu-sample-default-robots/projects/vehicles/protos/abstract/textures/tire_texture_normal.jpg
> WARNING: DEF YELLOW_CAR Transform > DEF FRONT_RIGHT_WHEEL Solid > Slot > Slot > Solid > Transform > DEF TIRE Shape > PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/feature-flu-sample-default-robots/projects/vehicles/protos/abstract/textures/tire_texture_occlusion.jpg: Error opening https://raw.githubusercontent.com/cyberbotics/webots/feature-flu-sample-default-robots/projects/vehicles/protos/abstract/textures/tire_texture_occlusion.jpg
> WARNING: DEF BUS Transform > Transform > Group > DEF COACHWORK Shape > DEF APPEARANCE PBRAppearance > ImageTexture: Cannot download https://raw.githubusercontent.com/cyberbotics/webots/feature-flu-sample-default-robots/projects/appearances/protos/textures/matte_car_paint/matte_car_paint_roughness.jpg: Error opening https://raw.githubusercontent.com/cyberbotics/webots/feature-flu-sample-default-robots/projects/appearances/protos/textures/matte_car_paint/matte_car_paint_roughness.jpg
> ```
> 
> the urls should be something like: `webots:// ...`. They were probably changed manually to test something.

Forest.proto has been fixed in #3768. I changed the image links, It should be fixed now. thanks!

2021-11-03 14:32 UTC, ad-daniel approved these changes
Thank you!

2021-11-04 07:30 UTC, merged