Add supervisor tutorial
cyberbotics/webots pull request #3882
Opened 2021-11-11 15:39 UTC by ad-daniel

**Description**
Add basic tutorial for the usage of a supervisor

preview: https://www.cyberbotics.com/doc/guide/tutorial-8-the-supervisor?version=feature-supervisor-tutorial

2021-11-12 15:14 UTC, BenjaminDeleze requested changes
It seems very good and useful to me! Maybe @omichel could read it to review the English style as I am quite bad at it.

It would maybe be better to do the tutorial directly in ENU/FLU ?

It may be useful to add a warning regarding the physic instabilities that can be caused by using the Supervisor to move objects.

2021-11-12 15:14 UTC, BenjaminDeleze commented on docs/guide/tutorial-8-the-supervisor.md
> +7. In the `appearance` field add a [PBRAppearance](../reference/solid.md) node and set its `baseColor` field to red (`0 1 0`)
```suggestion
7. In the `appearance` field add a [PBRAppearance](../reference/solid.md) node and set its `baseColor` field to green (`0 1 0`)
```

2021-11-12 16:10 UTC, omichel requested changes
The English looks very good to me.
I just have have a minor suggestion.

2021-11-12 16:12 UTC, ad-daniel commented
The problem with doing it with ENU is that it won't touch released branch until December. I was planning on just doing the changes in the `feature-enu-branch` next week when we synchronize the branches, I've kept it simple enough that it will just take a few changes when merging. Being a new file, there won't be any conflicts. What do you think?

2021-11-12 16:13 UTC, omichel commented
> What do you think?

Sounds good to me.

2021-11-12 16:26 UTC, BenjaminDeleze approved these changes
Thank you!

2021-11-15 09:40 UTC, omichel approved these changes
I tested the Matlab controller and it works fine.
Thank you.

2021-11-15 09:41 UTC, BenjaminDeleze approved these changes

2021-11-15 11:11 UTC, merged