Improve web simulation
cyberbotics/webots pull request #3977
Opened 2021-12-06 14:59 UTC by omichel

The web simulation system currently has two shortcomings:

1. The URL scheme is unnecessarily complicated, we should drop the `webots://` URL in favor of a simple GitHub URL referring to a world file.
2. The simulation URL is not checked against an allowed/blocked list by the simulation server which basically expose the simulation server to any Webots simulation hosted on GitHub.

This PR addresses the following:
- [x] Remove remnants of Python 2 compatibility.
- [ ] Fix the URL scheme to make it simpler.
- [ ] Check the simulation URL against an allowed list.
- [ ] Remove the old `init` method used to load controllers in robotbenchmark.
- [x] Update the [documentation](https://cyberbotics.com/doc/guide/web-simulation?version=feature-improve-web-simulation).
- [x] Fixed [get_git_info.sh](https://github.com/cyberbotics/webots/blob/feature-enu-plan/scripts/get_git_info/get_git_info.sh) script which was not supporting URLs with `@` like `https://omichel@github.com/cyberbotics/webots.git`.

2022-01-18 08:47 UTC, BenjaminDeleze requested changes
Seems good, just some remarks:

It worked well on the given examples on beta.webots.cloud. But I did not managed to make the quick start work.

It would also be good to better document the risk of not using docker and how to mitigates them (whitelist)

2022-01-18 08:47 UTC, BenjaminDeleze commented on docs/guide/web-simulation.md
>  ```
Not updated

2022-01-18 16:15 UTC, BenjaminDeleze requested changes
The documentation is clearer now!

When running the quick start example, I went to the monitoring page of the session server
![local](https://user-images.githubusercontent.com/25938827/149973680-be28764e-f340-41df-bbf5-21796dc21dea.png)

If I click on the link of the simulation server, it redirect me to: `https://localhost/2000/monitor` which does not work. It should redirect to: `http://localhost:2000/monitor`.

Moreover, even so I can see my simulation server on `http://localhost:2000/monitor`, its load is still indicated as N/A in the session server monitoring page (as in the picture) and so I cannot open a simulation from index.html (`Session server error: No simulation server available at the moment.`)

2022-01-18 16:50 UTC, omichel commented
I re-tested and it works fine for me. Are you sure you are up-to-date with the latest changes? (`git fetch; git pull`)?

2022-01-19 07:03 UTC, BenjaminDeleze approved these changes
Retested this morning and it is all fine. 
Thank you!

2022-01-19 09:00 UTC, merged