Update-converter-nue-to-enu
cyberbotics/webots pull request #4012
Opened 2021-12-08 13:58 UTC by joachimhgg

**Description**

Fix road conversion , improve general robustness, improve description

2021-12-10 16:40 UTC, BenjaminDeleze requested changes
The script works really well in general but I saw some mistakes in the conversion for:
- [x] crossroads
- [x] plane and floor
- [x] stairs (in `spot.wbt`)
- [x] radiator, officeChair, cabinet, stairs (in `hall.wbt`)
- [ ] sofa (in `nao_room`)

The support for elevation_grid is missing.

I dont think everything need necessary to be fixed, it is something we can discuss...

I think it is important to explain in the wiki that it will only work for worlds that are in NUE. Worlds in ENU will be broken but I see no solution.

2021-12-13 07:54 UTC, joachimhgg commented on scripts/converter/convert_nue_to_enu_rub_to_flu.py
> +    filename_list = ['projects/robots/softbank/nao/protos/Nao.proto']
No, I am removing it.

2021-12-13 15:06 UTC, joachimhgg commented
> The script works really well in general but I saw some mistakes in the conversion for:
> 
>     * [x]  crossroads
> 
>     * [x]  plane and floor
> 
>     * [x]  stairs (in `spot.wbt`)
> 
>     * [x]  radiator, officeChair, cabinet, stairs (in `hall.wbt`)
> 
>     * [x]  sofa (in `nao_room`)
> 
> 
> The support for elevation_grid is missing.
> 
> I dont think everything need necessary to be fixed, it is something we can discuss...
> 
> I think it is important to explain in the wiki that it will only work for worlds that are in NUE. Worlds in ENU will be broken but I see no solution.

I fixed the crossroad, viewpoint and added objects into the lists. For the `ElevationGrid`, it is too much time to do it so let's wait if there is a need for it, maybe we could share your script as well.

2021-12-13 16:15 UTC, BenjaminDeleze approved these changes
Thank you!

2021-12-14 07:17 UTC, merged