Fix ratslife crash
cyberbotics/webots pull request #4027
Opened 2021-12-13 15:13 UTC by BenjaminDeleze

**Description**
The problem came from the fact that we were using the url to find the image in the `gImagesMap`. It is fine and handy to retrieve an image from a given url, but when we want to remove an image it does not work.

It does not work because the workflow goes as follow:

1. We/supervisor change the value of an url of a `imageTexture`.
2. The value of the url of the `imageTexture` is effectively changed.
3. A signal is emitted telling `imageTexture` that the url has changed.
4. `destroyWrenTexture` is called to clean the old image.
5. It was using the url to lookup the map. But the url was already the **new** url, so it was deleting the wrong image

Now it iterates through the images (an not through urls) when we want to delete an image.

Fix #3982

2021-12-13 16:56 UTC, omichel requested changes

2021-12-13 16:56 UTC, omichel commented on src/webots/nodes/WbImageTexture.cpp
> +      }
Coding style:
```suggestion
      } else
        gImagesMap[key] = std::make_pair(image, instances);
```

2021-12-13 16:56 UTC, omichel commented on src/webots/nodes/WbImageTexture.cpp
> +      QString key = i.key();
```suggestion
      const QString key = i.key();
```

2021-12-13 16:56 UTC, omichel commented on src/webots/nodes/WbImageTexture.cpp
> +    QImage *image = i.value().first;
```suggestion
    const QImage *image = i.value().first;
```

2021-12-14 10:35 UTC, ad-daniel approved these changes
Nice catch, no issues with the memory leak either. Thank you.

2021-12-14 10:37 UTC, omichel approved these changes
Looks good to me. Thank you.

2021-12-14 13:08 UTC, merged