Feature PROTO wizard
cyberbotics/webots pull request #4104
Opened 2022-01-10 16:18 UTC by ad-daniel

**Description**
Adds a Wizard for the creation of PROTO files.

2022-01-11 09:04 UTC, omichel requested changes
Thank you.
This is very nice and useful.
The explanation are pretty clear.
I have just a few suggestions.

2022-01-11 09:04 UTC, omichel commented on src/webots/gui/WbNewProtoWizard.cpp
> +  }
```suggestion
  } else
    layout->addWidget(new QLabel("No fields."));
```

2022-01-11 11:37 UTC, ad-daniel commented
Added description field:
![description](https://user-images.githubusercontent.com/44834743/148935827-6a576cd0-cf24-4da7-90a2-ce6b11842ff2.png)

2022-01-11 13:23 UTC, omichel commented
The second page doesn't look great on my Windows machine:

![image](https://user-images.githubusercontent.com/1264964/148950146-235856fa-aea0-43e7-854d-130a53965a9e.png)

2022-01-11 13:38 UTC, omichel commented
Also, I believe it could be a good idea to pre-select a number of field that should be exposed most of the time, as recommended in the [User Guide](https://cyberbotics.com/doc/reference/proto-design-guidelines#recommended-fields-for-simple-proto-nodes). So, if they exist, the "translation" and "rotation" field should be checked by default. Maybe also the "name" field and more arguably the "controller" field (not sure). What do you think?

2022-01-12 07:20 UTC, ad-daniel commented
Hopefully it is high enough now

2022-01-13 11:50 UTC, ad-daniel commented
Text should no longer be cut off.

2022-01-14 07:56 UTC, omichel approved these changes
I confirm it now displays nicely the fields on Windows. They are not cut any more.
Thank you.

2022-01-14 07:58 UTC, merged