Theia and Webots Docker implementation
cyberbotics/webots pull request #4259
Opened 2022-02-18 16:29 UTC by joachimhgg

**Description**

Implement Theia IDE and Webots for webots.cloud using Docker compose

2022-03-02 15:27 UTC, joachimhgg commented
> In https://github.com/cyberbotics/webots-cloud/wiki/Setup-a-Webots-Project-Repository:
> 
>     * The Dockerfile.default, docker-compose-default.yml and docker-compose-theia.yml links have no targets.
> 
>     * `The competitor controller are then started by Webots inside the Webots container of the competitor`: I am not sure to understand, is it the Webots container or the Docker container?
> 
> 
> Otherwise i seems good to me. I saw that you did a lot of modification on Docker but did you try the server without Docker to be sure that nothing was broken in the process?

* I will add the targets when the PR will be merged in `develop`.
* It is the Docker container of Webots, as a container is necessarily a Docker one.
* Yes the instances of Webots can still be created by changing the `docker` flag to `false` in the .json in the `config/simulation` folder.

The simulation server is now sending errors to the `server.js` which interrupt the starting of the simulation and display an appropriate alert depending on the error. The following cases are handle:
* if the world does not exist
* if the default dockerfile or docker-compose.yml are missing (it is a server issue)
* if Webots was unable to start in its container
* if the image is not available on cyberbotics's dockerHub 

In addition, if the user is using its own Dockerfile, it can visualize its building in the JavaScript console.

2022-03-03 07:21 UTC, BenjaminDeleze submitted a review, later dismissed
Looks good to me, but as I am not familiar with Docker it is maybe good to have a second reviewer.

2022-03-03 09:53 UTC, omichel requested changes
It looks pretty good to me (although I didn't tested).

2022-03-03 09:53 UTC, omichel commented on resources/web/server/simulation_server.py
> +                        os.system(f'cp {defaultDockerfilePath} ./Dockerfile')
```suggestion
                        os.system(f'ln -s {defaultDockerfilePath} ./Dockerfile')
```

2022-03-03 09:53 UTC, omichel commented on resources/web/server/simulation_server.py
> +                    os.system(f'cp {dockerComposePath} ./docker-compose.yml')
```suggestion
                    os.system(f'ln -s {dockerComposePath} ./docker-compose.yml')
```

2022-03-03 09:53 UTC, omichel commented on resources/web/server/simulation_server.py
> +                    error = f"error: Miss docker-compose-default.yml in {config['dockerConfDir']}"
```suggestion
                    error = f"Error: Missing docker-compose-default.yml in {config['dockerConfDir']}"
```

2022-03-03 09:53 UTC, omichel commented on resources/web/server/simulation_server.py
> +                        logging.warning(f'[{id(self)}] ERROR killing Webots [{self.webots_process.pid}]')
```suggestion
                        logging.warning(f'[{id(self)}] Error killing Webots [{self.webots_process.pid}]')
```

2022-03-03 09:53 UTC, omichel commented on resources/web/server/config/simulation/docker/docker-compose-theia.yml
> +      - controller_data:/usr/local/$THEIA_V:rw
```suggestion
      - controller_data:/usr/local/$THEIA_VOLUME:rw
```

2022-03-03 09:53 UTC, omichel commented on resources/web/server/simulation_server.py
> +                            envVarDocker["THEIA_V"] = volume
```suggestion
                            envVarDocker["THEIA_VOLUME"] = volume
```

2022-03-03 11:17 UTC, joachimhgg commented on resources/web/server/config/simulation/docker/docker-compose-theia.yml
> +    image: joachimhgg/theiatest:test1
Theia does not provide official images anymore, so we will have the need to build it, depending of our needs. For the moment, I have just built this one for test.

2022-03-03 11:20 UTC, joachimhgg commented on resources/web/server/simulation_server.py
> +                error = f"error: {self.world} does not exist."
This error are sent to the `server.js`, hence I kept the same syntax that we can find on the function `onMessage(event)`

2022-03-03 13:08 UTC, omichel submitted a review, later dismissed
Thank you.

2022-03-03 14:51 UTC, merged