Add two nao motion files
cyberbotics/webots pull request #4274
Opened 2022-02-23 13:12 UTC by BenjaminDeleze

ditto

2022-02-24 08:12 UTC, omichel requested changes
Tai chi spelling is in two words, consequently, I would rename `Taichi.motion` to `TaiChi.motion` and fix the spelling elsewhere.

2022-02-24 08:12 UTC, omichel commented on projects/robots/softbank/nao/controllers/nao_demo/nao_demo.c
> +  wipeForehead;
Coding style:
```suggestion
  wipe_forehead;
```

2022-02-24 08:12 UTC, omichel commented on projects/robots/softbank/nao/controllers/nao_demo_python/nao_demo_python.py
> +        print('[w]: wipe its forehead')
```suggestion
        print('[W]: wipe its forehead')
```

2022-02-24 08:12 UTC, omichel commented on projects/robots/softbank/nao/controllers/nao_demo_python/nao_demo_python.py
> +        print('[T]: perform a taichi move')
```suggestion
        print('[T]: perform Tai chi movements')
```

2022-02-24 13:14 UTC, BenjaminDeleze commented
I also fixed some issues in the NAO controllers

2022-02-25 14:32 UTC, omichel approved these changes
Thank you.

2022-02-25 15:02 UTC, merged