Fix Wrenjs compilation
cyberbotics/webots pull request #4276
Opened 2022-02-24 06:45 UTC by BenjaminDeleze

**Description**
ditto

2022-02-24 09:04 UTC, BenjaminDeleze commented
I will improve the Makefile to be sure that it will fail everytime if there is a problem in the futur

2022-02-25 11:33 UTC, ad-daniel submitted a review, later dismissed
Thank you, appears to be working, can't reproduce it any longer

2022-02-25 15:36 UTC, omichel requested changes
It looks good to me.

2022-02-25 15:36 UTC, omichel commented on resources/Makefile.include
> +	  $(SILENT)rm $(WRENJS_DIR)/wrenjs.js $(WRENJS_DIR)/wrenjs.data $(WRENJS_DIR)/wrenjs.wasm > /dev/null 2>&1 || :
Adding two spaces here looks strange, I would remove one of them:
```suggestion
	 $(SILENT)rm $(WEBOTS_HOME_PATH)/src/wren/wrenjs.js $(WEBOTS_HOME_PATH)/src/wren/wrenjs.data $(WEBOTS_HOME_PATH)/src/wren/wrenjs.wasm  $(WEBOTS_HOME_PATH)/src/wren/functions_to_export.txt > /dev/null 2>&1 || :
	 $(SILENT)rm $(WRENJS_DIR)/wrenjs.js $(WRENJS_DIR)/wrenjs.data $(WRENJS_DIR)/wrenjs.wasm > /dev/null 2>&1 || :
```

2022-02-28 07:22 UTC, omichel approved these changes
Thank you.

2022-02-28 07:25 UTC, merged