Enhancement-controller-mavic
cyberbotics/webots pull request #4293
Opened 2022-03-01 15:34 UTC by joachimhgg

**Description**

Example of Python controller for Mavic patrolling around the house.
This demonstrates how to go to specific world coordinates using its GPS, imu and gyroscope. The drone reaches a given altitude and patrols from waypoint to waypoint.

2022-03-02 16:37 UTC, ad-daniel requested changes
Thank you, only a few comments

2022-03-02 16:37 UTC, ad-daniel commented on docs/guide/mavic-2-pro.md
> +The controller `mavicGotoTargets.py` shows how to move to specific world coordinates using its GPS, imu and gyroscope.
controller should probably be prefixed `mavic2pro` as the other is, not just mavic. Also the name should use snake case to be consistent with the other python controllers. As for the name itself, perhaps: `mavic2pro_waypoints` or `mavic2pro_patrol` might be better?

2022-03-02 16:37 UTC, ad-daniel commented on projects/robots/dji/mavic/controllers/mavicGotoTargets/mavicGotoTargets.py
> +            Xpos, Ypos, altitude = self.gps.getValues()
everything else is snake case, `Xpos` and `Ypos` should also be

2022-03-02 16:37 UTC, ad-daniel commented on projects/robots/dji/mavic/controllers/mavicGotoTargets/mavicGotoTargets.py
> +                vertical_input - yaw_input - pitch_input + roll_input
According to the our python coding style we can have up to 128 characters per line, it shouldn't be necessary to write most of this in two lines (from L165 to L182)

2022-03-02 16:37 UTC, ad-daniel commented on projects/robots/dji/mavic/controllers/mavicGotoTargets/mavicGotoTargets.py
> +        self.current_pose = 6 * [0]  # X,Y,Z, yaw, pitch, roll
```suggestion
        self.current_pose = 6 * [0]  # X, Y, Z, yaw, pitch, roll
```

2022-03-02 16:37 UTC, ad-daniel commented on projects/robots/dji/mavic/controllers/mavicGotoTargets/mavicGotoTargets.py
> +        waypoints = [[-30, 20], [-60, 20],  [-60, 10], [-30, 5]]
```suggestion
        waypoints = [[-30, 20], [-60, 20], [-60, 10], [-30, 5]]
```

2022-03-03 07:45 UTC, ad-daniel submitted a review, later dismissed
Thank you!

2022-03-03 07:57 UTC, omichel commented on docs/guide/mavic-2-pro.md
> +The controller `mavic2pro_patrol.py` shows how to move to specific world coordinates using its GPS, imu and gyroscope.
I believe it is better this way:
```suggestion
The `mavic2pro.c` controller allows you to control the drone, after it has taken off, with the keyboard of your computer.
The `mavic2pro_patrol.py` controller shows how to move to specific world coordinates using its GPS, imu and gyroscope.
```

2022-03-03 09:00 UTC, ad-daniel approved these changes
Thank you, github still having connection issues. I've been rerunning the job a few times but to no avail

2022-03-03 09:16 UTC, merged