Correction of depth measures
cyberbotics/webots pull request #4309
Opened 2022-03-03 11:06 UTC by BenjaminHug8

**Description**
Related to https://github.com/cyberbotics/urdf2webots/pull/161#issuecomment-1055116459, the RangeFinder measures were not correct close to the near plane.

This PR change the way how the depth is measured.

2022-03-03 13:56 UTC, BenjaminHug8 commented
I have to check if we can remove some parts of https://github.com/cyberbotics/webots/pull/4167 used when we get `Nan` instead of `Inf`.

2022-03-04 08:06 UTC, BenjaminHug8 commented
> I have to check if we can remove some parts of #4167 used when we get `Nan` instead of `Inf`.

We still need the check for `Nan` in the motion blur shader.

2022-03-04 09:24 UTC, omichel requested changes
Thank you. I would however add an entry in the change log about it as it is a significant bug fix.

2022-03-04 11:30 UTC, omichel requested changes

2022-03-04 11:30 UTC, omichel commented on docs/reference/changelog-r2022.md
> +    - Fixed measures close to the near plane for the [RangeFinder](rangefinder.md) device ([#4309](https://github.com/cyberbotics/webots/pull/4309)).
```suggestion
    - Fixed measurements close to the near plane for the [RangeFinder](rangefinder.md) device ([#4309](https://github.com/cyberbotics/webots/pull/4309)).
```

2022-03-04 13:16 UTC, omichel approved these changes
Thank you.

2022-03-04 13:19 UTC, merged