Add css file for web scene/animation
cyberbotics/webots pull request #4423
Opened 2022-04-01 14:36 UTC by ThomasOliverKimble

**Description**
After seeing the Robocup matches embedded on their website, it was decided that it was a good idea to export a `CSS` file alongside the `HTML` file to allow users to quickly have a nice looking web animation or simulation

**Tasks**
  - [ ] Agree on the design (colors, sizing, text, etc.)
  - [ ] Confirm documentation, and maybe add screenshots?

**Screenshots**

* Without `CSS`
![web_no_css](https://user-images.githubusercontent.com/100125668/161284797-9ece7bb6-459d-47b2-a450-0840f9e778e1.png)

* With `CSS`
![web_css](https://user-images.githubusercontent.com/100125668/161284450-75c4122f-5955-4fe2-b240-ea340afdea65.png)

2022-04-12 10:26 UTC, BenjaminDeleze requested changes
Seems good to me, however I have some suggestions:

- I would enable the css by default, otherwise they will do it.
- Thus I would put only the image with css styling in the doc.
- I am not totally convinced by the colors of `connect/disconnect` button, even so I think that coloring the button is a nice idea. Maybe the red should be the same as the one of the Webots logo.
- In animations/scenes the page has an vertical overflow. I think that it should not.
- In animations/scenes, I am not convinced about the align-left for the text of the footer.

2022-04-13 07:39 UTC, ThomasOliverKimble commented
> Seems good to me, however I have some suggestions:
> 
> * I would enable the css by default, otherwise they will do it.
> * Thus I would put only the image with css styling in the doc.
> * I am not totally convinced by the colors of `connect/disconnect` button, even so I think that coloring the button is a nice idea. Maybe the red should be the same as the one of the Webots logo.
> * In animations/scenes the page has an vertical overflow. I think that it should not.
> * In animations/scenes, I am not convinced about the align-left for the text of the footer.

Modifications have been applied:
* css enabled by default -> only css image in doc
* I agree on the colored buttons -> they are now always blue
* I have removed vertical overflow on animations/scenes, now there is only a scrollbar in the `Description` section if it is too long
* footer is now aligned left

2022-04-13 09:52 UTC, BenjaminDeleze requested changes
Very good, juste some minors remarks

2022-04-13 09:52 UTC, BenjaminDeleze commented on docs/guide/web-animation.md
> +**Note**: The `CSS` file is meant be used as a styling guide but can be modified/removed.
```suggestion
**Note**: The `CSS` file is meant to be used as a styling guide but can be modified/removed.
```

2022-04-13 09:52 UTC, BenjaminDeleze commented on docs/guide/web-scene.md
> +**Note**: The `CSS` file is meant be used as a styling guide but can be modified/removed.
```suggestion
**Note**: The `CSS` file is meant to be used as a styling guide but can be modified/removed.
```

2022-04-13 09:52 UTC, BenjaminDeleze commented on resources/web/streaming_viewer/index.html
> +      <webots-view style="width:100%; display:block; position: relative"></webots-view>
I am not convinced of using inline CSS, if we also have an external CSS file

2022-04-13 09:52 UTC, BenjaminDeleze commented on resources/web/templates/x3d_playback.html
> +      <webots-view style="width:100%; display:block; position: relative" data-scene=%x3dName% data-animation=%jsonName%></webots-view>
Same remark concerning the inline css

2022-04-14 06:04 UTC, BenjaminDeleze approved these changes
Thank you

2022-04-14 12:13 UTC, merged