I implementented QCommandLineParser to parse the arguments in the par…
cyberbotics/webots pull request #4427
Opened 2022-04-04 09:39 UTC by carikaser

…seArguments function. However, I did not implement the handling of the subcommands or any validity checks for them, as was said in the issue discussion.

**Description**
Adding QCommandLineParser to parse handle the the command line options.

**Related Issues**
This pull-request fixes issue #

**Tasks**
Add the list of tasks of this PR.
  - [ ] Task 1
  - [ ] Task 2

**Documentation**
If this pull-request changes the doc, add the link to the related page, including the `?version=BRANCH_NAME`, such as:
https://cyberbotics.com/doc/guide/getting-started-with-webots?version=develop

**Screenshots**
If this pull-request includes any new robots/simulations/etc. add one or more screenshots of the result.

**Additional context**
Add any other context about the pull-request here.

2022-04-04 13:15 UTC, ad-daniel commented
just for information, we have automatic tests that ensure the code is formatted correctly, so if you don't want to lose your mind waiting for the results you can run the test locally `python3 tests/test_sources.py` or if you use VS code or Atom you can also install plugins so that it automatically formats the code when saving. More instructions about the coding style and the extensions are available [here](https://github.com/cyberbotics/webots/wiki/CPP-Coding-Style/)

2022-04-04 13:18 UTC, carikaser commented
> just for information, we have automatic tests that ensure the code is formatted correctly, so if you don't want to lose your mind waiting for the results you can run the test locally `python3 tests/test_sources.py` or if you use VS code or Atom you can also install plugins so that it automatically formats the code when saving. More instructions about the coding style and the extensions are available [here](https://github.com/cyberbotics/webots/wiki/CPP-Coding-Style/)

Thank you so much, I will check that out !

2022-04-04 13:19 UTC, omichel commented
This PR has many unrelated formatting changes, which makes it hard to review.
Can you please revert these changes, so that we clearly see what your contribution is?

2022-04-19 13:21 UTC, omichel requested changes
Thank you. It looks pretty good.

However, I have a few change requests.

Also, I believe we should not use `QCoreApplication::translate()`, but `tr` instead which is more convenient and used everywhere else in the source code of Webots. See documentation [here](https://doc.qt.io/qt-6/qcoreapplication.html#translate).

Finally, we should avoid using `fprintf(stderr, ...)` and prefer the C++ counterpart: `cerr <<`.

2022-04-19 13:21 UTC, omichel commented on src/webots/gui/WbGuiApplication.cpp
> +        QStringList argumentsList = logArgument[0].split(",");
We try to use `const` everywhere it is possible to enhance readability and make the code more robust:
```suggestion
        const QStringList argumentsList = logArgument[0].split(",");
```

2022-04-19 13:21 UTC, omichel commented on src/webots/gui/WbGuiApplication.cpp
> +      QStringList streamArgument = parser.values(streamOption);
```suggestion
      const QStringList streamArgument = parser.values(streamOption);
```

2022-04-19 13:21 UTC, omichel commented on src/webots/gui/WbGuiApplication.cpp
> +      QStringList protoCacheUpdate = parser.values(updateProtoCacheOption);
```suggestion
      const QStringList protoCacheUpdate = parser.values(updateProtoCacheOption);
```

2022-04-19 13:21 UTC, omichel commented on src/webots/gui/WbGuiApplication.cpp
> +        cout << "Warning: `run` mode is deprecated, falling back to `fast` mode" << endl;
This is not consistent with other printed message: it should probably go through `stderr` and be translated.
```suggestion
        cout << "Warning: `run` mode is deprecated, falling back to `fast` mode" << endl;
```

2022-04-19 13:21 UTC, omichel commented on src/webots/gui/WbGuiApplication.cpp
> +      QStringList mode = parser.values(modeOption);
```suggestion
      const QStringList mode = parser.values(modeOption);
```

2022-04-19 13:35 UTC, omichel commented
Also, the behavior on this branch is now different from before. If I type `webots --unknown-option`, I am getting a dialog box:

![image](https://user-images.githubusercontent.com/1264964/164015758-35da2ffe-7833-4e4f-a618-3426cff36e66.png)

Whereas the behavior on the master branch is to display in the terminal:
```
webots: invalid option: '--unknown-option'
Try 'webots --help' for more information.
```

I believe we should not change the original behavior, which is more user friendly (getting the error in the terminal where the command was issued).

2022-04-19 13:40 UTC, omichel commented on src/webots/gui/WbGuiApplication.cpp
> +      QStringList logArgument = parser.values(logPerfomanceOption);
```suggestion
      const QStringList logArgument = parser.values(logPerfomanceOption);
```

2022-04-21 06:55 UTC, carikaser commented
> Also, the behavior on this branch is now different from before. If I type `webots --unknown-option`, I am getting a dialog box:
> 
> ![image](https://user-images.githubusercontent.com/1264964/164015758-35da2ffe-7833-4e4f-a618-3426cff36e66.png)
> 
> Whereas the behavior on the master branch is to display in the terminal:
> 
> ```
> webots: invalid option: '--unknown-option'
> Try 'webots --help' for more information.
> ```
> 
> I believe we should not change the original behavior, which is more user friendly (getting the error in the terminal where the command was issued).

Thank you for the review. However, concerning this comment, I think it is a particularity of the QCommandLineParser to open a dialog box to display the help or if an error occurs, is this a problem?

2022-04-21 07:07 UTC, omichel commented
Can't we change this default behavior of QCommandLineParser ? Your code seems to print this "invalid option" message to stderr, but it doesn't appear to work. Can you check it?

2022-04-21 07:26 UTC, omichel commented
The documentation says "On Windows, QCommandLineParser uses message boxes to display usage information and errors if no console window can be obtained.". However, when I launch Webots from a MSYS2 console, I don't get the error message in the console.

2022-04-21 07:32 UTC, omichel commented on src/webots/gui/WbGuiApplication.cpp
> +  parser.parse(QCoreApplication::arguments());
Maybe you should check the return value of the `parse()` method and if false, you should print on stderr the error, which you can retrieve with the `errorText()` method. See example [here](https://doc.qt.io/qt-6/qcommandlineparser.html).

2022-04-22 07:59 UTC, omichel commented
I just fixed the terminal problem in a87aad67432bbc7c6b6ed54ed92cfe024dc24ada.

2022-04-25 15:21 UTC, omichel requested changes
Thank you for the changes.
However, I have a problem with this PR: the world file argument is ignored.
On the master branch: `webots projects/robots/gctronic/e-puck/worlds/e-puck.wbt` opens this world whereas on this branch, it ignores the world file argument and open the previously opened world.
Could you try to fix it?

2022-04-27 12:01 UTC, omichel requested changes

2022-04-27 12:01 UTC, omichel commented on src/webots/gui/WbGuiApplication.cpp
> +        cerr << tr("webots: invalid option : '--log-performance': log file path is missing.").toUtf8().constData();
In English, there is no space before a colon:
```suggestion
        cerr << tr("webots: invalid option: '--log-performance': log file path is missing.").toUtf8().constData();
```

2022-04-27 12:01 UTC, omichel commented on src/webots/gui/WbGuiApplication.cpp
> +    cerr << "Warning: you should also use --batch (in addition to --stream) for production." << endl;
Why did you remove the translation here?

2022-04-27 12:29 UTC, omichel requested changes
When I type `webots --mode=` or `webots --mode=unknown`, it doesn't display any error and runs normally while it was displaying errors in this case on the master branch.

2022-04-27 12:35 UTC, omichel commented
Also, the help message is not as good as before (less precise, incomplete, not very useful):
```
webots --help
$ webots --help
Usage: C:\msys64\home\Olivier\webots\msys64\mingw64\bin\webots-bin.exe [options]

Options:
  -?, -h, --help                   Displays help on commandline options.
  --help-all                       Displays help including Qt specific options.
  -v, --version                    Displays version information.
  --minimize                       Minimize the window
  --fullscreen                     View window in fullscreen
  --mode <speed>                   Specify speed of simulation (default is
                                   realtime)
  --convert                        Convert
  --no-rendering                   No rendering
  --sysinfo                        System information
  --batch                          Batch
  --update-proto-cache <task>      Update the PROTO cache
  --update-world                   Update world
  --enable-x3d-meta-file-export    Enable x3d meta file export
  --stream                         Stream
  --stdout                         stdout
  --stderr                         stderr
  --log-performance <logArgument>  Log performance
  --disable-logging                Disable logging
  --enable-logging                 Enable logging
  --log-level                      Log level
  --no-sandbox                     No sandbox
  --single-process                 Single Process
  --remote-debugging-port          Remote Debugging Port
```

Whereas it used to be:
```
$ webots --help
Usage: webots [options] [worldfile]

Options:

  --help
    Display this help message and exit.

  --version
    Display version information and exit.

  --sysinfo
    Display information about the system and exit.

  --mode=<mode>
    Choose the startup mode, overriding application preferences. The <mode>
    argument must be either pause, realtime or fast.

  --no-rendering
    Disable rendering in the main 3D view.

  --fullscreen
    Start Webots in fullscreen.

  --minimize
    Minimize the Webots window on startup.

  --batch
    Prevent Webots from creating blocking pop-up windows.

  --stdout
    Redirect the stdout of the controllers to the terminal.

  --stderr
    Redirect the stderr of the controllers to the terminal.

  --stream[="key[=value];..."]
    Start the Webots streaming server. Parameters may be
    given as an option:
      port=1234          - Start the streaming server on port 1234.
      mode=<x3d|mjpeg>   - Specify the streaming mode: x3d (default) or mjpeg.
      monitorActivity    - Print a dot '.' on stdout every 5 seconds.
      disableTextStreams - Disable the streaming of stdout and stderr.

  --log-performance=<file>[,<steps>]
    Measure the performance of Webots and log it in the file specified in the
    <file> argument. The optional <steps> argument is an integer value that
    specifies how many steps are logged. If the --sysinfo option is used, the
    system information is prepended into the log file.

  convert
    Convert a PROTO file to a URDF, WBO, or WRL file.

Please report any bug to https://cyberbotics.com/bug
```

The goal of this PR is not to change the help message or the behavior, but just to use the QCommandLineParser class.
We want to keep the behavior similar to what it was before.

2022-04-28 06:16 UTC, omichel requested changes

2022-04-28 06:16 UTC, omichel commented on src/webots/gui/WbGuiApplication.cpp
> +      }
[coding style](https://github.com/cyberbotics/webots/wiki/CPP-Coding-Style#cs360-single-if-while-or-for-statement-must-be-written-without-brackets-the-statement-part-should-be-put-on-a-separate-line-in-case-of-nested-block-keep-brackets) (here and at other places):
```suggestion
      if (mode.size() != 1 || mode[0] == "=")
        cerr << tr("Error: Must specify one mode argument.").toUtf8().constData() << endl;
```

2022-04-28 06:38 UTC, omichel commented
Thank you, the behavior is now very good. We are almost there.

I just have another requirement, I found the error messages a little bit inconsistent:
```
$ webots --mode=unknown
webots: invalid option: 'unknown'
Try 'webots --help' for more information.

$ webots --stream="unknown"
webots: unknown option: 'unknown' in --stream
Try 'webots --help' for more information.
Warning: you should also use --batch (in addition to --stream) for production.

$ webots --unknown-option
Webots: Unknown option 'unknown-option'.
```

Some comments:
1. Sometime Webots is spelled with an uppercase letter, sometimes not. I would prefer the lowercase version as it corresponds to the command line.
2. Sometimes the "Try 'webots --help' for more information." is displayed in case of error, sometimes not (note: it is always displayed on the master branch). I think it should always be displayed in case of error.
3. Sometime the option with an unknown value is displayed (like in `--stream`), sometimes not (like in `--mode`). This should be more consistent. I believe we should display an error message like "webots: invalid value 'blahblah' in --option_name".

Although some of these inconsistencies are also present on the master branch, this PR is a good opportunity to address them.

2022-04-28 10:13 UTC, omichel commented
Oops, I actually meant that we should use the spelling "webots" only when we refer to the command line, not the software in general for which the "Webots" is indeed better... Sorry for any confusion...

2022-04-29 07:29 UTC, omichel commented
I just fixed a number of problems and crashes depending on the command argument passed to webots.

2022-04-29 08:43 UTC, ad-daniel requested changes
Code-wise there were just a few one-liners to unbracket left. I couldn't suggest all the changes at once due to deleted lines, hopefully I didn't make a mistake in the process.

Behavior wise I've only noticed two differences:
- In the current branch `./webots projects/robots/niryo/ned/worlds/ned.wbt --stream` gives an error. Now it requires a value, which in theory should be optional
- Before `./webots convert projects/robots/niryo/ned/protos/Ned.proto` generated the urdf, now it gives an error. In this case I think we should ameliorate the description as well, it's not really clear how it's supposed to be used (since supposedly it converts in different formats), nor why only this command is `convert` instead of `--convert` (it was already like this)

2022-04-29 08:43 UTC, ad-daniel commented on src/webots/gui/WbGuiApplication.cpp
> +  QStringList args = parser.optionNames();
```suggestion
  const QStringList args = parser.optionNames();
```

2022-04-29 08:43 UTC, ad-daniel commented on src/webots/gui/WbGuiApplication.cpp
> +    } else if (subCommand == "minimize" && parser.isSet(minimizeOption)) {
```suggestion
    if (subCommand == "help" && parser.isSet(helpOption))
      mTask = HELP;
    else if (subCommand == "version" && parser.isSet(versionOption))
      mTask = VERSION;
    else if (subCommand == "minimize" && parser.isSet(minimizeOption))
```

2022-04-29 08:43 UTC, ad-daniel commented on src/webots/gui/WbGuiApplication.cpp
> +    } else if (subCommand == "fullscreen" && parser.isSet(fullscreenOption)) {
```suggestion
    else if (subCommand == "fullscreen" && parser.isSet(fullscreenOption))
```

2022-04-29 08:43 UTC, ad-daniel commented on src/webots/gui/WbGuiApplication.cpp
> +    } else if (subCommand == "mode" && parser.isSet("mode")) {
```suggestion
    else if (subCommand == "mode" && parser.isSet("mode")) {
```

2022-04-29 08:43 UTC, ad-daniel commented on src/webots/gui/WbGuiApplication.cpp
> +    } else if (subCommand == "no-rendering" && parser.isSet(noRenderingOption)) {
```suggestion
    } else if (subCommand == "no-rendering" && parser.isSet(noRenderingOption))
```

2022-04-29 08:43 UTC, ad-daniel commented on src/webots/gui/WbGuiApplication.cpp
> +    } else if (subCommand == "convert" && parser.isSet("convert")) {
```suggestion
    else if (subCommand == "convert" && parser.isSet("convert")) {
```

2022-04-29 08:43 UTC, ad-daniel commented on src/webots/gui/WbGuiApplication.cpp
> +    } else if (subCommand == "sysinfo" && parser.isSet(sysinfoOption)) {
```suggestion
    } else if (subCommand == "sysinfo" && parser.isSet(sysinfoOption))
```

2022-04-29 08:43 UTC, ad-daniel commented on src/webots/gui/WbGuiApplication.cpp
> +    } else if (subCommand == "batch" && parser.isSet(batchOption)) {
```suggestion
    else if (subCommand == "batch" && parser.isSet(batchOption)) {
```

2022-04-29 08:43 UTC, ad-daniel commented on src/webots/gui/WbGuiApplication.cpp
> +    } else if (subCommand == "update-world" && parser.isSet(updateWorldOption)) {
```suggestion
    } else if (subCommand == "update-world" && parser.isSet(updateWorldOption))
```

2022-04-29 08:43 UTC, ad-daniel commented on src/webots/gui/WbGuiApplication.cpp
> +    } else if (subCommand == "enable-x3d-meta-file-export" && parser.isSet(x3DMetaFileExportOption)) {
```suggestion
    else if (subCommand == "enable-x3d-meta-file-export" && parser.isSet(x3DMetaFileExportOption))
```

2022-04-29 08:43 UTC, ad-daniel commented on src/webots/gui/WbGuiApplication.cpp
> +    } else if (subCommand == "stream" && parser.isSet("stream")) {
```suggestion
    else if (subCommand == "stream" && parser.isSet("stream")) {
```

2022-04-29 08:43 UTC, ad-daniel commented on src/webots/gui/WbGuiApplication.cpp
> +    } else if (subCommand == "stdout" && parser.isSet(stdoutOption)) {
```suggestion
    } else if (subCommand == "stdout" && parser.isSet(stdoutOption))
```

2022-04-29 08:43 UTC, ad-daniel commented on src/webots/gui/WbGuiApplication.cpp
> +    } else if (subCommand == "stderr" && parser.isSet(stderrOption)) {
```suggestion
    else if (subCommand == "stderr" && parser.isSet(stderrOption))
```

2022-04-29 08:43 UTC, ad-daniel commented on src/webots/gui/WbGuiApplication.cpp
> +    } else if (subCommand == "log-performance" && parser.isSet("log-performance")) {
```suggestion
    else if (subCommand == "log-performance" && parser.isSet("log-performance")) {
```

2022-04-29 12:08 UTC, omichel commented
I didn't yet fixed the `convert` problem, but I am now wondering what is the added value of this `QCommandLineParser` with respect to the previous implementation. It turns out that we don't use the `QCommandLineParser` goodies such as the automatic display of the help message and the code to parse the options doesn't look simpler than before. So, I am questioning the usefulness of this idea. Do you see any advantage of using `QCommandLineParser` in this case?

2022-05-02 09:34 UTC, carikaser commented
> I didn't yet fixed the `convert` problem, but I am now wondering what is the added value of this `QCommandLineParser` with respect to the previous implementation. It turns out that we don't use the `QCommandLineParser` goodies such as the automatic display of the help message and the code to parse the options doesn't look simpler than before. So, I am questioning the usefulness of this idea. Do you see any advantage of using `QCommandLineParser` in this case?

I was thinking the same as you, as we don't use the main features of the `QCommandLineParser` such as the automatic help, version or error display, it seems that there would not be an added value compared to the previous code (and even makes the code longer).  Thus, I would also say that the way the parsing was done before was more optimal in order to get the desired results and using the `QCommandLineParser` here seems unnecessary.

2022-05-02 09:41 UTC, omichel commented
Great, so I am closing this PR.

2022-05-02 09:41 UTC, closed without merging