Enhancement animation loading
cyberbotics/webots pull request #4445
Opened 2022-04-11 13:21 UTC by BenjaminDeleze

After seeing the animation generated by Robocup (https://robocup-hlvs.de/GAME_K-GD6-3/public_logs/K-GD6-3.html) , I improved the loading time of the animation by:

- starting the loading of JSON ealier.
- Then I generated some keyframes (think about it like snapshots of the simulation) in order to increase the response time when jumping forward or backward in the replay. The keyframes are generated during the loading.
  - I measured an overhead of 300ms on the Robocup animation for a total loading time of about 16 seconds. It seems acceptable to me knowing that this animation has a JSON file of 400MB.
- I also reordered some loops to minimize the number of iterations
- Finally I made some cleanup.

To test and compare with the original: https://cyberbotics.com/animations/robocup/K-GD6-3.html

2022-04-11 15:26 UTC, omichel requested changes
That looks good to me.

2022-04-11 15:26 UTC, omichel commented on resources/web/wwi/Animation.js
> +        // We do not want to include the previousPoseStep in the loop as its updates are in the keyFrame. However, we need to include it if their is no keyFrames or if it is the step 0 as their is no
their -> there

2022-04-11 15:26 UTC, omichel commented on resources/web/wwi/Animation.js
> +        for (let i = this.step; i >= previousPoseStep; i--) { // Iterate through each step until the nearest keyFrame is reached or all necessary updates have been applied. Go in decreasing order to
steps

2022-04-11 15:44 UTC, omichel commented
It works very well! However, when testing on both Firefox and Chrome, there is a waiting time after the scene is display and before the buttons of the GUI are displayed. What is webotsjs doing at this point? It would be nice to display a progress message here, maybe, otherwise the user may believe that it is just displaying a static picture...

2022-04-12 06:05 UTC, BenjaminDeleze commented
> It works very well! However, when testing on both Firefox and Chrome, there is a waiting time after the scene is displayed and before the buttons of the GUI are displayed. What is webotsjs doing at this point? It would be nice to display a progress message here, maybe, otherwise the user may believe that it is just displaying a static picture...

It is when the scene has finished to load, but not the json.
Indeed it would be nice, but as @ThomasOliverKimble is reworking the progress bar, I thought it was maybe better to wait until the new version is out.

2022-04-12 06:29 UTC, omichel requested changes

2022-04-12 06:29 UTC, omichel commented on resources/web/wwi/Animation.js
> +        // We do not want to include the previousPoseStep in the loop as its updates are in the keyFrame. However, we need to include it if there is no keyFrames or if it is the step 0 as their is no
```suggestion
        // We do not want to include the previousPoseStep in the loop as its updates are in the keyFrame. However, we need to include it if there is no keyFrames or if it is the step 0 as there is no keyFrame for it
```

2022-04-12 06:29 UTC, omichel commented
Not sure why the mac source tests are failing...

2022-04-12 06:30 UTC, BenjaminDeleze commented on resources/web/wwi/Animation.js
> +        // We do not want to include the previousPoseStep in the loop as its updates are in the keyFrame. However, we need to include it if there is no keyFrames or if it is the step 0 as their is no
oups

2022-04-12 06:32 UTC, omichel approved these changes
Thank you.

2022-04-12 06:41 UTC, merged