Remote extern controllers through TCP/UDP
cyberbotics/webots pull request #4518
Opened 2022-05-06 13:46 UTC by ygoumaz

**Description**
Currently, <extern> controllers can be used on a local machine with Webots. With multiple Webots instances, an environment variable WEBOTS_PID containing the PID of the Webots process allows to differentiate which instance we want to target. Same for the robots: with multiple robots with <extern> controllers, an environment variable WEBOTS_ROBOT_NAME can be set to target a specific robot.

The goal of this PR is to extend the <extern> controllers to remote communication. Webots could start on a machine and a controller on another machine. A new environment variable WEBOTS_CONTROLLER_URL replaces the two old ones to specify that we are on a separate machine.

URL format is as follows: `<protocol>://<machine_ip>:<webots_port>/<robot_name>`. Three protocols should be available:
- `ipc` for local <extern> controllers (already implemented in PR #4344).
- `tcp` and `udp` for remote <extern> controllers (this PR implementation).

The webots_port allows to differentiate Webots instances, while the robot_name allows to target a specific robot.

**Documentation**
https://cyberbotics.com/doc/guide/running-extern-robot-controllers?version=feature-enable-remote-extern-controllers

**Additional context**
This PR continues the work accomplished in #4344, where the local <extern> controller are implemented using the WEBOTS_CONTROLLER_URL variable and the `ipc` protocol.

2022-06-01 15:03 UTC, omichel requested changes
Good job. This is a first code review. I still need to test it.

2022-06-01 15:03 UTC, omichel commented on src/webots/nodes/utils/WbDataStream.cpp
> +  }
```suggestion
  for (int i = 0; i != sizeof(n); ++i)
    append((char)((n & (0xFF << (i * 8))) >> (i * 8)));
```

2022-06-01 15:03 UTC, omichel commented on src/webots/nodes/utils/WbDataStream.cpp
> +  }
```suggestion
  for (int i = 0; i != sizeof(n); ++i)
    append((char)((n & (0xFF << (i * 8))) >> (i * 8)));
```

2022-06-01 15:03 UTC, omichel commented on src/webots/nodes/utils/WbDataStream.cpp
> +}
```suggestion
}

```

2022-06-02 08:13 UTC, omichel commented on src/controller/c/tcp_client.h
> +typedef int TcpClient;
I believe it makes the code less opaque to remove this `typedef` and use `int` instead for the file descriptor of the socket, which is something very standard.
```suggestion
```

2022-06-02 08:22 UTC, omichel commented on src/controller/c/tcp_client.c
>    free(c);
That seems wrong and is causing a compilation warning:
```suggestion
```

2022-06-02 08:35 UTC, omichel approved these changes
Thank you.
I tested it on Windows and it works nicely.
I would be nice however to have a second review as this PR is quite big.

2022-06-02 14:14 UTC, BenjaminDeleze requested changes
Seems good! only some minors things:
It is strange to me that if we have two robots the behavior is different depending if the connection is remote or not:
Local: if name is not specified, refuse the connection
Remote: if name is not specified, connect to the first one

otherwise I ran most of the guided tour worlds without any problems!

2022-06-02 14:51 UTC, ygoumaz commented
The behavior is indeed not consistent with local extern controllers. I have updated the code to refuse connection if the robot-name is unset and multiple extern controllers are defined in the simulation. The documentation has also been updated.

2022-06-02 14:55 UTC, omichel commented on docs/guide/running-extern-robot-controllers.md
> +For remote connections, it is mandatory to specify the complete URL for the controller to find the Webots instance, but the `/<robot_name` URL path can be left blank if only one robot has an `<extern
```suggestion
For remote connections, it is mandatory to specify the complete URL for the controller to find the Webots instance, but the `/<robot_name>` URL path can be left blank if only one robot has an `<extern>` controller.
```

2022-06-02 15:17 UTC, omichel submitted a review, later dismissed
Thank you.

2022-06-03 06:14 UTC, BenjaminDeleze submitted a review, later dismissed
Thank you

2022-06-07 11:57 UTC, omichel approved these changes
Looks good to me.

2022-06-07 12:00 UTC, BenjaminDeleze approved these changes
Thank you

2022-06-07 12:01 UTC, merged