Enhancement assimp webotsjs
cyberbotics/webots pull request #4519
Opened 2022-05-06 13:52 UTC by BenjaminDeleze

The goal of this PR is to support `Mesh` and `ColladaShape` in WebotsJS as in Webots.
For now, Webots converts the `WbMesh`/`WbColladaShape` in `WbIndexedFaceSet`.

- [x] Compile Assimp with Emscripten and build some wrappers to be able to use it in JS (made thanks to https://github.com/cyberbotics/assimpjs).
- [ ] Modify the export of `WbMesh` and `WbColladaShape` in Webots.
- [ ] Implement the parsing and rendering of `WbMesh` and `WbColladaShape` in WebotsJS.

2022-05-24 12:05 UTC, ad-daniel requested changes
Thank you, overall works nicely, the issues I've encountered are:

- the pickable state appears no to be active on the webotsjs side. If you load the car or the elf I sent you last time it seems it's impossible to rotate around them
- if the mesh file contains spaces, ex: `/home/daniel/Desktop/3D Models/cads/car/car.dae` it doesn't appear to be able to load it on the webotsjs side. Maybe it's due to the filtering when splitting the url?
- is the stream supposed to respond to field changes? When I change the url for instance, isn't it supposed to load the new object? If I cut and paste the node it does so, but not if I just change the url.
- Lastly, just a question: I noticed that for the docs of the robotino3 you copied the `head_white_cover.obj` file, can't we refer to the one in the protos instead? Otherwise we'll end up doubling all meshes

2022-05-24 12:06 UTC, BenjaminDeleze commented on resources/web/wwi/dependencies/assimpjs.js
> +function(assimpjs) {
yes, it is a "glue" file generated automatically by Emscripten to load the `.wasm`

2022-05-24 12:18 UTC, BenjaminDeleze commented
> * is the stream supposed to respond to field changes? When I change the url for instance, isn't it supposed to load the new object? If I cut and paste the node it does so, but not if I just change the url.

I don't think so as it was not the case before. (only some fields supports updates: translation, rotation, some colors and lights)

2022-05-24 12:38 UTC, BenjaminDeleze commented on resources/web/wwi/nodes/WbCadShape.js
> +    return new WbPbrAppearance(getAnId(), baseColor, baseColorMap, transparency, roughness, roughnessMap, metalness, metalnessMap, iblStrength, normalMap, normalMapFactor, occlusionMap, occlusionMapS
Until now not (at least in practice). After some discussion, it was decided to put it at 128 (as we do for other languages), but I will adapt all our JS code base to this rule in another PR.

2022-05-24 12:49 UTC, BenjaminDeleze commented on src/webots/nodes/utils/WbUrl.cpp
> +        node->warn(QObject::tr("Mesh export fails, because too much meshes are sharing the same name: %1.").arg(url));
I tested without and it is necessary

2022-05-24 14:20 UTC, BenjaminDeleze commented
> * the pickable state appears no to be active on the webotsjs side. If you load the car or the elf I sent you last time it seems it's impossible to rotate around them

I think you discovered a more general bug here. It seems that webotsJS does not handle well the pickable state when we are too far from an object. It is more visible with the car and elf because the are big, so we put the viewpoint further. I will handle it in another issue as it is not related to this PR. Well spotted!

>* if the mesh file contains spaces, ex: /home/daniel/Desktop/3D Models/cads/car/car.dae it doesn't appear to be able to load it on the webotsjs side. Maybe it's due to the filtering when splitting the url?

It appeared to be a problem not only with `CadShape` but also with more general mesh and images. I believe I fixed the problem.

>* Lastly, just a question: I noticed that for the docs of the robotino3 you copied the head_white_cover.obj file, can't we refer to the one in the protos instead? Otherwise we'll end up doubling all meshesnoticed that for the docs of the robotino3 you copied the head_white_cover.obj file, can't we refer to the one in the protos instead? Otherwise we'll end up doubling all meshes

It was a problem of Robotino that has an wrongly defined url inside its Proto, it is now fixed

2022-05-25 07:20 UTC, ad-daniel approved these changes
Looks good, thank you

2022-05-25 07:56 UTC, omichel requested changes

2022-05-25 07:56 UTC, omichel commented on src/webots/nodes/WbCadShape.cpp
> +      QString meshPath(WbUrl::computePath(this, "url", mUrl, i));
```suggestion
      const QString meshPath(WbUrl::computePath(this, "url", mUrl, i));
```

2022-05-25 07:56 UTC, omichel commented on src/webots/nodes/WbMesh.cpp
> +        QString newUrl = WbUrl::exportMesh(this, mUrl, i, writer);
```suggestion
        const QString newUrl = WbUrl::exportMesh(this, mUrl, i, writer);
```

2022-05-25 07:56 UTC, omichel commented on src/webots/nodes/WbMesh.cpp
> +    writer << " name='" << name_dirty.replace("&", "&amp;", Qt::CaseInsensitive) << "'";
We should use camelCase for variables:
```suggestion
    QString dirtyName = mName->value();
    dirtyName.replace("\'", "&apos;", Qt::CaseInsensitive);
    dirtyName.replace("\"", "&quot;", Qt::CaseInsensitive);
    dirtyName.replace(">", "&gt;", Qt::CaseInsensitive);
    dirtyName.replace("<", "&lt;", Qt::CaseInsensitive);
    writer << " name='" << dirtyName.replace("&", "&amp;", Qt::CaseInsensitive) << "'";
```

2022-05-25 07:56 UTC, omichel commented on src/webots/vrml/WbSFColor.hpp
> +  explicit WbSFColor(double r, double g, double b) : mValue(WbRgb(r, g, b)) {}
🤣

2022-05-25 08:56 UTC, omichel approved these changes
Thank you.

2022-05-25 09:20 UTC, merged