Feature animals proto
cyberbotics/webots pull request #4539
Opened 2022-05-17 17:32 UTC by carikaser

Adding new animal PROTOs

Defining PROTO files for the following animals: cow, horse, dog, cat, rabbit, deer, sheep, fox and farm related objects (barn for now).

2022-06-05 21:49 UTC, ad-daniel requested changes
Thank you, primarely I believe the PR could use additional cleanup:

- I don't know if it's because you attempted to generate the docs prior to having finished implementing the PROTO (or rather, prior to doing the clean up), but it seems that doing so added a lot of images to `docs/guide/images` that have nothing to do with the final state of the animals folder. I'd suggest undoing all the changes done to the docs folder and regenerating it
- Similarly, from which branch did you generate the docs? Since this PR is targetting develop the urls should reference R2022b, not R2022a. Since you are introducing new objects, there's no reason for the PR to change unrelated stuff like the documentation of other objects like "advertising-board". It's possible the script does more than it should, and make additional changes (it shouldn't but sometimes it does), but regardless, unrelated changes don't need to be committed.
- the icon of the barn is not in the right location
- I've noticed that several mtl files (for instance cat.mtl) refer to textures like:
```
map_Bump Cat_bump.jpg
map_Kd Cat_diffuse.jpg
```
which are not included/used. I believe it's because in the PROTO you opted to define the shapes manually (i.e., using a Mesh node + PBRAppearance node instead of using a CadShape node), which is fine as an approach, but in that case I'd remove these references from the mtl files since they don't bring anything useful at this point. 
- As mentioned by the script that generates the docs (and the failing test), the `docs/guide/menu.md` file needs to be updated as well
- In most animals I believe the capsule for the body is too big, the capsule should reflect most of the body, doesn't need to contain every detail of it. In many cases it can be shorter and have  smaller radius

2022-06-05 21:49 UTC, ad-daniel commented on docs/guide/object-animals.md
> +### BrownCow Field Summary
since the proto of the cow was renamed, the doc must be regenerated

2022-06-05 21:49 UTC, ad-daniel commented on projects/objects/animals/protos/Horse.proto
> +          url "webots://projects/objects/animals/protos/horse/meshes/Horse.obj"
all other object files you included are lowercase, for consistency this should be as well

2022-07-21 07:20 UTC, BenjaminDeleze commented
I completed this PR by:

- Improving the bounding object (tell me if they are too/not enough precise as I modeled them to support physics but we finally removed it).
- Removing the physics.
- Changing the orientation from RLU to FLU.
- Renaming textures and turn the heavy png in lighter jpg.
- Increasing the size of the `barn.proto` to match the size of the houses.
- Adding thumbnail pictures for the doc.
- Improving the `Boomer.wbt` to include the new protos.

I think I addressed all the comments made by Daniel and Olivier

2022-07-21 08:25 UTC, omichel requested changes

2022-07-21 08:25 UTC, omichel commented on docs/reference/changelog-r2023.md
> +    - Added some static animals (cow, horse, deer, sheep, dog, fox, cat, rabbit) and a barn ([#4539](https://github.com/cyberbotics/webots/pull/4539)).
```suggestion
    - Added some static animals (cow, horse, deer, sheep, dog, fox, cat and rabbit) and a barn ([#4539](https://github.com/cyberbotics/webots/pull/4539)).
```

2022-07-21 08:25 UTC, omichel commented on projects/objects/animals/protos/Cat.proto
> +# A static Cat.
```suggestion
# A static cat.
```

2022-07-21 08:25 UTC, omichel commented on projects/objects/animals/protos/Dog.proto
> +# A static Dog.
```suggestion
# A static dog.
```

2022-07-21 08:25 UTC, omichel commented on projects/objects/animals/protos/Rabbit.proto
> +# A static Rabbit.
```suggestion
# A static rabbit.
```

2022-07-21 08:25 UTC, omichel commented on projects/objects/buildings/protos/Barn.proto
> +# A Barn.
```suggestion
# A barn.
```

2022-07-21 09:52 UTC, omichel approved these changes
Thank you.

2022-07-25 15:20 UTC, ad-daniel approved these changes
Thank you!

2022-07-26 05:57 UTC, merged