Fix world info in Guided Tour
cyberbotics/webots pull request #4712
Opened 2022-06-22 07:51 UTC by stefaniapedrazzi

If loading a guided tour world takes long (usually because of the assets download) the Guided Tour window is updated before the `WbWorld::instance()` object is updated and thus still shows infos related to the previously loaded world.

While waiting for the world to load, the title label shows the world file name and the info contains the "Loading.." text.
Then, after the world loading is completed and `WbWorld::instance()`  is reset, the title and info are replaced by the actual `WorldInfo` field values.
![Screenshot from 2022-06-22 09-45-07](https://user-images.githubusercontent.com/5910449/174973612-ff663194-5731-40d8-bd2a-3d92fcbfa133.png)

2022-06-22 09:59 UTC, omichel requested changes

2022-06-22 09:59 UTC, omichel commented on src/webots/gui/WbGuidedTour.cpp
> +      // Reset title and info until correct info are available
```suggestion
      // Reset title and info until correct info is available
```

2022-06-22 10:17 UTC, omichel approved these changes
That looks better to me this way.
Thank you.

2022-06-23 10:12 UTC, stefaniapedrazzi commented
I had to fix a clang-format error.
Build test passed (before I synchronized with develop).

2022-06-23 10:14 UTC, omichel approved these changes
Thank you.

2022-06-23 10:27 UTC, merged