Add new workflow `test_build` label
cyberbotics/webots pull request #4737
Opened 2022-06-23 10:20 UTC by stefaniapedrazzi

Add new label to be used by the GitHub Action workflow to compile Webots without generating the packages.

This could maybe speed up the tests.
What do you think? Could this be useful?

If yes, I can complete the implementation for all the workflow files.

2022-06-23 10:21 UTC, omichel commented
Yes, that would be useful.
Meanwhile, we should also have a wiki page that explains the actions fired by the tags.

2022-06-27 09:57 UTC, stefaniapedrazzi commented
Here is a new page describing the labels:
https://github.com/cyberbotics/webots/wiki/CI-Test-Labels
Also linked from the Git Worklflow page (https://github.com/cyberbotics/webots/wiki/Git-workflow)

I will add it to the wiki home page when this PR is accepted.

2022-06-30 07:36 UTC, stefaniapedrazzi commented
`make webots_target -j4` instruction works fine on linux and windows in this PR but not on macOS.
I would need to test on the macOS machine to better debug the issue.

2022-07-11 12:31 UTC, BenjaminDeleze requested changes
Seems good, only some small remarks

2022-07-11 12:31 UTC, BenjaminDeleze commented on .github/workflows/test_suite_linux_develop.yml
> +         fetch-depth: 15
```suggestion
      with:
         submodules: true
         fetch-depth: 15
         ref: develop
```

2022-07-11 12:31 UTC, BenjaminDeleze commented on .github/workflows/test_suite_mac_develop.yml
> +        export PATH=/usr/local/bin/:$PATH
Why do we need to add this to the PATH only for `develop` ?

2022-07-11 14:02 UTC, merged