Add blog post
cyberbotics/webots pull request #4745
Opened 2022-06-24 12:02 UTC by ad-daniel

**Description**
Ditto.

2022-07-05 15:05 UTC, BenjaminDeleze requested changes

2022-07-05 15:05 UTC, BenjaminDeleze commented on docs/blog/Webots-2022-b-release.md
> +- Use [CadShape](../reference/cadshape.md) node to represent for visual tags with mesh
strange sentence

2022-07-05 15:05 UTC, BenjaminDeleze commented on docs/blog/Webots-2022-b-release.md
> +- A very requested feature, R2022b comes with native support for Apple M1 processors on macOS
Are we sure it works?

2022-07-06 13:52 UTC, omichel requested changes

2022-07-06 13:52 UTC, omichel commented on docs/blog/Webots-2022-b-release.md
> +[Franka Emika](https://www.franka.de/)'s [Panda](../guide/panda.md) robot that comes with the [PandaHand](../guide/panda.md#panda-hand) gripper.
This is was not a sentence:
```suggestion
The [Franka Emika](https://www.franka.de/)'s [Panda](../guide/panda.md) robot comes with the [PandaHand](../guide/panda.md#panda-hand) gripper.
```

2022-07-06 13:52 UTC, omichel commented on docs/blog/Webots-2022-b-release.md
> +You can share 3D scenes and animations recorded from a simulation, but also fully interactive simulations.
```suggestion
You can share 3D scenes and animations recorded from simulations, but also fully interactive simulations.
```

2022-07-06 13:52 UTC, omichel commented on docs/blog/Webots-2022-b-release.md
> +The change does not introduce a loss of performance.
```suggestion
This change does not introduce any loss of performance.
```

2022-07-06 13:52 UTC, omichel commented on docs/blog/Webots-2022-b-release.md
> +And many other bug fixes.
```suggestion
And many bug fixes.
```

2022-07-06 15:39 UTC, omichel approved these changes

2022-07-06 15:58 UTC, merged