Fixed hang after copy/paste of robots on Linux
cyberbotics/webots pull request #4748
Opened 2022-06-24 14:04 UTC by omichel

Fixes #4716.

2022-06-24 15:43 UTC, ad-daniel requested changes
I'm not sure if it's related to the same original issue but if I:

- run the simulation a few seconds and pause it
- copy and paste the robot minimum 2 times (doesn't trigger for just 1 paste)
- I get:

```
ERROR: Cannot listen to the local server (server name = '/tmp/webots-1234/ipc/MyBot%282%29/intern'): QLocalServer::listen: Name error`
```

2022-06-24 15:43 UTC, ad-daniel commented on src/webots/control/WbController.cpp
> +  // check if robot was renamed before it started (this happens in case of copy/paste of the robot)
```suggestion
  // check if the robot was renamed before it started (this happens in case of copy/paste of the robot)
```

2022-06-24 16:24 UTC, ad-daniel commented
Not sure if something is wrong on my end, but it seems I can't run the simulation anymore (the unmodified world)

2022-06-27 06:41 UTC, omichel commented
I can indeed reproduce the problem, will investigate...

2022-06-27 08:53 UTC, omichel commented
> Not sure if something is wrong on my end, but it seems I can't run the simulation anymore (the unmodified world)

I believe I fixed the problem. Sorry for the trouble...

2022-06-27 09:54 UTC, merged