Fix convert root to basenode
cyberbotics/webots pull request #4897
Opened 2022-07-14 14:33 UTC by BenjaminDeleze

Add the SubProto of a Proto to the extern Proto list when clicking on `Convert root to base node`

PS: I am not sure that the ways I modified `combinePaths` is very clean.

2022-07-15 08:04 UTC, ad-daniel requested changes
The implementation looks good, I've only had a warning on this:
- `highway_overtake.wbt`: convert `StraightRoadSegment.proto`

2022-07-15 08:07 UTC, ad-daniel commented on src/webots/vrml/WbNode.cpp
> +      if (!subProtoUrl.endsWith(".proto")) {
```suggestion
      if (!subProtoUrl.endsWith(".proto", Qt::CaseInsensitive)) {
```

2022-07-18 08:36 UTC, ad-daniel requested changes
Just details, otherwise it seems to work very well

2022-07-18 08:36 UTC, ad-daniel commented on src/webots/vrml/WbProtoTreeItem.cpp
> +
```suggestion
```

2022-07-18 08:36 UTC, ad-daniel commented on src/webots/vrml/WbNode.cpp
> +#include "WbProtoTreeItem.hpp"
```suggestion
```

2022-07-18 08:36 UTC, ad-daniel commented on src/webots/vrml/WbNode.cpp
> +#include "WbProtoTreeItem.hpp"
Since we moved `combinePath` to WbUrl, I don't think this import is necessary anymore

2022-07-18 13:29 UTC, BenjaminDeleze commented
Everything seems ok for me

2022-07-18 14:07 UTC, merged