Improve error messages for worlds and protos prior to R2022b
cyberbotics/webots pull request #4920
Opened 2022-07-20 06:52 UTC by ygoumaz

As mentioned in [#4860 (comment)](https://github.com/cyberbotics/webots/pull/4860#issuecomment-1187669542), old worlds don't display the complete list of missing EXTERNPROTO declarations. This PR also makes the distinction between old PROTO files (prior to R2022b) and new ones to show correct warnings.

2022-07-20 13:48 UTC, ad-daniel submitted a review, later dismissed

2022-07-20 14:50 UTC, ad-daniel reviewed
Looks good, only some details. I'll do more extensive checks when https://github.com/cyberbotics/webots/pull/4930 is merged into this PR

2022-07-20 14:50 UTC, ad-daniel commented on src/webots/vrml/WbProtoManager.cpp
> +        .arg(parentFilePath);
I think we can lower the scope of the messages to where they are actually used, no need to define them all when we only show some of them

2022-07-20 14:50 UTC, ad-daniel commented on src/webots/vrml/WbProtoManager.cpp
> +  displayMissingDeclarations(backwardsCompatibilityMessage);
Since here there's just one message, I think we can pass it directly without creating an intermediary variable

2022-07-21 07:16 UTC, ad-daniel commented
From what I've been able to test, the behavior appears to be correct. The general approach is to display the wiki link if R2022a world/protos are detected whereas to display which declarations are missing if the world/protos are from R2022b onward (the reason being, you don't want to have the users do it manually if it involves a multitude of changes). The only case which is only partially handled is if the missing declaration of a PROTO does exist and is on the world side, but although a bit strange it's not entirely wrong either, as the same 2 objects can't have different urls anyway. Whatever the case, if this hanging declaration has no instances, as soon as the world is saved the declaration is purged and from that point what and where it's missing will be shown. It's not ideal but isn't that common an occurrence either, you kinda need to chase for it. The "proper" solution involves removing the check that searches for a declaration in the mExternProto list in findModel function. Doing so solves the issue, but opens up a new one, namely that when you:
1. Insert a node with add-node
2. Don't save the world (so the declaration for the added node exists only in mExternProto list which hasn't been saved yet)
3. Cut the node you just added and attempt to paste it
4. When pasting, findModel has no way of knowing where to find this node, currently it infers it's declaration by searching for one in the mExternProto list.

In short, if the mExternProto check is removed to solve the other "oddity", a solution needs to be found to handle this case which as it stands I don't see a better way.

I think we can merge this PR, and if @stefaniapedrazzi thinks the issues she found have a been addressed, we can merge the other PR into master and a release candidate can be built

2022-07-21 07:25 UTC, omichel commented
> In short, if the mExternProto check is removed to solve the other "oddity", a solution needs to be found to handle this case which as it stands I don't see a better way.

One solution could be to include the EXTERNPROTO url in the cut buffer, so that when we paste a cut PROTO, we can also re-insert the EXTERNPROTO url if needed.

2022-07-25 07:25 UTC, ad-daniel commented
The issue isn't that a declaration (url to the node location) is missing during the cut/paste action, but rather that since findmodel MUST search among the `mExternProto` list for the declaration of inserted nodes (since they aren't saved yet, they're only available there), in some situations such as the one mentioned by Stefania, by allowing the search among ALL the mExternProto declarations (not just the inserted ones), situations that should raise a warning silently don't. In other worlds, it's a matter of priority. Since a match is found in `mExternProto` too early, the declaration doesn't need to be injected by backwards compatibility and therefore a warning isn't shown. The solution is to restrict the search among item  in the `mExternProto` list only to inserted nodes.

2022-07-25 07:54 UTC, omichel requested changes

2022-07-25 07:54 UTC, omichel commented on src/webots/vrml/WbProtoManager.cpp
> +    path = path.replace(WbStandardPaths::webotsHomePath(), "webots://");
```suggestion
    path.replace(WbStandardPaths::webotsHomePath(), "webots://");
```

2022-07-25 07:54 UTC, omichel commented on src/webots/vrml/WbProtoManager.cpp
> +WbVersion WbProtoManager::checkProtoVersion(QString protoUrl, bool *foundProtoVersion) {
```suggestion
WbVersion WbProtoManager::checkProtoVersion(const QString &protoUrl, bool *foundProtoVersion) {
```

2022-07-25 07:54 UTC, omichel commented on src/webots/vrml/WbProtoManager.cpp
> +  if (WbUrl::isWeb(protoDeclaration) && WbNetwork::instance()->isCached(modelPath)) {
```suggestion
  if (WbUrl::isWeb(protoDeclaration) && WbNetwork::instance()->isCached(modelPath))
```

2022-07-25 07:54 UTC, omichel commented on src/webots/vrml/WbProtoManager.cpp
>    } else if (WbUrl::isLocalUrl(protoDeclaration)) {
```suggestion
  else if (WbUrl::isLocalUrl(protoDeclaration)) {
```

2022-07-25 08:09 UTC, omichel approved these changes

2022-07-25 08:12 UTC, merged