Fix convert root to basenode missing declaration
cyberbotics/webots pull request #5014
Opened 2022-08-05 11:54 UTC by ad-daniel

**Description**

Due to the recent changes, declarations added on the fly by the convert root to basenode mechanism no longer work.
Additionally, ambiguous situations should be notified to the user.

2022-08-05 14:53 UTC, ad-daniel commented
Due to the recent change that the extern proto list is purged on every node deletion (rather than just on saves), the declaration of the nodes that will become visible must occur only AFTER the "previous" node (i.e., non converted one) is deleted. Since no instances yet exist of these declarations, deleting the previous node would result in the declarations being purged. I've also fixed this in the PR.

2022-08-05 16:07 UTC, omichel requested changes

2022-08-05 16:07 UTC, omichel commented on src/webots/vrml/WbProtoManager.cpp
> +          WbLog::warning(tr("Conflicting declarations for '%1' are provided: %2 and %3, the first will be used. To use the "
```suggestion
          WbLog::warning(tr("Conflicting declarations for '%1' are provided: %2 and %3, the first one will be used. To use the "
```

2022-08-05 16:07 UTC, omichel commented on src/webots/vrml/WbProtoManager.hpp
> +  void setFromRootNodeConversion(bool value) { mFromRootNodeConversion = value; }
Since it is always called with a `false` parameter, should probably remove the parameter and rename the method.

2022-08-08 08:06 UTC, omichel approved these changes
Thank you.

2022-08-08 08:17 UTC, merged