Fix search of relative assets in derived nodes
cyberbotics/webots pull request #5071
Opened 2022-08-12 13:40 UTC by ad-daniel

**Description**

Assets relative to a PROTO are determined based on the visibility of the field in question. For nested PROTO, following the aliases allows to determine the scope of a field and therefore relative to which PROTO it must be resolved.
This method however falls flat when derived PROTO are concerned because in the process of building these PROTO nodes, all intermediary nodes are instantiated only temporarily, so notions of visibility can't be relied upon as no contiguous chain of aliases exists anymore.

With this PR, a map of "IS" connections (between the exposed parameter and the internal field) is kept at the PROTO model level so that it's possible to follow this chain by jumping through consecutive ancestors in the derived PROTO chain.

2022-08-12 13:44 UTC, BenjaminDeleze commented
With a bit of luck it will also fix #5028 !

2022-08-12 13:49 UTC, ad-daniel commented
> With a bit of luck it will also fix #5028 !

eheh, no such luck unfortunately, this issue/fix is just related to derived PROTO, it doesn't touch the visibility condition

2022-08-12 15:29 UTC, omichel requested changes

2022-08-12 15:29 UTC, omichel commented on src/webots/vrml/WbProtoModel.hpp
> +  void verifyNodeAliasing(WbNode *node, WbFieldModel *param, WbTokenizer *tokenizer, bool searchInParameters, bool &ok);
I would rename these functions to `setupAliasing` and `setupNodeAliasing` as the `verify` prefix is a bit misleading (they also construct the parameter alias map).

2022-08-15 07:57 UTC, omichel approved these changes
Thank you.

2022-08-15 08:37 UTC, merged