New Rosbot PROTO with associated devices PROTOs
cyberbotics/webots pull request #5168
Opened 2022-09-02 12:52 UTC by ygoumaz

Implementation of the `ROSbot` PROTO in Webots.

The robot embeds the following sensors which are also created as PROTO files:
- `Astra` RGBD Camera.
- `RpLidar A2` Lidar.
- `MPU-9250` Inertial Measurement Unit (IMU).

2022-09-16 09:42 UTC, omichel commented
As a quick first review, it seems that some meshes are too much faceted. We should smooth them. I believe this can be done in Blender on the OBJ files.

2022-09-16 12:37 UTC, ygoumaz commented
obj files now all have a smooth shading applied to them.

2022-09-16 15:13 UTC, omichel commented
> .obj files now all have a smooth shading applied to them.

Thank you, that's nice. However, I still have a few comments on the 3D models, like the wheels now look weird, the connectors should have a different color from the body, etc. However, I believe it is simpler that I show them to you one-by-one.

2022-09-22 09:24 UTC, ygoumaz commented
The PR is again ready for review. The ROSbot PROTO has been significantly improved visually. Any feedback to improve the documentation and the sample world is welcome.

2022-09-22 10:30 UTC, omichel commented
It looks very good to me, thank you. I just noticed strange triangle patterns on the red body of the robot which was not present in the previous version I believe:
![rosbot](https://user-images.githubusercontent.com/1264964/191724146-fc23ccc7-f676-4bb8-9ed6-62ec5abcc699.png)
Could this be caused by the modified UV mapping?

2022-09-22 13:19 UTC, ygoumaz commented
I fixed the reflection problem on the top red part of the robot. I also applied the same solution to the wheel rims and it improved a lot the mapping of the aluminium visually.

The solution is to select all the corresponding faces of the Mesh in Blender and to "UV unwrap faces". It allows to apply the mapping to all faces rather than to each triangle separately.

2022-09-23 08:56 UTC, omichel commented
It looks very nice now. Thank you.
There are still pending comments on this PR to be addressed.

2022-09-27 09:02 UTC, omichel requested changes

2022-09-27 09:58 UTC, omichel requested changes

2022-09-27 09:58 UTC, omichel commented on projects/devices/orbbec/protos/Astra.proto
> +# Model of the Astra RGBD Camera developed by Orbbec.
```suggestion
# Model of the Astra RGBD camera developed by Orbbec.
```

2022-09-27 09:58 UTC, omichel commented on projects/robots/husarion/rosbot/controllers/rosbot/rosbot.c
> +  double coefficients[2][2] = {{15.0, -9.0}, {-15.0, 9.0}};
```suggestion
  const double coefficients[2][2] = {{15.0, -9.0}, {-15.0, 9.0}};
```

2022-09-27 09:58 UTC, omichel commented on projects/robots/husarion/rosbot/controllers/rosbot/rosbot.c
> +  /* camera RGBD */
```suggestion
  /* RGBD camera */
```

2022-09-27 09:58 UTC, omichel commented on projects/robots/husarion/rosbot/controllers/rosbot/rosbot.c
> +  double base_speed = 6.0;
```suggestion
  const double base_speed = 6.0;
```

2022-09-27 09:58 UTC, omichel commented on projects/robots/husarion/rosbot/controllers/rosbot/rosbot.c
> +   * control). */
```suggestion
  /* get a handler to the motors and set target position to infinity (speed control). */
```

2022-09-27 14:17 UTC, omichel submitted a review, later dismissed
Thank you. Everything looks good to me now.

2022-09-27 15:06 UTC, ygoumaz commented
Some `WorldInfo` fields of the sample world were not correct.

2022-09-27 15:22 UTC, omichel approved these changes
:+1:

2022-09-27 15:35 UTC, merged