added section to correct corners that are separated by commas instead…
cyberbotics/webots pull request #5243
Opened 2022-09-19 14:17 UTC by RugnirViking

… of newlines

**Description**
Encountered an issue in which when upgrading some SimpleBuildings were converted correctly but others appeared flipped. upon investigation it was found that those SimpleBuildings were using comma separated vectors for its corners instead of newline separated like the script expects. This PR goes through and changes any comma-separated lists of corners into newline separated before the file is parsed by the main script

**Additional context**
Persuant to a conversation had in the webots discord on 19th september 2022

2022-09-19 15:32 UTC, stefaniapedrazzi requested changes
Thank you for this fix!
I tested it and it seems to work fine.

If possible it would be better to avoid duplicating the loop through the file and apply all the changes directly the already existing loop.

2022-09-19 15:32 UTC, stefaniapedrazzi commented on scripts/converter/convert_nue_to_enu_rub_to_flu.py
> +
```suggestion

```

2022-09-19 15:32 UTC, stefaniapedrazzi commented on scripts/converter/convert_nue_to_enu_rub_to_flu.py
> +                print(line, end ='')
```suggestion
                print(line, end='')
```

2022-09-19 15:32 UTC, stefaniapedrazzi commented on scripts/converter/convert_nue_to_enu_rub_to_flu.py
> +                # fix for issue where corners are comma separated
```suggestion
                # split coordinates separated by commas on new lines
```

2022-09-19 15:32 UTC, stefaniapedrazzi commented on scripts/converter/convert_nue_to_enu_rub_to_flu.py
> +                        print(vector)
The new lines are not correctly aligned.
In this file there is the `add_space` function that is used to compute the spaces needed to correctly align the values.

2022-09-20 08:39 UTC, RugnirViking commented
I have made it so that the vectors are padded correctly, I had a go at putting everything into the single loop but it wasn't working quite right and I need to get back to work @stefaniapedrazzi

2022-09-20 10:13 UTC, stefaniapedrazzi requested changes
Thank you for fixing the alignment!

There is still just a minor coding style detail to fix then this PR is ready to be merged.

2022-09-20 10:13 UTC, stefaniapedrazzi commented on scripts/converter/convert_nue_to_enu_rub_to_flu.py
> +                        print(add_space(line)+vector.strip())
```suggestion
                        print(add_space(line) + vector.strip())
```

2022-09-21 06:26 UTC, omichel commented
@RugnirViking: I just sent you an invite to become a member of the Webots-committers group so that you should be to merge your PR directly and create new PRs on the cyberbotics repos.

2022-09-26 06:36 UTC, stefaniapedrazzi approved these changes
Thank you!

2022-09-26 08:17 UTC, merged