Improve PROTO web loader
cyberbotics/webots pull request #5314
Opened 2022-10-10 12:00 UTC by ad-daniel

**Description**
Ditto.

2022-10-25 11:23 UTC, BenjaminDeleze requested changes
Seems good, just some minor remarks:

2022-10-25 11:23 UTC, BenjaminDeleze commented on resources/web/wwi/protoVisualizer/Tokenizer.js
> +    }
Seems like it could be combine in one `if`

2022-10-25 11:23 UTC, BenjaminDeleze commented on resources/web/wwi/protoVisualizer/Parameter.js
> +    this.value.setValueFromJavaScript(v);
Not sure if inside the class we should use the `getter` or directly access the attribute with `this.#value`. Personally I would tend to access directly the value.

2022-10-25 13:20 UTC, ad-daniel commented on resources/web/wwi/nodes/utils/id_provider.js
> +}
probably not anymore, if yes I'll re-add it later

2022-10-26 06:17 UTC, BenjaminDeleze approved these changes
Seems good to me

2022-10-26 06:22 UTC, merged