Implement first use case of webots.cloud/proto
cyberbotics/webots pull request #5376
Opened 2022-10-27 07:39 UTC by BenjaminDeleze

A user needs a new size of `SoccerBall.proto`
A competition organizer want to develop a soccer competition. It founds the `SoccerBall.proto` in Webots, however the size is a bit too small to work well with the robots he plans to use as players.

He has four solutions to fix his problem:

1. Recreate a new proto from scratch.
2. Edit the `.proto` in a text editor.
3. Use the proto wizard.
4. Use the proto editor of `webots.cloud.

Solution 1 requires some knowledge about how to write proto and this user does not have time to learn them.
Solution 2 is a bit simpler but also require a minimum of knowledge and the interface is not very user-friendly.
Solution 3 is good, but solution 4 is better because the user can see the effect of its modifications in real-time in the viewer of webots.cloud.

For solution 4 to work, it needs:
  - [ ] A window to change the radius
     - [ ] display `radius` and an `input` field.
     - [ ] WebotsJS must support `radius` update.
     - [ ] Changing the `radius` must change the visual result.
  - [ ] A download button to download the proto with the modified radius.
  - [ ] Have a nice user interface:
    - [ ] The proto parameter must be open and well positioned when the user first open the proto
    - [ ] The download button shoud be displayed
    - [ ] The reset button must be implemented to restore the state of the field `radius`

2022-10-28 07:07 UTC, omichel requested changes
It is not possible to set a name for the saved proto, it is named CustomProto.
The name field has quotes, e.g., `"`. I believe they should be removed.
The "reset to default value" button should have a tooltip.
The layout should align the field name and field values (e.g., table). I believe that would be more readable especially when the number of exposed parameters is high.

2022-10-28 07:28 UTC, omichel commented
Also, I believe we could add a "Download World" button that would download a world file that includes the original proto with the parameters currently set by the user (as well as a light, floor, etc. to match the web view).

Also, maybe the "Download Proto" button could be renamed to "Download Derived Proto", which sounds clearer to me.

2022-10-28 08:20 UTC, BenjaminDeleze commented
> It is not possible to set a name for the saved proto, it is named CustomProto.

The decision to open or not the `save as` pop up is taken by the browser so we can really control it. 
User can force their browser to always open the pop up (for example in `Firefox`: `settings/Always ask you where to save files`)

There is one solution to that, it is to use the [File System Access API](https://web.dev/file-system-access/#create-a-new-file). However this feature is quite new and even if is supported in most Chromium base browsers (to some extend), it is on the technology preview step on Safari and not available at all on Firefox. (https://caniuse.com/native-filesystem-api), so I am not totally convinced.

Another solution would be to make a custom field/pop up where the user could choose the name (but not the location) of the file she wants to save.

> The layout should align the field name and field values (e.g., table). I believe that would be more readable especially when the number of exposed parameters is high.

Should the reset buttons also be align or should they be at the end of the field?

> Also, I believe we could add a "Download World" button that would download a world file that includes the original proto with the parameters currently set by the user (as well as a light, floor, etc. to match the web view).

I am not convinced that it is really useful.

2022-10-28 13:45 UTC, BenjaminDeleze commented
I think I fixed all the reported issues.

In addition I removed the custom tool-tips to replace them by the browser provided ones.

2022-10-31 11:21 UTC, omichel reviewed
I suggested a few const declarations and comments clean-up. Not sure this is relevant. Let me know.

2022-10-31 11:21 UTC, omichel commented on resources/web/wwi/ProtoManager.js
> +      // setTimeout(() => this.demoFieldChange('rotation', {x: 0, y: 0, z: 1, a: 0.785}), 2000);
Can we remove these now?
```suggestion
```

2022-10-31 11:21 UTC, omichel commented on resources/web/wwi/ProtoManager.js
> +      // setTimeout(() => this.exportProto(), 4000);
```suggestion
```

2022-10-31 11:21 UTC, omichel commented on resources/web/wwi/FloatingProtoParameterWindow.js
> +    let string = parameter.value.value;
```suggestion
    const string = parameter.value.value;
```

2022-10-31 11:21 UTC, omichel commented on resources/web/wwi/FloatingProtoParameterWindow.js
> +    let object = {'x': node.inputs[0].value, 'y': node.inputs[1].value, 'z': node.inputs[2].value};
```suggestion
    const object = {'x': node.inputs[0].value, 'y': node.inputs[1].value, 'z': node.inputs[2].value};
```

2022-10-31 11:21 UTC, omichel commented on resources/web/wwi/FloatingProtoParameterWindow.js
> +    let object = {'x': node.inputs[0].value, 'y': node.inputs[1].value, 'z': node.inputs[2].value, 'a': node.inputs[3].value};
```suggestion
    const object = {'x': node.inputs[0].value, 'y': node.inputs[1].value, 'z': node.inputs[2].value, 'a': node.inputs[3].value};
```

2022-10-31 12:45 UTC, omichel approved these changes
Thank you.

2022-10-31 12:56 UTC, merged