Add support for SFNode editing in Web PROTO
cyberbotics/webots pull request #5435
Opened 2022-11-08 10:38 UTC by ad-daniel

**Description**

- [ ] list SFNode parameters in the interface
- [ ] add compatibility filter mechanism (slot type, robot ancestors, ...)
- [ ] handle insertion in node structure
   - [ ] add library mechanism to choose PROTO from
   - [ ] generate and/or load meta-data (from proto-list.xml?) 
   - [ ] handle insertion in the node-structure (and js notification)
   - [ ] ?

2022-12-20 15:54 UTC, BenjaminDeleze requested changes
Works well in general, just some remarks:

- When `no nodes match the criteria`, the text is stuck against one side, it would be nicer if it had some space.
- In the configuration window of SFNode, it would nicer if the left margin was bigger.
- Not sure if related with this PR, but when changing the string of some PBRAppearances, lets say I put `top` instead of `back` for the `cardboard`  type, an error is thrown: 
```Requested deletion of node that does not exist```
- Personally, I would inverse the order of the icons: first the configure and then the delete.
- The state of the reset buttons is not saved when moving back and forth in protos
- The download name is not saved when going in subproto
- When trying with the Nao, it finds nothing to suggest for the `jersey` field whereas the `NaoJersey` should be suggested.
- This PR breaks the streaming viewer, the animations and the documentation.
- Not sure if introduced in this PR but it seems that the objects are not always correctly cleaned:
  - go in `https://proto.webots.cloud/run?version=proto&url=https://github.com/BenjaminDeleze/sandbox/blob/master/protoExample/protos/OfficeChair.proto`
  - change enable physics to FALSE
  - Click on webots.cloud to go back to the main menu
  - Load the nao proto
  - Both the nao and the office chair are in the scene

2022-12-20 15:54 UTC, BenjaminDeleze commented on resources/web/wwi/FloatingProtoParameterWindow.js
> +      'z': parseFloat(node.inputs[2].value), 'a': parseFloat(node.inputs[3].value)};
I got this warning: 
` Object properties must go on a new line if they aren't all on the same line. (object-property-newline)`

2022-12-20 15:54 UTC, BenjaminDeleze commented on resources/web/wwi/NodeSelectorWindow.js
> +      xmlhttp.onreadystatechange = async () => {
```suggestion
      xmlhttp.onreadystatechange = async() => {
```

2022-12-20 15:54 UTC, BenjaminDeleze commented on resources/web/wwi/NodeSelectorWindow.js
> +    p.style.margin = 'auto 10px auto 0px'
```suggestion
    p.style.margin = 'auto 10px auto 0px';
```

2022-12-20 15:54 UTC, BenjaminDeleze commented on resources/web/wwi/NodeSelectorWindow.js
> +        this.selection = ol.children[compatibleNodes.indexOf(this.parameter.value.value.name)]
```suggestion
        this.selection = ol.children[compatibleNodes.indexOf(this.parameter.value.value.name)];
```

2022-12-20 15:54 UTC, BenjaminDeleze commented on resources/web/wwi/NodeSelectorWindow.js
> +
```suggestion
```

2022-12-20 15:54 UTC, BenjaminDeleze commented on resources/web/wwi/NodeSelectorWindow.js
> +    button.ondblclick = async (item) => this.insertNode(item.target.innerText);
```suggestion
    button.ondblclick = async(item) => this.insertNode(item.target.innerText);
```

2022-12-20 15:54 UTC, BenjaminDeleze commented on resources/web/wwi/NodeSelectorWindow.js
> +      license.innerHTML = 'License:&nbsp;<i>' + info.license + '</i>'
```suggestion
      license.innerHTML = 'License:&nbsp;<i>' + info.license + '</i>';
```

2022-12-20 15:54 UTC, BenjaminDeleze commented on resources/web/wwi/NodeSelectorWindow.js
> +      throw new Error('The parameter is expected to be defined prior to checking node compatibility.')
```suggestion
      throw new Error('The parameter is expected to be defined prior to checking node compatibility.');
```

2022-12-20 15:54 UTC, BenjaminDeleze commented on resources/web/wwi/NodeSelectorWindow.js
> +      throw new Error('Cannot display node selector unless a parameter is provided.')
```suggestion
      throw new Error('Cannot display node selector unless a parameter is provided.');
```

2022-12-20 15:54 UTC, BenjaminDeleze commented on resources/web/wwi/Parser.js
> +        parentNode.children.push(viewpoint);
I think that `parentNode`  is not defined

2022-12-20 15:54 UTC, BenjaminDeleze commented on resources/web/wwi/ProtoManager.js
> +import WbWorld from './nodes/WbWorld.js';
```suggestion
```

2022-12-20 15:54 UTC, BenjaminDeleze commented on resources/web/wwi/WebotsView.js
> +    return new Promise(function (resolve, reject) {
```suggestion
    return new Promise(function(resolve, reject) {
```

2022-12-20 15:54 UTC, BenjaminDeleze commented on resources/web/wwi/X3dScene.js
> -      const ancestor = getAncestor(parentNode);
we can remove the `getAncestor` import

2022-12-20 15:54 UTC, BenjaminDeleze commented on resources/web/wwi/X3dScene.js
> +    xmlhttp.onreadystatechange = async () => {
```suggestion
    xmlhttp.onreadystatechange = async() => {
```

2022-12-20 15:54 UTC, BenjaminDeleze commented on resources/web/wwi/X3dScene.js
> +      node.finalize()
```suggestion
      node.finalize();
```

2022-12-20 15:54 UTC, BenjaminDeleze commented on resources/web/wwi/nodes/WbPbrAppearance.js
> +      customID = getAnId()
```suggestion
      customID = getAnId();
```

2022-12-20 15:54 UTC, BenjaminDeleze commented on resources/web/wwi/nodes/WbShape.js
> +
```suggestion
```

2022-12-20 15:54 UTC, BenjaminDeleze commented on resources/web/wwi/protoVisualizer/Node.js
> +    for (const [parameterName, parameter] of this.parameters)
```suggestion
    for (const [, parameter] of this.parameters)
```
Is this working? that is what my linter is suggesting

2022-12-20 15:54 UTC, BenjaminDeleze commented on resources/web/wwi/protoVisualizer/Parameter.js
> +      const id = this.node.getBaseNode().id; // delete existing node (must be done prior to regeneration or the information is lost)
Line too long

2022-12-20 15:54 UTC, BenjaminDeleze commented on resources/web/wwi/protoVisualizer/Vrml.js
> +    if (v.a === NaN)
We should use the `isNaN()` function to compare with NaN

2023-01-05 14:54 UTC, ad-daniel commented
I believe all points have been addressed, I've uploaded the files to the server

2023-01-05 16:11 UTC, BenjaminDeleze requested changes
Good job! most of the issues are indeed fixed, but I could still find some:

- TextureTransform of the proto parameters has its `resetButton` enable and it throws an error when clicking on the reset button
- When streaming and adding an object to the scene, nothing appears and I get to following error: ```parentNode is undefined at x3dScene.js:182```
  -  I get the same error and the object disappear when modifying a regenerating parameter
  -   Same error when reseting the `spot.wbt` world 
- I experimented a bit with the Tinkerbots (I added it on proto.webots.cloud), and even if I am 2 or 3 levels down in subnodes, the `back` button bring me back to the root? Is it the wanted behavior?
- When adding several levels of subprotos, only the first levels (so parameters of the root) are added as externProto, other are not.

2023-01-05 16:11 UTC, BenjaminDeleze commented on resources/web/wwi/FloatingProtoParameterWindow.js
> +    input.onchange = (e) => this.exportName = e.target.value;
I saw that you removed the `My` prefix.
I added it to avoid conflicts with the base proto and also to show that the user can modify the name

2023-01-06 09:19 UTC, ad-daniel commented
> TextureTransform of the proto parameters has its resetButton enabled

It's the correct behavior, it's flagged as modified in webots too. The reason is that OfficeChair defines the field as `seatAppearance  Leather { textureTransform TextureTransform { scale 10 10 } }`, so the the `textureTransform` field is non-default with respect to Leather. I've fixed the behavior when clicking the reset button, which was indeed wrong.

> I experimented a bit with the Tinkerbots (I added it on proto.webots.cloud), and even if I am 2 or 3 levels down in subnodes, the back button bring me back to the root?

This was the intended behavior as when discussing with Olivier we agreed this was good enough for now, we care more about the root after all. In the case of the tinkerbots however the layers can get big fairly quickly, so I've changed it and now it returns back up one level instead. We'll need it later one either way, so might as well

2023-01-06 11:43 UTC, BenjaminDeleze requested changes
I observed the two following bugs in streaming, however, they are also present in Master so I think we should fix them later and not in this PR:
  - When adding a jersey to a nao it does not work.
  - I the regeneration of the nao is triggered, the updates do not work anymore.

2023-01-06 11:43 UTC, BenjaminDeleze commented on resources/web/wwi/X3dScene.js
> +      this.loadObject(data, parentId === "0" ? WbWorld.instance.root.id.replace('n', '') : parentId);
```suggestion
      this.loadObject(data, parentId === '0' ? WbWorld.instance.root.id.replace('n', '') : parentId);
```

2023-01-06 12:48 UTC, ad-daniel commented
should probably open an issue about them or they might be forgotten

2023-01-06 12:55 UTC, BenjaminDeleze approved these changes
Good job!

2023-01-06 13:02 UTC, merged