Fix north in worlds imported from OpenStreetMap
cyberbotics/webots pull request #5795
Opened 2023-01-27 17:35 UTC by fparat

**Description**
A world imported from an OpenStreetMap file has the axis Y to the east and X to the south.
This patch fixes the importer script to have Y to the north and X to the east

Example for this random location: https://www.openstreetmap.org/export#map=15/48.0048/1.6344

Before:
![tournoisis_world](https://user-images.githubusercontent.com/15631473/215154442-aa6ddb99-8217-4067-b676-a4ed24b9afb9.png)

After:
![tournoisis_world_fixed](https://user-images.githubusercontent.com/15631473/215154471-bd3a93ab-5f62-40cf-a504-40f128548a6d.png)

**Related Issues**
N.A.

**Tasks**
N.A.

**Documentation**
N.A.

**Screenshots**
N.A.

**Additional context**
I had trouble to put some inclination to the viewpoint, so I used View > Change View > Top View to get the new values.

2023-01-30 07:25 UTC, omichel requested changes
Thank you for this nice contribution.
I have a request for some simplification in your code.

2023-01-30 07:25 UTC, omichel commented on resources/osm_importer/utils/misc_utils.py
> +    file.write("  position " + "0" + " 0 " + str(position) + "\n")
```suggestion
    file.write("  position 0 0 " + str(position) + "\n")
```

2023-01-30 09:29 UTC, stefaniapedrazzi commented
The changes to the coordinate system of the worlds imported from OSM was changed on purpose to be consistent with the new global coordinate system (ENU) used in Webots since version R2022a.
These changes were introduced in  #1643:
* `projection.py`: https://github.com/cyberbotics/webots/pull/1643/files#diff-e61ad3409535312f1f34fdbc7c663beea73cd513c93a6e03ecd42bc729f51eb4
* `misc_util.py`:https://github.com/cyberbotics/webots/pull/1643/files#diff-806a12a552161fa136924a632fa0b336b0e9bff4048fda655d011a3c12f3b49d

Since Webots R2022a it is strongly suggested to use ENU as global coordinate system for new simulations.

@fparat: could you please further explain why would you like to revert back the orientation of the importer OSM world to the former NUE coordinate system?
Do you have any particular issue with the ENU global coordinate system?

2023-02-05 16:30 UTC, fparat commented
This fix intends to respect the ENU system.

In my example you can see that without the fix the objects are placed with X=south Y=east and Z=up.

With the fix, X=East, Y=North and Z=Up.

Maybe there was a regression since #1643, or maybe I am changing the wrong code, in which case I would need some pointers on which part to fix.

2023-02-06 08:46 UTC, stefaniapedrazzi reviewed
You are right!
I just tested and the imported world is not oriented correctly.
So the fix is fine.

About the Viewpoint settings, maybe we could restore a similar view as before using values like the following ones.
```
    file.write("Viewpoint {\n")
    file.write("  orientation -0.3922 0.3922 0.8321 1.7536\n")
    ...
    file.write("  position 0 " + str(-position * 0.85) + " " + str(position) + "\n")
```
Would that work for your use case?

2023-02-06 21:10 UTC, fparat commented
I updated the branch with your settings, it is nicer than the top view. 

![tournoisis_world_fixed_reviewed](https://user-images.githubusercontent.com/15631473/217088293-abacb2f6-3892-401e-a329-3e91ec8b122e.png)

2023-02-08 16:12 UTC, omichel approved these changes
Thank you.

2023-02-09 09:23 UTC, merged