Fix web proto issues related to vehicles
cyberbotics/webots pull request #5811
Opened 2023-01-31 16:29 UTC by ad-daniel

**Description**

- [x] Fix Slot issues prevent loading of vehicles
- [x] Improve vehicle loading time ==> Tesla now loads in ~3 seconds rather than ~15
- [x] Fix updating of image texture urls in webotsjs
- [ ] Fix vehicle lights being in the wrong place

2023-02-01 15:43 UTC, BenjaminDeleze requested changes
The bounding objects are too big

2023-02-01 15:43 UTC, BenjaminDeleze commented on resources/web/wwi/Parser.js
>        parentNode.children.push(spotLight);
Do we really want to push `undefined` as children?

2023-02-02 08:41 UTC, ad-daniel commented
All issues should be addressed now, I've uploaded to the server and this time I actually committed the BO fix to the branch, not just on the server :sweat_smile:

2023-02-02 09:23 UTC, BenjaminDeleze commented
I confirm that the previous issues are fixed.

I found a new one but I am not sure it's related to this PR:
When there is a node in the extension slot of the nao or tesla we cannot download the model

2023-02-02 09:59 UTC, ad-daniel commented
Yes it isn't related to this PR but it should work now.

2023-02-02 10:35 UTC, BenjaminDeleze commented
Did you push the fix to the server? Because I can still reproduce the issue.

I found another as well:
I cannot add anything in the hand slots of the `Nao` whereas in Webots any node can fit.
(If you want to merge this PR and handle the new issues later in another one, we can)

2023-02-02 13:27 UTC, ad-daniel commented
> Did you push the fix to the server? Because I can still reproduce the issue.

No, it was local only.

> I cannot add anything in the hand slots of the Nao whereas in Webots any node can fit.

The issue was introduced when removing the proto-list.xml, the check only looked at the first IS link (which in itself is fine), but it didn't go full depth down to the base node. In the case of the Nao, the hands are a separate PROTO and the IS chain is longer.

I've fixed it and pushed files to the server

2023-02-02 13:44 UTC, BenjaminDeleze approved these changes
Thank you! well done!

2023-02-02 13:47 UTC, merged