Update changelog to reflect PR 5792 and 5796.
cyberbotics/webots pull request #5812
Opened 2023-01-31 17:35 UTC by brettle

Forgot to include these updates in those PRs.

2023-02-01 07:30 UTC, ad-daniel submitted a review, later dismissed
Indeed, thank you

2023-02-01 07:34 UTC, stefaniapedrazzi requested changes

2023-02-01 07:34 UTC, stefaniapedrazzi commented on docs/reference/changelog-r2023.md
> +    - Fixed thread-safety issue when robots collide. ([#5796](https://github.com/cyberbotics/webots/pull/5796))
I would also specify that this error could occur only if physics multi-threading is enabled (note that this is disabled by default and not many users are enabling it)
```suggestion
    - Fixed thread-safety issue when robots collide ([#5796](https://github.com/cyberbotics/webots/pull/5796)).
```

2023-02-01 14:34 UTC, brettle commented on docs/reference/changelog-r2023.md
> +    - Fixed thread-safety issue when robots collide ([#5796](https://github.com/cyberbotics/webots/pull/5796)).
```suggestion
    - Fixed thread-safety issue when robots collide. This was only an issue if physics multi-threading was enabled (which is not the default and rarely used) ([#5796](https://github.com/cyberbotics/webots/pull/5796)).
```

2023-02-02 07:40 UTC, stefaniapedrazzi approved these changes
Thank you!

2023-02-02 11:59 UTC, merged