Allow cache tests to be run from a local branch
cyberbotics/webots pull request #5824
Opened 2023-02-02 06:40 UTC by brettle

**Description**
Allow cache tests to be run from a local branch.

**Additional context**
Before this change, the cache tests retrieved the files from GitHub under the branch that the user was in. However, when working on PRs on a local branch, this caused the cache tests to fail because the branch was not yet (and might never be) in the official repo.

2023-02-02 07:20 UTC, ad-daniel requested changes
This should indeed fix the issue when running it locally and doesn't change the test itself, so works for me. @stefaniapedrazzi what do you think?

2023-02-02 07:20 UTC, ad-daniel commented on tests/cache/cache_environment.py
> +    print(f'Assuming branch {BRANCH} does not exist in the cyberbotics webot repo.')
```suggestion
    print(f'Assuming branch {BRANCH} does not exist in the cyberbotics Webots repo.')
```

2023-02-02 10:49 UTC, brettle commented
@stefaniapedrazzi can you provide details on your environment and the exceptions you're seeing?

Note that you need remote named "upstream" that refers to the cyberbotics webots repo on GitHub.

2023-02-02 11:10 UTC, stefaniapedrazzi commented
I created a local branch named "test_suite_cache" based on `origin/develop` and edited the `resources/branch.txt` file so that I'm sure that the current branch used in the test_suite is the local one (this can also be updated running `scripts/get_git_info/get_git_info.sh`).
This is the common use case where I would expect the test_suite to fail because the corresponding remote branch it not found.

These are the error messages printed in the console:
```
Unable to access https://raw.githubusercontent.com/cyberbotics/webots/test_suite_changes/README.md.
Assuming branch test_suite_changes does not exist in the cyberbotics webot repo.
Traceback (most recent call last):
  File "/home/stefi/webots/tests/cache/cache_environment.py", line 46, in <module>
    with urllib.request.urlopen(test_url) as response:
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stefi/webots/tests/./test_suite.py", line 34, in <module>
    from cache.cache_environment import update_cache_urls
  File "/home/stefi/webots/tests/cache/cache_environment.py", line 52, in <module>
    BRANCH = subprocess.run(["git", "merge-base", "HEAD", "upstream/develop", "upstream/master"],
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'merge-base', 'HEAD', 'upstream/develop', 'upstream/master']' returned non-zero exit status 128.
```

2023-02-02 11:54 UTC, brettle commented
Thanks @stefaniapedrazzi. The issue was that you didn't have a remote named "upstream". I've fixed the code to look for the appropriate remote. Should work for you now.

2023-02-02 11:57 UTC, brettle commented
> I'm just wondering if we really need to add the complexity to search for a valid branch or we could simply skip the cache tests.

That would hinder development related to caching on a local branch and for developers who can't create a branch on the official github repo.

2023-02-03 13:22 UTC, brettle commented
One of the tests [failed](https://github.com/cyberbotics/webots/actions/runs/4082308814/attempts/1), so I'm rerunning it. I suspect it's an intermittent failure unrelated to this PR.

2023-02-03 13:25 UTC, brettle commented
GitHub [seems](https://github.com/cyberbotics/webots/actions/runs/4082308814/jobs/7041334196) to be having some network issues. That would probably explain the previous error as well.

2023-02-06 08:05 UTC, ad-daniel commented
On a local branch I'm encountering the same issue reported by Stefania even after the change you made:
```
Unable to access https://raw.githubusercontent.com/cyberbotics/webots/test-branch/README.md.
Assuming branch test-branch does not exist in the github.com/cyberbotics/webots.git repo.
Finding a remote that refers to github.com/cyberbotics/webots.git.
Traceback (most recent call last):
  File "/home/daniel/webots_master/tests/cache/cache_environment.py", line 46, in <module>
    with urllib.request.urlopen(test_url) as response:
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tests/test_suite.py", line 33, in <module>
    from cache.cache_environment import update_cache_urls
  File "/home/daniel/webots_master/tests/cache/cache_environment.py", line 55, in <module>
    remote = next(filter(lambda line: repo in line, remotes.splitlines())).split("\t")[0]
StopIteration
```

2023-02-06 08:46 UTC, brettle commented
@ad-daniel, do you not have any remotes? What does `git remote -v` print for you? Also, what OS are you using?

2023-02-06 09:12 UTC, ad-daniel commented
I do, perhaps it's related to ssh authentication, the URL is different
```
origin	git@github.com:cyberbotics/webots.git (fetch)
origin	git@github.com:cyberbotics/webots.git (push)
```
I'm on Ubuntu 20

2023-02-06 09:17 UTC, brettle commented
Yep. That would do it. Should work now.

2023-02-06 09:21 UTC, ad-daniel approved these changes
It works indeed, thank you!

2023-02-07 09:00 UTC, merged