Add BaseNode support to web PROTO
cyberbotics/webots pull request #5878
Opened 2023-02-10 17:01 UTC by ad-daniel

**Description**

- [x] Handle boundingObjects (and all variants like `Box {}`, `Transform { Box {} }`, `Group { Shape { Box {} } }`, ...) 
- [ ] Show compatible BaseNodes in node selector window
   - [x] Physics
   - [x] Damping
   - [x] ImmersionProperties
   - [x] BoundingObject
   - [x] Appearance/PBRAppearance
   - [x] Geometries
   - [ ] ??
- [ ] Add node info (icon + description) when a base-node is selected in the selector window
- [ ] Add hasShapeAncestor method for more complex node structures (ex: to a Solid children field add a Shape node, then a PBRAppearance, then an ImageTexture => the addition of the ImageTexture needs to trigger a unfinalize/finalize of the Shape)
- [ ] Test if BaseNode insertion rules are the same as on Webots
- [ ] Cleanup

2023-02-20 13:11 UTC, BenjaminDeleze commented
This PR will break the display of some protos, namely: `teapot.proto` and ` TorusBoundingObject.proto`.
It is because they are either geometry or bounding objects.

Note: I think this PR is doing the right thing and should not be modified to support again those protos. However, once this PR is merged we should thing on how we want to display pure BO or geometry on webots.cloud

2023-02-22 16:38 UTC, ad-daniel commented
where should I upload the files now that feature-web-proto was merged?

2023-02-22 16:39 UTC, ad-daniel commented
@BenjaminDeleze

2023-02-23 06:37 UTC, BenjaminDeleze commented
You can put them on testing such that we can test on testing.webots.cloud

2023-02-24 08:20 UTC, ad-daniel commented
note: testing.webots.proto doesn't have much in terms of PROTO, that's why when the node selection window is opened very few are shown.

2023-02-24 14:54 UTC, BenjaminDeleze requested changes
I played a bit with it and it is really impressive!

So far I encounter two errors:

- When I try to add a textureTransform to an appearance Proto (grass for example):
```
The parent field should be defined when attempting a node insertion.
```

- When resetting a MfField inside a base node:
```
tokenizer.rewind is not a function
``` 
and after that the `+` button does not work.

- Nothing can be inserted in `rotatingHead` of `Lidar` (not directly related with this PR)

2023-02-24 14:54 UTC, BenjaminDeleze commented on resources/web/wwi/NodeSelectorWindow.js
> +      // don't display PROTO nodes which have been filtered-out by the user's "filter" widget
```suggestion
      // don't display base nodes nodes which have been filtered-out by the user's "filter" widget
```

2023-02-24 14:54 UTC, BenjaminDeleze commented on resources/web/wwi/protoVisualizer/test_proto_viewer.html
> +  webotsView.loadProto("https://raw.githubusercontent.com/ad-daniel/prefab/master/protoExamples/protos/SolidWithAShape.proto")
I think we should revert that

2023-02-24 15:50 UTC, ad-daniel commented
I think I've addressed all the issues, including the Lidar one

2023-02-27 07:14 UTC, BenjaminDeleze approved these changes
Thank you!

2023-02-27 07:23 UTC, merged