Make supervisor_export_image test image content.
cyberbotics/webots pull request #5887
Opened 2023-02-14 03:09 UTC by brettle

Use exported image as a texture and do a basic check for correctness.

I'm also experiencing some strange behavior with image export on my local machine and this is a way to figure out whether it also happens during CI.

2023-02-14 08:11 UTC, stefaniapedrazzi reviewed
It is good to also test the content of the exported image.
Camera image colors might slightly differ due to the differences in the graphics card.
The test is still failing because of the move handles that are displayed for the selected object.
The selection should be disabled from the supervisor by selecting for example the Viewpoint or the WorldInfo node or it could be set in the WBPROJ file (that in this particular case will have to be committed to the repo).
In the WBPROJ file you simply have to add the line:
```
userInteractions: selectionDisabled
```

Meanwhile, I have a couple of comments about the coding style.

2023-02-14 16:13 UTC, brettle commented
Thanks for the feedback.

Why would color differ by graphics card in this case? For the image I'm exporting, I'm using a material that emits the pure color and for the image grabbed by the camera, I'm using such a bright light (with no attenuation) that the image should be saturated. If it's not, I can increase the light intensity until it is.

2023-02-14 22:43 UTC, brettle commented
Any idea why this is still failing on ubuntu-20.04? The exported image which is supposed be green is actually the color of the sky. I added additional planes to completely enclose the viewpoint (in colors that aren't the blue of the sky) and I changed the workflow to make the `tests/` directory available as an artifact if the test suite fails. The `GREEN.png` file from that artifact should be green but is this instead:

![GREEN](https://user-images.githubusercontent.com/118192/218879207-9e9769f4-2d74-4730-abf2-8f6fd2626067.png)

2023-02-17 08:36 UTC, omichel requested changes

2023-02-17 08:36 UTC, omichel commented on tests/with_rendering/controllers/supervisor_export_image/supervisor_export_image.c
> +
This doesn't seem to be used.
```suggestion
```

2023-02-17 08:36 UTC, omichel commented on tests/with_rendering/controllers/supervisor_export_image/supervisor_export_image.c
> +bool file_exists(const char *filename) {
```suggestion
static bool file_exists(const char *filename) {
```

2023-02-17 08:36 UTC, omichel commented on tests/with_rendering/controllers/supervisor_export_image/supervisor_export_image.c
> +  rotation[3] = angle_radians;
```suggestion
  double rotation[4] = {0.0, 0.0, 1.0, angle_radians};
```

2023-02-17 08:36 UTC, omichel commented on tests/with_rendering/worlds/supervisor_export_image.wbt
> +DEF Test Robot {
We generally use all caps for DEF names.
```suggestion
DEF TEST Robot {
```

2023-02-17 08:36 UTC, omichel commented on tests/with_rendering/controllers/supervisor_export_image/supervisor_export_image.c
> +  WbFieldRef rotation_field = wb_supervisor_node_get_field(wb_supervisor_node_get_from_def("Test"), "rotation");
```suggestion
  WbFieldRef rotation_field = wb_supervisor_node_get_field(wb_supervisor_node_get_from_def("TEST"), "rotation");
```

2023-02-17 19:28 UTC, omichel approved these changes
Thank you.

2023-02-17 19:33 UTC, merged