WebotsJS: fix parameters bugs
cyberbotics/webots pull request #5894
Opened 2023-02-14 14:57 UTC by BenjaminDeleze

**Description**

- Fix viewpoint when there is no boundingSphere
- Fix wrong defaultValues in jointWithBacklash MFNode
- Fix `toJS` method when the node is a baseNode and not a proto

2023-02-15 07:38 UTC, BenjaminDeleze commented
Fix a bug where two `ifs` have been converted to an `if, else`

2023-02-15 13:26 UTC, ad-daniel requested changes
Thank you
When I add a robot to the endPoint (say Crazyflie), and switch to the Devices tab, several errors related to the bounding sphere are thrown when hovering above some of the devices (gps, gyro, ...)

Similarly, in the Joints tab, everything seems to be working except the root joint (for crazyflie is crazyflie, for nao is nao)

2023-02-16 09:20 UTC, BenjaminDeleze commented
Okay I have lost some hairs with those ones:
I found several more bugs:
  - [x] I was calling ._boundingSphere directly instead of the .boundingSphere function. And the ._boundingSphere is not present in all objects
  - [x] When adding objects, the boundingSphere was not recalculated correctly. The solution I found is to recall postFinalize in order to trigger computation.
    It seems a bit overkill, but we will do it only once for each device so I think it is acceptable. I tried to use a modified version of the `recomputeBoundingSphere` function but it is a bit of a mess as it does not exist in all the classes.
  - [x] Some joints were not working because `_endPointZeroRotation` and `_endPointZeroTranslation` were not defined in the case when no endPoint was present at the node creation.
  - [ ] The anchor seems to "jump" in some special case when we change the endPoint.

2023-02-17 07:49 UTC, ad-daniel requested changes
Nice, seems to work well, thank you!

2023-02-17 07:49 UTC, ad-daniel commented on resources/web/wwi/nodes/utils/WbBoundingSphere.js
> +import WbWorld from '../WbWorld.js';
```suggestion
```

2023-02-17 07:49 UTC, ad-daniel commented on resources/web/wwi/nodes/utils/WbBoundingSphere.js
> +import WbWorld from '../WbWorld.js';
doesn't appear to be used

2023-02-17 09:02 UTC, ad-daniel approved these changes
Thank you

2023-02-17 09:04 UTC, merged