Add support for controllerArgs in MATLAB
cyberbotics/webots pull request #5943
Opened 2023-02-27 10:57 UTC by nilsjor

## Issue
As is stated in the documentation under [Using Controller Arguments](https://cyberbotics.com/doc/guide/controller-programming#using-controller-arguments):

>Note that using MATLAB, the controller arguments retrieval is not supported.

This is related to #5942, but will not necessarily resolve it. Also see [this commit](https://github.com/nilsjor/webots/commit/de9ec48234de38b0e3fd01f0cba598d645e56ede).

## Summary
In Webots, MATLAB controllers are launched as separate, headless instances of MATLAB, with an entrypoint called launcher.m. 
The launcher-file uses environment variables set by the Webots application to communicate the relevant information, including `WEBOTS_HOME`, `WEBOTS_CONTROLLER_NAME`, to name a few. 
These variables are set in Webots by `WbController::setProcessEnvironment()`, [or manually in external mode](https://cyberbotics.com/doc/guide/running-extern-robot-controllers#environment-variables).

The suggested change adds the following changes to the codebase:

1. By introducing a new environment variable—`WEBOTS_CONTROLLER_ARGS`—the arguments can be passed to the launcher in the same way as the controller name, which can then pass them on to the controller code.
2. The launcher has been altered to check for the presence of this variable, and to add it to the controller invocation.
3. The appropriate places in the documentation has also been updated to support this feature.

## Usage
Currently, Webot-controllers written in MATLAB are executed as "scripts", not "functions". Both are files with a .m-extension, but functions must start with a `function` declaration, see more [here](https://www.mathworks.com/help/matlab/matlab_prog/scripts-and-functions.html).
Arguments cannot be passed to scripts during invocation—only to functions—this is a well-documented feature of MATLAB, see [this](https://www.mathworks.com/matlabcentral/answers/51780-pass-parameters-to-script) and [this](https://www.mathworks.com/matlabcentral/answers/1601450-how-do-i-pass-input-parameters-when-running-a-script-within-another).

If a user wants arguments for their MATLAB controller, they must add the proper function declaration at the start of their controller. The built-in commands [`nargin`](https://www.mathworks.com/help/matlab/ref/nargin.html) and [`varargin`](https://www.mathworks.com/help/matlab/ref/varargin.html) can then be used in the controller, similar to `argc` and `argv` in C/C++.

If there are no arguments provided, the new launcher-invocation is still backwards-compatible with old scripts lacking the function declaration.
Conversely, if controller args are provided by the user, but the controller is missing the appropriate function declaration, it will throw the following error:
>```
> Error: Execution of script <controller_name> as a function is not supported ...
>```

This error will appear in the Webots console, and is very transparent, informing the user that the controller is not seen by MATLAB as a function.

2023-02-27 12:57 UTC, ygoumaz commented
Thanks for the great explanation of your contribution. I think the change from `scripts` to `functions` is worthwhile and would allow to be more consistent with C/C++ and other language capabilities. 

Before going into the code review and testing phase, I have a quick note: even if the change is not that big, it should be targeted at the `develop' branch, as this is a new feature/enhancement. In addition, we have developed a brand new launcher to greatly simplify the use of 'extern' controllers, which is already available in the develop branch (see #5629 for more details). This means that the launcher should also be adapted to pass the arguments to the MATLAB launcher sub-process. Also, the associated documentation (which you [already modified in this PR](https://github.com/cyberbotics/webots/pull/5943/files#diff-b641482f147659369e2a86771c2c0a72180c7e29b3e71497171cabd39208154c)) has completely changed in the new version.

Don't hesitate if you need any help with the new 'extern' controller launcher.

2023-02-27 16:00 UTC, nilsjor commented
Thank you for a quick reply. I have some questions below:

> I think the change from `scripts` to `functions` is worthwhile and would allow to be more consistent with C/C++ and other language capabilities.

I am glad you feel the same way. Should I commit those changes as part of this PR?

> ... even if the change is not that big, it should be targeted at the `develop' branch, as this is a new feature/enhancement. 

Can I change target somehow? Right now this is aimed at master. 

> In addition, we have developed a brand new launcher to greatly simplify the use of 'extern' controllers, which is already available in the develop branch (see #5629 for more details). This means that the launcher should also be adapted to pass the arguments to the MATLAB launcher sub-process. Also, the associated documentation (which you [already modified in this PR](https://github.com/cyberbotics/webots/pull/5943/files#diff-b641482f147659369e2a86771c2c0a72180c7e29b3e71497171cabd39208154c)) has completely changed in the new version.

I was able to merge my local `matlab-argv` branch with `develop`. The only conflict was, as you mention, the documentation for external mode. I could push that merge, if you then re-direct this PR to be aimed at develop. Otherwise, should i close this one and re-open a new one?

Thanks

2023-02-27 16:11 UTC, ygoumaz commented
I was able to rebase the PR to develop. You can solve the conflicts with the `Resolve conflicts` button on this Github page or do it locally by merging develop in your branch (as you may already have done).

> I am glad you feel the same way. Should I commit those changes as part of this PR?
Yes you can go ahead, I think this PR can contain all the changes mentioned by your issue.

You can now directly modify the launcher in `src/controller/launcher`.

2023-02-27 16:15 UTC, nilsjor commented
Thanks for the help! I have added what I have so far. I will commit my changes to launcher during the next few days

2023-03-02 14:27 UTC, nilsjor commented
I have completed the changes.  A summary of the commits:

d49a5377a6922807ba7841d438d86224b4742b4f : This commit adds a keyboard-controller to one of the worlds, re-written from a C-controller in the same project. It was used for testing, someone might find it useful so I left it in.

18f2061fe79573ed072d3611880631f038238efd : This commit does two things. First, it fixes an (unrelated) error with the new extern-launcher. When trying to run the above mentioned MATLAB-controller, I found that the `WEBOTS_PROJECT` variable was not being set correctly.
I was being set to:
```
'C:\msys64\home\Nils\webots\projects\robots\mir\mir100\controllers\keyboard_matlab\.\keyboard_matlab.m'
```
With the new fix, it is now correctly set to 
```
'C:\msys64\home\Nils\webots\projects\robots\mir\mir100'
```
Secondly, it makes the MATLAB invocation in the extern-launcher identical to the Webots internal one. One of the arguments was not a valid argument, and was generating a warning.

9ca9d8fdbbcf74ef10f92ee4f853b8cefbbf1a7a : This commit solves the original problem. It looks for the additional arguments passed to `webots-controller.exe`, and writes them to an environment variable. The delimiter depends on the OS.

1ada2486586392ad20d28d5299b6bf6af372157a : Finally, I just had to test this and it worked perfectly. Quoting from [MathWorks](https://www.mathworks.com/help/matlab/ref/matlabwindows.html):
> **R2019a**: -r option for non-interactive use is not recommended ⚠️ 
> To start MATLAB non-interactively, use the -batch option. To start MATLAB interactively, use the -r option.

The deprecated Matlab invocation
```
matlab -nosplash -nodesktop -minimize -r launcher
```
was replaced with the recommended
```
matlab -batch launcher
```
which does the following:
* Starts without the desktop
* Does not display the splash screen
* Executes statement
* Displays figure windows, unless combined with the -noFigureWindows option
* Displays user-generated modal dialog boxes, but does not display unprompted modal dialog boxes
* Disables changes to preferences
* Disables toolbox caching
* Logs text to stdout and stderr
* Exits automatically with exit code 0 if statement executes successfully. Otherwise, MATLAB terminates with a non-zero exit code.

2023-03-02 17:36 UTC, ygoumaz requested changes
I only went through the code and documentation modifications yet. Very good job, this is a very high quality contribution and the PR is nicely documented and explained.

I already have a few comments on the code. Sometimes some comments may be wrong, feel free to tell me if I did not understand everything correctly as I am not a MATLAB expert.

2023-03-03 12:13 UTC, nilsjor commented on src/controller/launcher/webots_controller.c
> +    _spawnvpe(_P_WAIT, windows_argv[0], windows_argv, NULL);
The reasoning is that this is identical to how they are invoked in Webots main application. Currently, there is no danger in doing this. In the long run, launcher might also be "function"-ized, with arguments passed directly.

2023-03-03 12:17 UTC, nilsjor commented on src/controller/launcher/webots_controller.c
> +      strcpy(varargin, new_argv[controller_args_size]);
I would love to get help with this one. I believe my intent is quite clear--but working with strings in C is hard work. I want to `join` the elements of a string array with `ENV_SEPARATOR` as the delimiter.

This code builds, and run. But this is currently where the [automated tests](https://github.com/cyberbotics/webots/actions/runs/4323255447/jobs/7546654976#step:6:144) fail:
```
Common realloc mistake: 'varargin' nulled but not freed upon failure [memleakOnRealloc]
```

2023-03-03 14:00 UTC, ygoumaz commented
I will take care of the modifications in the launcher. Do you mind if I commit directly to this PR?

2023-03-03 14:47 UTC, nilsjor commented
> I will take care of the modifications in the launcher. Do you mind if I commit directly to this PR?

Please feel free!

2023-03-03 15:11 UTC, nilsjor commented
I am having a stab at the C-code again

2023-03-03 15:14 UTC, omichel commented
It is simply a matter of removing some spaces here and there as we have a pretty picky coding style check in the CI.
The log shows you where to remove these spaces.

2023-03-03 15:40 UTC, ygoumaz commented
I pushed a cleaner solution, by handling the MATLAB case directly in the `add_controller_arguments` function of the launcher. Could you give it a try to see if it works? I did some tests but I am not sure that I have tested all cases.

With this approach, the arguments are not passed to the launcher anymore, but it will be very easy in the future to remove this part and simply let the arguments be added in the default way (if we functionize the launcher).

2023-03-03 15:45 UTC, ygoumaz commented
Actually, wouldn't it be better to modify the `launcher.m` so that it already accepts arguments in a function way? And also adapt the Webots code to make it consistent?

2023-03-03 15:48 UTC, ygoumaz commented on src/controller/launcher/webots_controller.c
> +      strcpy(varargin, new_argv[controller_args_size]);
Using `snprintf` is really safer and I think that it gives better code clarity. Take a look at the solution I just implemented for more details.

2023-03-03 15:49 UTC, ygoumaz commented on src/controller/launcher/webots_controller.c
> +    _spawnvpe(_P_WAIT, windows_argv[0], windows_argv, NULL);
As commented below, I am wondering if we should not already adapt launcher.m so that it takes arguments in a 'functionized' way?

2023-03-03 16:01 UTC, nilsjor commented
> Actually, wouldn't it be better to modify the `launcher.m` so that it already accepts arguments in a function way? And also adapt the Webots code to make it consistent?

I did have a quick look. It was not nearly as straight-forward as making controllers as functions, which is why I am holding off on it. The controller name, webots-path etc. would need to be passed on too. Personally, I feel that it should be its own milestone.

2023-03-03 16:22 UTC, ygoumaz commented
I have fixed the sources issue, all tests should pass now. Just a quick note to let you know that I will be off next week, so I will resume with more in-depth tests on Monday the 13th.

2023-03-07 15:23 UTC, nilsjor commented
> I have fixed the sources issue, all tests should pass now. Just a quick note to let you know that I will be off next week, so I will resume with more in-depth tests on Monday the 13th.

I have tested the new argument-parsing from ba4b54a0ed247de0216d95a10ce7d53fb36343f7. **It does not work for more than one argument!**

```
webots-controller.exe keyboard_matlab.m one two three
```
gives
```
WEBOTS_CONTROLLER_ARGS =

    'one'
```

Additionally, I have discovered another issue with the extern launcher. At first, I thought this was just something I had done wrong when setting up MSYS, but I have this issue when using the released version installed in Program Files too...

When launching controllers "normally" using Webots, upon inspecting the PATH variable for the controllers I find that the path contains
```
PATH = 

    %WEBOTS_HOME%\msys64\mingw64\bin\cpp;
    %PATH%;
    %USER_PATH%;
    %WEBOTS_HOME%\lib\controller
```
In other words, some Webots process has at two separate stages appended `%WEBOTS_HOME%\msys64\mingw64\bin\cpp` to the start, then `%WEBOTS_HOME%\lib\controller` at the end of the string. 

I believe `src\webots\launcher\launcher.c` is responsible for the the first edit, as can be read in the comments 
> It adds paths to the PATH environment variable to ensure that the correct libraries will be found ...

However, I have not yet been able to track down the process that causes the second addition. This last addition to the PATH is essential for MATLAB controllers to function! Otherwise you are met with the following error:
```
Error using loadlibrary
There was an error loading the library "Controller"
The specified module could not be found.

Error in launcher (line 148)
    loadlibrary(libname,protofile,'alias','libController');

Caused by:
    Error using loaddefinedlibrary
    The specified module could not be found.
```
I have been manually adding `lib\controller` inside launcher.m during testing to bypass this, but If the extern-launcher is meant to be truly comprehensive, this modification to PATH should be handled too. This is provided by 1b65a789e7c167a293889631d96cae1f2d76befa.

Finally, I have submitted one more minor edit:

9a31cd612495cfb3802f51153176f109638c87c7: I have discovered that redirecting to stdout on external contollers on Windows with the new `batch` mode only works using `matlabroot\bin\matlab.exe` rather than `matlabroot\bin\<arch>\MATLAB.exe`. This also seems to be the more general case, which is an improvement, see [this](https://www.mathworks.com/matlabcentral/answers/227181-what-is-the-difference-between-matlab-exe-in-matlabroot-bin-and-matlabroot-bin-arch-directory-in) question.

2023-03-14 08:16 UTC, ygoumaz commented
Thank you for providing the additional information regarding the fixes. I will investigate the issue when multiple arguments are passed.

Regarding the controller library to be added to the Path, it makes sense to include it as it was already required in the old documentation of external controllers. However, I noticed that in the commit you linked, the libController path was only added for macOS and Windows. Can you please clarify if there was a specific reason for omitting Linux? Shouldn't we add `$WEBOTS_HOME/lib/controller` to `LD_LIBRARY_PATH`?

In any case, I will begin testing on all platforms, with and without launcher. Thank you again for the updates and I will keep you informed of any progress.

2023-03-14 14:52 UTC, ygoumaz commented
I tested MATLAB controllers from Webots and from the launcher on all platforms and it works very well. I even added the possibility to play a demo movement if the 'demo' argument is given. This feature is present in the C controller, and it can now be used in the MATLAB controller.

2023-03-14 15:03 UTC, ygoumaz commented
Could you please test the latest changes and check that everything still works on your side. Once done, I will do the final review!

2023-03-14 23:56 UTC, nilsjor commented
I will have a look by the end of the week. Nice touch with the youbot demo!

I have not yet fixed the case with the missing PATH for linux, perhaps you did already? 

2023-03-15 15:33 UTC, nilsjor commented
There, I have submitted the final commit—sorry about the force-push, clang-format got annoyed...

This is it from me, I think! I have been using the latest build for my project (my real job) the last few hours. It works great! :)

**Disclaimer:** I am running this on Windows 10, with MATLAB R2021a. This is probably a pretty typical setup, but it should still be mentioned that have not tested it on macOS or Linux. 

I have to say that the new extern-launcher is excellent, together with the new `batch`-mode execution of controllers means that `fprintf` can be used freely, and that the resulting output stays persists in the shell-window where the launcher was called. This has enabled a whole new workflow, where the MATLAB IDE can be neglected completely.

I still have a few other ideas for improvements, but I will create separate issues for them—they are not related to #5942.

2023-03-16 10:19 UTC, omichel approved these changes
Looks very good to me.
Thank you.

2023-03-16 10:56 UTC, ygoumaz submitted a review, later dismissed
I tested on all platforms and it works nicely! Thank you for the great contribution!

2023-03-16 11:00 UTC, ygoumaz requested changes
[changelog-r2023.md](https://github.com/cyberbotics/webots/blob/develop/docs/reference/changelog-r2023.md) should be updated.

2023-03-20 16:01 UTC, ygoumaz approved these changes

2023-03-20 16:33 UTC, merged