Fix invalid robot names
cyberbotics/webots pull request #5959
Opened 2023-03-01 16:03 UTC by ad-daniel

**Description**

Fixes https://github.com/cyberbotics/webots/issues/5452

This PR:
- If the percentage-encoded robot name length is beyond an arbitrary size of 70 characters, a hash is used instead. The risk is that if the Robot name contains non-ASCII characters, the percentage encoding can result in a huge string which ends up crashing the controller when the connection takes place (QLocalServer has a limit of 106 characters for the server name)
- Reverts https://github.com/cyberbotics/webots/pull/5484 so that "/tmp" is used instead of `TMP_DIR` and changes the permissions so that multiple users can

2023-03-10 07:23 UTC, ad-daniel commented
I've tested it on linux and macos, couldn't test on windows

2023-03-10 09:09 UTC, omichel requested changes
It looks very good to me.
I am now testing on Windows different use-cases, including local and remote controllers.

2023-03-10 10:13 UTC, omichel submitted a review, later dismissed

2023-03-10 10:14 UTC, omichel commented
I would also add a line in the change log.

2023-03-10 13:19 UTC, omichel approved these changes
Thank you.

2023-03-10 13:24 UTC, merged

2023-04-13 07:53 UTC, omichel commented on src/webots/control/WbController.cpp
> +  QProcess::execute("sh", QStringList() << "-c" << QString("chmod -R 777 %1").arg(mIpcPath));
This code seems wrong: useless and not working on Windows where it is supposed to be executed.