Remove the duplicate PROTO documentation from the user guide to use webots.cloud instead
cyberbotics/webots pull request #6148
Opened 2023-05-17 07:03 UTC by omichel

To avoid the duplication of the PROTO documentation, this PR removes the documentation of PROTO nodes from the Webots user guide and adds pointers to the interactive PROTO documentation on https://webots.cloud.
In addition to this, this PR also make some clean-up in this documentation.

2023-06-05 13:29 UTC, BenjaminDeleze requested changes
The references to the protos seem to have been modified correctly, however:

- All the scenes under `docs/guide/scenes` should be removed.
- Remove the `scripts/web_component_studio`
- I am not sure if it makes sense to keep all the `automobile/vehicle-lincoln.md` and so on.
- Remove the 3d viewer dependencies.

2023-06-06 13:00 UTC, BenjaminDeleze requested changes
The `wwi/viewer.js` could be removed

2023-06-06 14:11 UTC, omichel commented on docs/automobile/proto-nodes.md
> +- [AckermannVehicle](https://webots.cloud/run?url={{ url.github_tree }}/projects/vehicles/protos/abstract/AckermannVehicle.proto) is the base class of almost all vehicles.
We decided to keep the actual version URL so that the version of the PROTO model referred to matches with the version of the documentation.

2023-06-07 13:32 UTC, omichel commented
> I get an error: `Uncaught ReferenceError: setupModalWindow is not defined at viewer.js:1098:1`

It should be fixed now, see https://cyberbotics.com/doc/guide/index?version=0dedead90f631452ff13281c06000cd3972dc0fa

2023-06-07 14:06 UTC, BenjaminDeleze approved these changes
Thank you!

2023-06-07 14:13 UTC, merged