Improve webotsJS
cyberbotics/webots pull request #6280
Opened 2023-06-30 06:22 UTC by BenjaminDeleze

**Description**

- [x] Add tracks to the surveyor
  - [x]  keep possibility to have wheels to maintain compatibility with the controller
  - [x] create new controller
- [ ] Fix errors related with tracks in webotsJS
- [ ] Remove `vrmlField` and replace the field we want to export to the web by `w3dField`
  - [ ] change wrl and webots parsing
  - [ ] change exports functions
- [ ] Replace `.x3d` format with `.w3d`
  - [ ] webots side
  - [ ] webotsJS side
  - [ ] webots.cloud
  - [ ] documentation

We decided to replace `x3d` because the `x3d` used by webots is so extended that it is not  really `x3d` anymore (see #3615 ) by our own format: `w3d`. In practice only the name and file extension will change, the content will remain the same.

Concerning the `vrmlField`, we do not support vrml import/export anymore. Moreover, currently, only the `vrmlField` are exported to webotsJS. It induces a lot of custom export to get some fields that we need in webotsJS but that are currently not `vrmlField`.

2023-07-07 16:04 UTC, omichel approved these changes
I reviewed the code and tested the W3D export and everything looks good to me. However, since this is a big PR, a second review would be nice.

2023-07-10 12:07 UTC, stefaniapedrazzi requested changes
I tested and I could find only one issue with the visualization of the `TrackWheel` and the `Track.animatedGeometries`:
the initial position of the TrackWheel and `Track.animatedGeometries` doesn't match the one in Webots at load, but at least for the TrackWheel nodes the position is adjusted after the first simulation step.

Steps to reproduce:
1. Run track.wbt
2. Reduce the `Track.geometriesCount` to 10 (in order to better visualize the position)
3. Save the simulation at time step != 0
4. Restart Webots in pause mode and with streaming option
5. Connect from the streaming viewer -> the orientation of the track wheels and the position/orientation of the animatedGeometries in WebotsJS differs from the one in Webots
6. Run one simulation step
-> the TrackWheel geometry jumps to the correct position, but the animated geometries still differ in Webots and WebotsJS

2023-07-10 12:07 UTC, stefaniapedrazzi commented on projects/robots/surveyor/controllers/surveyor/surveyor.c
> +  float speed = 0.05;
```suggestion
  const int timeStep = wb_robot_get_basic_time_step();
  const float speed = 0.05;
```

2023-07-10 12:07 UTC, stefaniapedrazzi commented on projects/robots/surveyor/controllers/surveyor/surveyor.c
> +    int key = wb_keyboard_get_key();
```suggestion
    const int key = wb_keyboard_get_key();
```

2023-07-17 08:37 UTC, BenjaminDeleze commented
> I tested and I could find only one issue with the visualization of the `TrackWheel` and the `Track.animatedGeometries`: the initial position of the TrackWheel and `Track.animatedGeometries` doesn't match the one in Webots at load, but at least for the TrackWheel nodes the position is adjusted after the first simulation step.
> 
> Steps to reproduce:
> 
> 1. Run track.wbt
> 2. Reduce the `Track.geometriesCount` to 10 (in order to better visualize the position)
> 3. Save the simulation at time step != 0
> 4. Restart Webots in pause mode and with streaming option
> 5. Connect from the streaming viewer -> the orientation of the track wheels and the position/orientation of the animatedGeometries in WebotsJS differs from the one in Webots
> 6. Run one simulation step
>    -> the TrackWheel geometry jumps to the correct position, but the animated geometries still differ in Webots and WebotsJS

I fixed it for `TrackWheels`, it was because the rotation field is an hiddenField so it was not initially exported to w3d so I had to manually do it.

For the animated geometries, I think it is normal and we can let it like that because we send to webotsJS only the following information:
- The  `animatedGeometry`
- The `geometriesCount`
And webotsJS build all the track animated geometries from that.
So it has no idea of where are the animated geometires on webotsJS side.

2023-07-17 08:47 UTC, BenjaminDeleze commented on resources/nodes/Solid.wrl
> +  field    SFString   name                "solid"      # used by wb_robot_get_device()
I thought at first glance it was correct, but no, we need it for the `follow` functionality.

2023-07-17 08:59 UTC, BenjaminDeleze commented on resources/web/wwi/Parser.js
> +    const followSmoothness = parseFloat(getNodeAttribute(node, 'followSmoothness', 0.5));
The followSmoothness is still exported because it is a `w3dField`

2023-07-17 12:26 UTC, BenjaminDeleze commented on src/webots/vrml/WbNode.hpp
> +  virtual QStringList fieldsToSynchronizeWithW3D() const { return QStringList(); }
I checked and it was already the case with `X3d` and `X3D`. However I am not sure if it is better to put `W3D` or `W3d` everywhere.

2023-07-20 07:45 UTC, omichel submitted a review, later dismissed
Thank you.

2023-07-20 07:47 UTC, omichel commented on src/webots/vrml/WbNode.hpp
> +  virtual QStringList fieldsToSynchronizeWithW3D() const { return QStringList(); }
I would go for `W3d` as it is a word per see.

2023-08-14 11:40 UTC, BenjaminDeleze commented
I just changed the `X3D` to `X3d` in function name

2023-08-14 11:48 UTC, omichel approved these changes
Thank you.

2023-08-14 11:52 UTC, merged