Add Silo and Ditch PROTO models
cyberbotics/webots pull request #6289
Opened 2023-07-03 12:34 UTC by stefaniapedrazzi

Ditto.

2023-07-03 14:37 UTC, BenjaminDeleze requested changes
Thank you!
Just some minor remarks:
- It would be nice to integrate the new protos in existing world (in `Boomer.wbt` for example).
- The appearance of the `Silo` does not really match with its icon (in which the Silo is green). And I think that the current appearance of the Silo is too `metallic`, but that's subjective.
- As `coneHeight` is already a variable, it may be nice to make it a parameter as 2 meters could be strange depending on the `radius`.

2023-07-03 14:37 UTC, BenjaminDeleze commented on projects/objects/buildings/protos/Silo.proto
> +EXTERNPROTO "https://raw.githubusercontent.com/cyberbotics/webots/R2023b/projects/appearances/protos/BrushedSteel.proto"
```suggestion
EXTERNPROTO "webots://projects/appearances/protos/BrushedSteel.proto"
```

2023-07-03 14:37 UTC, BenjaminDeleze commented on projects/objects/buildings/protos/Silo.proto
> +  field SFBool     locked               TRUE
Is it really a good idea to lock it by default?
As a user I would like to insert it, move it and then lock it.

2023-07-03 14:37 UTC, BenjaminDeleze commented on projects/objects/floors/protos/Ditch.proto
> +EXTERNPROTO "https://raw.githubusercontent.com/cyberbotics/webots/R2023b/projects/appearances/protos/SandyGround.proto"
```suggestion
EXTERNPROTO "webots://projects/appearances/protos/SandyGround.proto"
```

2023-07-03 14:37 UTC, BenjaminDeleze commented on projects/objects/floors/protos/Ditch.proto
> +  field SFInt32    randomSeed     1                                                                  # Defines whether the bounds of the terrain should be flat.
The alignment of comments seems wrong

2023-07-03 14:40 UTC, stefaniapedrazzi commented
> The appearance of the Silo does not really match with its icon (in which the Silo is green). 

It is metallic, so it reflects the background and the appearance depends on the background used in the world.

2023-07-05 06:37 UTC, stefaniapedrazzi commented
The conflicts has been resolved, but this GitHub PR page doesn't get updated.
I will wait a little bit to check if it changes otherwise I will close this PR and open a new one.

2023-07-05 06:52 UTC, closed without merging