Fix omni directional cylindrical test failing
cyberbotics/webots pull request #6403
Opened 2023-10-04 16:47 UTC by TheMangalex

**Description**
Fixes a failing test due to #6396

I changed the mIsOmniDirectional variable back to being horizontalFOV > M_PI and instead reprojected all back points to fix the issue from #6395

I additionally added another object to the recognition test which is perpendicular to the sensor plane to ensure that these objects are also correctly recognized. 

I want to add another test which checks that the recognized position is correct as this was a problem in #6395

**Related Issues**
This pull-request addresses issue #6395

**Screenshots**
Newly added object for test
<img width="334" alt="image" src="https://github.com/cyberbotics/webots/assets/26520790/ba6806ac-a3cf-48ab-be06-855a9cea90a6">

Fixed detection
<img width="259" alt="image" src="https://github.com/cyberbotics/webots/assets/26520790/920dd0f7-7aa4-42a6-9278-4469c70b5e06">

2023-10-05 05:56 UTC, omichel requested changes
We should fix clang format errors.

2023-10-05 05:56 UTC, omichel commented on tests/api/controllers/camera_recognition/camera_recognition.c
> +  "visible sphere", "visible box", "sub solid", "visible capsule", "composed solid", "visible sphere without BO", "perpendicular box"};
clang format fix:
```suggestion
  "visible sphere", "visible box", "sub solid", "visible capsule", "composed solid", "visible sphere without BO",
  "perpendicular box"};
```

2023-10-05 05:56 UTC, omichel commented on tests/api/controllers/camera_recognition/camera_recognition.c
> +    object_number);
clang format:
```suggestion
  ts_assert_int_equal(object_number, VISIBLE_SOLID_NUMBER + 4,
                      "The spherical camera should initially see %d objects and not %d (with occlusion).",
                      VISIBLE_SOLID_NUMBER + 4, object_number);
```

2023-10-05 05:56 UTC, omichel commented on tests/api/controllers/camera_recognition/camera_recognition.c
> +    VISIBLE_SOLID_NUMBER + 2, object_number);
clang format fix:
```suggestion
  ts_assert_int_equal(object_number, VISIBLE_SOLID_NUMBER + 2,
                      "The cylindrical camera should initially see %d objects and not %d (with occlusion).",
                      VISIBLE_SOLID_NUMBER + 2, object_number);
```

2023-10-06 06:22 UTC, omichel commented
It seems that there are more clang format issues.

2023-10-06 10:50 UTC, TheMangalex commented
I did another update to the clang formatting. This time it seems all test were running successful.

2023-10-06 10:52 UTC, omichel commented
Thank you. Is the PR ready for review? (It is still marked as Draft.)

2023-10-06 10:53 UTC, TheMangalex commented
Yes, I updated it now.

2023-10-06 14:26 UTC, omichel approved these changes
That looks great to me.
Thank you.

2023-10-06 14:46 UTC, merged