Allow Indirect Field Accesses in Proto Templates
cyberbotics/webots pull request #6614
Opened 2024-08-04 00:52 UTC by CoolSpy3

**Description**
Allows use of the raw `fields` variable in proto templates.

**Related Issues**
This pull-request fixes issue #6566.

**Tasks**
Add the list of tasks of this PR.
  - [x] Allow the use of the `fields` variable in proto templates.
  - [x] Add tests for the new behavior
  - [ ] ~~Update the documentation~~ (By my reading of the current documentation [[lua](https://cyberbotics.com/doc/reference/lua-procedural-proto?tab-language=java#programming-facts)] [[javascript](https://cyberbotics.com/doc/reference/javascript-procedural-proto#programming-facts)], the new behavior is already described.)
  - [ ] Update the [changelog](https://github.com/cyberbotics/webots/blob/master/docs/reference/changelog-r2024.md)

2024-08-04 02:19 UTC, CoolSpy3 commented
The CI failure does appear to be reproducible on this branch and not `master`, so I'm marking this PR as a draft until I have time to investigate it.

2024-08-04 07:48 UTC, CoolSpy3 commented
It looks like the `Car` proto is being regenerated as a result of these changes, causing the controller to restart. Thus, the test supervisor thinks there's three controllers running, but it only receives completion reports from two of them. I still have to find a good workaround. The only real solution I can think of is gating the behavior behind a tag. (i.e. `# tags: fieldsObject`/`# tags: indirectFieldAccess` [open to suggestions on the name]). However, if someone else has another idea, feel free to let me know.

Side note: In general, proto robots having their controllers restarted when they're regenerated seems a little unintuitive, however, any proposed behavior I can think of has some annoying edge cases. I think the best option is just to make a note of it in the proto docs. If others feel that we should update this behavior in some way, one of us can open a new issue with the proposed behavior.

2024-08-04 22:45 UTC, CoolSpy3 commented
Note: It's hard to tell from the diff, but `WbProtoModel:219` (Now `227`) and `WbProtoModel:281` (Now `292`) are not identical to their pre-edit counterparts.

2024-08-12 10:29 UTC, omichel requested changes
It looks good to me.

2024-08-12 10:29 UTC, omichel commented on tests/protos/worlds/template_indirect_field_access_lua.wbt
> +		}
```suggestion
    }
```

2024-08-12 10:29 UTC, omichel commented on tests/protos/worlds/template_indirect_field_access.wbt
> +		}
```suggestion
    }
```

2024-08-12 19:57 UTC, omichel approved these changes
Thank you.

2024-08-12 20:05 UTC, merged