Fix incomplete loading while minimized under some windowing systems.
cyberbotics/webots pull request #6617
Opened 2024-08-08 22:05 UTC by brettle

**Description**

Under some window systems (notably linux wayland), `QWindow::isExposed()` always returns false if the window is minimized (e.g. when running tests). This was preventing the initial non-culling call to `renderNow()` from accomplishing its goal of ensuring that meshes/textures are loaded onto the GPU. (This resulted in the `skin` test failing because the aabb for the skin was not calculated using the skeleton.) This fixes that by allowing the non-culling call to proceed even if the window is not exposed. It also suppresses the resulting errors/warnings *only* for that call because several of the parsing tests fail if the stderr output is not empty.

**Tasks**
Add the list of tasks of this PR.
  - [X] Update the [changelog](https://github.com/cyberbotics/webots/blob/master/docs/reference/changelog-r2024.md)

2024-08-09 06:35 UTC, omichel requested changes
I am afraid that disabling all GL errors in the CI tests (under wayland) might open the door to some tests passing whereas they should actually fail. Why not disabling minimization in the CI tests?

2024-08-09 06:35 UTC, omichel commented on src/webots/gui/WbView3D.cpp
> +  // GPU If the window is not yet exposed (e.g. minimized under Wayland) this can produce some GL
```suggestion
  // GPU if the window is not yet exposed (e.g. minimized under Wayland) this can produce some GL
```

2024-08-09 06:35 UTC, omichel commented on docs/reference/changelog-r2024.md
> +    - Fixed incomplete loading while minimized under some windowing systems ([#6616](https://github.com/cyberbotics/webots/pull/6616)).
```suggestion
    - Fixed incomplete loading while minimized under some windowing systems ([#6617](https://github.com/cyberbotics/webots/pull/6617)).
```

2024-08-09 06:35 UTC, omichel commented on src/webots/gui/WbView3D.cpp
> +  bool exposed = isExposed();
```suggestion
  const bool exposed = isExposed();
```

2024-08-09 13:41 UTC, brettle commented
> I am afraid that disabling all GL errors in the CI tests (under wayland) might open the door to some tests passing whereas they should actually fail. Why not disabling minimization in the CI tests?

It's useful to run the CI tests locally while doing other work simultaneously, so I'd really rather not disable minimization. Moreover, if the tests (other than the "with-rendering" tests) fail while minimized, that is arguably a bug.

Note that the suppression is only for the initial post-load rendering pass. Any test which does more than one timestep will do at least one rendering pass without suppression and if the test requires no error output it will still fail.

If that doesn't address you concern, would it be addressed by only doing the suppression if some env var is set and setting that env var in `test_suite.py`? If so, let me know if you have a preferred env var name.

2024-08-09 17:15 UTC, brettle commented
I could also *not* set the env var in test_suite.py and instead output a message mentioning it when we detect the situation where it might be useful. Something along the lines of "WARNING: Webots will print errors/warnings because your windowing system does not support rendering to minimized windows. To suppress those, set WEBOTS_QUIET_MINIMIZED_RENDERING=true in your environment."

2024-08-09 18:32 UTC, brettle commented
Thinking about this some more, I'm wondering if instead of this PR, we should just make the initial non-culling render target a FBO instead of the window's framebuffer. I *think* that would succeed without errors/warnings even if the window was not exposed. Thoughts?

2024-08-09 21:42 UTC, omichel commented
> Thinking about this some more, I'm wondering if instead of this PR, we should just make the initial non-culling render target a FBO instead of the window's framebuffer. I _think_ that would succeed without errors/warnings even if the window was not exposed. Thoughts?

Yes, if that works, it would be ideal.

2024-08-13 15:39 UTC, brettle commented
> I am afraid that disabling all GL errors in the CI tests (under wayland) might open the door to some tests passing whereas they should actually fail. Why not disabling minimization in the CI tests?

Latest commit no longer disables error reporting.

2024-08-13 15:52 UTC, brettle commented
> > Thinking about this some more, I'm wondering if instead of this PR, we should just make the initial non-culling render target a FBO instead of the window's framebuffer. I _think_ that would succeed without errors/warnings even if the window was not exposed. Thoughts?
> 
> Yes, if that works, it would be ideal.

Afaict, it was already rendering to an FBO, so I mostly just needed to ensure that it would still render if not exposed. The only things that were triggering errors were blitting of the render to the screen, swapping buffers, and clearing the default framebuffer during postprocessing. The first 2 were easy to disable for the initial render. The clearing of the default framebuffer during postprocessing doesn't *appear* to be needed (and seems like it could cause other problems) so this removes it.

2024-08-14 15:28 UTC, omichel approved these changes
That looks much better this way to me.
Thank you.

2024-08-14 16:37 UTC, merged