Remove ROS1 support
cyberbotics/webots pull request #6697
Opened 2024-11-13 15:50 UTC by MNikoliCC

**Description**
Remove ROS 1 support from Webots, including dependencies, code, and documentation references.

**Tasks**
Add the list of tasks of this PR.
  - [x] Remove ROS 1 support from Webots, including dependencies
  - [x] Update documentation to reflect the removal of ROS 1 support

**Additional context**
This PR aims to streamline the codebase by fully removing ROS 1 support. Note any related issues, deprecations, or compatibility changes here.

2024-11-14 11:22 UTC, lukicdarkoo requested changes
Looks good, I believe there are only two places left:
- `.github/workflows/test_suite_linux_develop.yml`
- `.github/workflows/test_suite_linux_develop.yml`

2024-11-14 11:22 UTC, lukicdarkoo commented on docs/reference/changelog-r2024.md
> +    - Remove ROS1 support ([#6697](https://github.com/cyberbotics/webots/pull/6697)).
```suggestion
    - Removed ROS (1) support ([#6697](https://github.com/cyberbotics/webots/pull/6697)).
```

2024-11-14 11:22 UTC, lukicdarkoo commented on docs/reference/robot.md
> +> **note** [Java, Python, MATLAB]: `wb_robot_wwi_receive` and `wb_robot_window_send` functions are not available in the Java, Python or MATLAB API.
```suggestion
> **note** [Java, Python, MATLAB]: `wb_robot_wwi_receive` and `wb_robot_window_send` functions are not available in the Java, Python, or MATLAB API.
```

2024-11-14 11:30 UTC, MNikoliCC commented
> Looks good, I believe there are only two places left:
> 
> * `.github/workflows/test_suite_linux_develop.yml`
> * `.github/workflows/test_suite_linux_develop.yml`

Aren't those the same files?
The file is already modified.

2024-11-14 15:14 UTC, MNikoliCC commented
> @MNikoliCC Sorry, the other file is `.github/workflows/test_suite_linux.yml`. It uses the non-existing flag `--exclude-ros`.
> 
> Regarding `.github/workflows/test_suite_linux_develop.yml`, no, this file is not changed, you changed only `test_suite_linux.yml`.

Sorry for the oversight, here are the changes.

2024-11-15 12:13 UTC, lukicdarkoo approved these changes
Thank you

2024-11-15 12:45 UTC, merged