Remove Ubuntu 20.04 and add 24.04 support
cyberbotics/webots pull request #6704
Opened 2024-11-18 12:16 UTC by MNikoliCC

**Description**
This pull-request focuses on removing support for Ubuntu 20.04 and adding support for Ubuntu 24.04. This involves updating dependencies, testing compatibility, and ensuring smooth packaging for the newer distribution.

**Tasks**
Add the list of tasks of this PR.
  - [ ] Update the [changelog](https://github.com/cyberbotics/webots/blob/master/docs/reference/changelog-r2024.md)
  - [ ] Update the documentation
  - [ ] Remove Ubuntu 20.04-specific dependencies and configurations.
  - [ ] Add Ubuntu 24.04 support in scripts and packaging workflows.
  - [ ]  Test and validate compatibility with Ubuntu 24.04.
  - [ ]  Update CI/CD pipelines for Ubuntu 24.04.

**Additional context**
This update transitions Webots to the latest supported LTS versions of Ubuntu. While dropping 20.04, the focus is on enhancing compatibility and functionality for users adopting Ubuntu 24.04. This ensures alignment with modern software ecosystems and provides access to newer libraries and features.

2024-11-25 14:15 UTC, MNikoliCC commented on projects/languages/java/controllers/Driver/Driver.java
> +    controller.initialize();
This is needed to avoid the "this-escape" warning on Java 21.

2024-11-26 12:46 UTC, lukicdarkoo requested changes
In general it looks good, there is one issue I noticed.

Please also check once more the following PR as a reference:
https://github.com/cyberbotics/webots/pull/4502

2024-11-26 12:46 UTC, lukicdarkoo commented on tests/test_suite.py
> +                        (filename.endswith('robot_window_html.wbt') and (is_ubuntu_22_04 or is_ubuntu_24_04)) or
This added condition means `supervisor_start_stop_movie.wbt` and `robot_window_html.wbt` will not be tested at all on Linux. We should check if we can test it at least for one version of Ubuntu

2024-11-26 12:46 UTC, lukicdarkoo commented on scripts/packaging/linux_distro.py
> +        "libwebp.so.7",
Here we are missing some libraries. We discussed them, but just leaving a note

2024-11-26 12:46 UTC, lukicdarkoo commented on scripts/packaging/linux_distro.py
> +        "libwebp.so.7",
I believe these libraries are related to the tar distribution. It would be good to test the tar distribution on a clean Ubuntu 24.04

2024-11-28 16:23 UTC, lukicdarkoo approved these changes
Looks good, thank you

2024-11-29 14:55 UTC, lukicdarkoo approved these changes

2024-12-02 10:31 UTC, merged