Fix
cyberbotics/webots pull request #6717
Opened 2024-12-03 14:31 UTC by MNikoliCC

**Description**
The `EXTERNPROTO` import paths for certain PROTO files were incorrectly referencing raw GitHub URLs, such as `https://raw.githubusercontent.com/cyberbotics/webots/R2025a/`.... This has been fixed by replacing them with the correct Webots-specific protocol `webots://`.

**Related Issues**
Fixes #6716

**Tasks**
Add the list of tasks of this PR.
  - [ ] Fix bug

2024-12-03 14:48 UTC, MNikoliCC commented
This is the new warning that produces the Heron USV robot to fall into the sea, because there is no bounding object:
```
WARNING: Heron "heron":  Skipped node: Cannot insert Transform node in 'boundingObject' field of Robot node in bounding object.
WARNING: Heron "heron": Mass is invalid because 'boundingObject' is not defined. Using default mass properties: mass = 1, inertia matrix = identity
```
A workaround would be to make a simple bounding object from multiple Pose nodes instead of loading the whole mesh and scaling it down. This would reduce the complexity of the simulation as well.

2024-12-04 10:38 UTC, MNikoliCC commented
After adding the boundingObject, the simulation is working as expected.

2024-12-04 11:05 UTC, lukicdarkoo requested changes
Looks good, just remove the changelog

2024-12-04 11:05 UTC, lukicdarkoo commented on docs/reference/changelog-r2025.md
> +    - Fixed Heron USV warnings regarding the importing of PROTO files and the boundingObject description ([#6717](https://github.com/cyberbotics/webots/pull/6717)).
This is not needed as the model wasn't present in the previous Webots version

2024-12-04 12:15 UTC, lukicdarkoo approved these changes
Thank you

2024-12-05 11:11 UTC, MNikoliCC commented
Whit this change (decimating the mesh), the last warning is fixed:
`WARNING: Heron "heron" > DEF HERON Shape > Mesh "": Too many triangles (23409) in mesh: unable to cast shadows, please reduce the number of triangles below 21845 or set Shape.castShadows to FALSE to disable this warning.`

2024-12-05 13:16 UTC, lukicdarkoo approved these changes

2024-12-05 13:22 UTC, merged